### ISSUE TITLE
Have a showdown tournament/ Another world cup 

### ISSUE THREAD

**Issue by Sadkeemstar112** [SmashMC-Development/Suggestions#1004]
**Describe the suggestion**
So my goal with this github post is to bring back world cup or have a showdown tournament in pixelmon. So to start it all of a lot of players that like to battle (my self included) wants another world cup or something big to happen on the server. I actually scrolled a bit in announcements and found that almost 2 years ago on smashmc it was a showdown tournament that was for 2 or 3 months. Each tourney was 1 month so it was in total of 2 or 3 showdown tournaments. But whould it not be fun if we could combine the two into one. So a lot of players here are familiar with how the world cup was played out we had qualifiers on each server every week for 6 weeks then all the players that qualified went and played in the world cup tournament. But what if the server hosted a showdown tournament on each server every 1-2 weeks. So after the 2 weeks the player with the highest score/elo got a qualification to the world cup on the server they played on and it was in total lets say 6 tournaments. Why whould this be better than just having a tournament every week and the player that wins it can just move on. So i think we all are familiar with how moves can miss or that u just get really unlucky the game if u have a showdown system and u battle a lot and are really consistent u should not have a problem with getting a lot of points.  I think the rewards should be the same as last world cups qualifiers it was a legend crate key to the player that qualified. Another big factor why i want a showdown tournament instead of a qualifiers round is that timezones play a big factor in what qualifiers u can attend or not. But if world cup is not getting hosted i think its still a great idea to have a showdown tournament as a event to get more players into competitive.  With the rewards of world cup i know that IRL money is not allowed as rewards but the rewards can be gift cards in the store and a discord rank saying (Winner of World cup 2022) So players feel a little bit more rewarded.  The Showdown system i was thinking it will be a pluggin like warzones system but the elo or rating gets reset after a time and the winners will be given a legendary crate key and a ticket to the world cup qualifiers. Kind regards Kermstar 

**Which servers does this apply to?**
All servers 

**Additional context**
![image](https://user-images.githubusercontent.com/86523809/168468155-416a978f-434f-4424-a3b7-80dacb278af0.png)

![image](https://user-images.githubusercontent.com/86523809/168468162-ae5665af-ebc3-44a5-8d0d-ce8f1df765d6.png)

![image](https://user-images.githubusercontent.com/86523809/168474806-392b96f1-11c7-4068-9293-865370eba700.png)

**Comment by WalkAway7** [comment]
Yeah I love this idea. Perks to doing this on showdown is that there won't be any risk of a waiting glitch or similar pixelmon side issues. Only thing I have to say is that this would be a huge effort on the staffs side. I've hosted a few showdown tourneys in one of my servers, and sometimes they can be a real headache, even if there is only 20 people joining. But if it can be done in a organised fashion, I'm all for this idea.

**Comment by Sadkeemstar112** [comment]
> Yeah I love this idea. Perks to doing this on showdown is that there won't be any risk of a waiting glitch or similar pixelmon side issues. Only thing I have to say is that this would be a huge effort on the staffs side. I've hosted a few showdown tourneys in one of my servers, and sometimes they can be a real headache, even if there is only 20 people joining. But if it can be done in a organised fashion, I'm all for this idea.

They had a pluggin the last time it almost looked like warzones system so they just have to reset the elo and get the pluggin

**Comment by BadBigHero** [comment]
Im all for this idea.

**Comment by WalkAway7** [comment]
Oh that's great then actually, yeah I'd love to see this around

**Comment by Heartzzlol** [comment]
I agree with this idea, because with the amount of battle glitches in game doing it on showdown would prevent those issues

**Comment by Chummsy** [comment]
I have participated in the old world cup and absolutely loved it! Would be awesome to see such a tourney back on the server ;)
I'm full in with this idea

**Comment by Heartzzlol** [comment]
I love this idea

**Comment by oLimooo** [comment]
I agree with having another world cup. Right now with school about to end at least in Texas, they will be a bunch of people looking to play games during the summer, and having a world cup during summer can affectively boost the server in every way possible.

**Comment by EboyZenks** [comment]
I agree with this 100% it would bring allot more attraction to the server after the reset

**Comment by M1n0j** [comment]
I agree to have one similar to world cup but doing it in showdown defeats the purpose of having it go towards a pixelmon server. Imo if its done it should be in pixelmon, even tho some battle mechanics are different/buggy its what makes pixelmon pixelmon. Also having it on showdown defeats the purpose of grinding on the server for BPs and HAs needed.

**Comment by Sadkeemstar112** [comment]
> 

If u read the thing i was trying to tell that it was going to be a showdown pluggin like some other pixelmon servers have not going to mention them and the rank 1 showdown player on each server gets a place in the tournament "The Showdown system i was thinking it will be a pluggin like warzones system but the elo or rating gets reset after a time and the winners will be given a legendary crate key and a ticket to the world cup qualifiers"

**Comment by Mikirae** [comment]
Unfortunately, the biggest reason we've held off on this is because of the insane amount of Waiting glitches that are currently in the game. It seems like more happen all the time, and unless we can get a plugin to recreate battles (which is something we're looking in to, but I'm not hopeful), then we'd end up with a lot of drama once again every time a battle errors.

**Comment by Mikirae** [comment]
> > Yeah I love this idea. Perks to doing this on showdown is that there won't be any risk of a waiting glitch or similar pixelmon side issues. Only thing I have to say is that this would be a huge effort on the staffs side. I've hosted a few showdown tourneys in one of my servers, and sometimes they can be a real headache, even if there is only 20 people joining. But if it can be done in a organised fashion, I'm all for this idea.
> 
> They had a pluggin the last time it almost looked like warzones system so they just have to reset the elo and get the pluggin

I also don't really know what this means or if you're thinking of something else, we just had a different tournament plugin on the server.

**Comment by Sadkeemstar112** [comment]
> > > Yeah I love this idea. Perks to doing this on showdown is that there won't be any risk of a waiting glitch or similar pixelmon side issues. Only thing I have to say is that this would be a huge effort on the staffs side. I've hosted a few showdown tourneys in one of my servers, and sometimes they can be a real headache, even if there is only 20 people joining. But if it can be done in a organised fashion, I'm all for this idea.
> > 
> > 
> > They had a pluggin the last time it almost looked like warzones system so they just have to reset the elo and get the pluggin
> 
> I also don't really know what this means or if you're thinking of something else, we just had a different tournament plugin on the server.

Yes i know but i was thinking having a qualifiers system like warzone the player with the highest reputation gets a ticket to world cup like the showdown ladder but it resets every week. I played last world cup and it was like the random battle tournament pluggin that happens every 3 hours. And i was thinking on something else :). I think it could work if there are rules about the waiting glitches really and tbh i have not gotten waiting glitch in a long time so i see that it has become better. Kind regards Keem

**Comment by jantjewieger** [comment]
> I agree to have one similar to world cup but doing it in showdown defeats the purpose of having it go towards a pixelmon server. Imo if its done it should be in pixelmon, even tho some battle mechanics are different/buggy its what makes pixelmon pixelmon. Also having it on showdown defeats the purpose of grinding on the server for BPs and HAs needed.

This is the biggest issue with hosting it on showdown. Kinda defeats the purpose of playing on smash if its hosted on showdown. I see that waiting glitches cause a big issue but imo it should still remain on smashMC

**Comment by oLimooo** [comment]
I have a suggestion for world cup. So far what I am reading is players would like the tourney to be in-game because of the grind part that goes into a tournament. I fully agree with this, however some battles can get a bunch a pixelmon issues such as waiting glitches and it takes forever if it’s a stall team. The way to make this fair as possible is, staff opens a new discord channel to let players send their in-game teams (with a screenshot) or can directly dm a staff member. After staff confirms their teams, they are put into a bracket to battle on showdown but with their in game team. I believe this can be a way to balance both sides from in-game to showdown.

**Comment by Mikirae** [comment]
> I have a suggestion for world cup. So far what I am reading is players would like the tourney to be in-game because of the grind part that goes into a tournament. I fully agree with this, however some battles can get a bunch a pixelmon issues such as waiting glitches and it takes forever if it’s a stall team. The way to make this fair as possible is, staff opens a new discord channel to let players send their in-game teams (with a screenshot) or can directly dm a staff member. After staff confirms their teams, they are put into a bracket to battle on showdown but with their in game team. I believe this can be a way to balance both sides from in-game to showdown.

Very confused because I swear I replied to this already but I don't see it here lol.
Once again, not hosting it on Showdown because it ruins the feel of it being Pixelmon. It's also rather easy to just change up the teams, and with the amount of people that are joining, it's not really feasible to have a staff member having them stream their game every time they battle or something. It's something that had been thought of in the past, and we're just unfortunately not interested in hosting it on Showdown.
Only way I can see it happening is with either the help of a plugin recreating battles, or waiting glitches not being so prevalent anymore.

**Comment by Sadkeemstar112** [comment]
> > I have a suggestion for world cup. So far what I am reading is players would like the tourney to be in-game because of the grind part that goes into a tournament. I fully agree with this, however some battles can get a bunch a pixelmon issues such as waiting glitches and it takes forever if it’s a stall team. The way to make this fair as possible is, staff opens a new discord channel to let players send their in-game teams (with a screenshot) or can directly dm a staff member. After staff confirms their teams, they are put into a bracket to battle on showdown but with their in game team. I believe this can be a way to balance both sides from in-game to showdown.
> 
> Very confused because I swear I replied to this already but I don't see it here lol. Once again, not hosting it on Showdown because it ruins the feel of it being Pixelmon. It's also rather easy to just change up the teams, and with the amount of people that are joining, it's not really feasible to have a staff member having them stream their game every time they battle or something. It's something that had been thought of in the past, and we're just unfortunately not interested in hosting it on Showdown. Only way I can see it happening is with either the help of a plugin recreating battles, or waiting glitches not being so prevalent anymore.

Uhm i was thinking of a showdown

**Comment by Mikirae** [comment]
We won't be doing it on Showdown because once again, it detracts from the
entire Pixelmon experience. Going to an external site where people can
potentially edit their teams without our knowledge also just doesn't seem
like the best option here.
Unfortunately, until we get something that can recreate battles, or until
waiting glitches are fixed/insanely less common than they are now, a
large-scale tournament like this won't be feasible.
