### ISSUE TITLE
swapping my rank to another server

### ISSUE THREAD

**Issue by devitexx** [SmashMC-Development/Suggestions#1005]
swap rank from kyurem to rayquaza

Kyurem/rayquaza
i would like for my rank to be moved from kyurem to rayquaza since the server died, i dont want any of the purchase bonuses just the commands and if this would be possiable i would be super happy

**Comment by WalkAway7** [comment]
This is an issue for a ticket in the discord. Go to #bot-spam and type -ticket open (reason).

**Comment by Archie4690** [comment]
Hey, like said above this would have been better suited for a support ticket, although with that said, and to save you a ticket, we do not offer rank server swaps. If you want to get a rank on Rayquaza you would need to buy another rank over on that server. WIth that being said I will close up this suggestion.
