### ISSUE TITLE
/wondertrade

### ISSUE THREAD

**Issue by llnama** [SmashMC-Development/Suggestions#1008]
**Describe the suggestion**
Add more pokemon to wondertrade's bank. This way there is a lower chance for people to get what someone just wondertraded.
Let's say you make it so there's 25 pokemon in the wt bank, there would be 4% chance for a player to get one of those mons.
This way it is more luck based to get some legendary that someone put into WT.

**Which servers does this apply to?**
All

**Comment by Mikirae** [comment]
Upped it from 50 to 100. Thank you for your suggestion :)
