### ISSUE TITLE
PC boxes

### ISSUE THREAD

**Issue by SimaoAntunes26** [SmashMC-Development/Suggestions#1021]
Hi, I know that you are having a lot of work now with the reset but I was wondering if you could add some extra boxes on the PC. I played on smash for a long time and I'm more like a Pokemon collector (basically I want to have all the pokemon and their variants) and considering just the dex there are almost 900 mons, divided by 30 (slots per box) and 30 boxes are full. Could you increase the number for like 75 (I say that cause I think it's a good number) I would like to know what you think about that.
Once again, sry to bother I know that you have a lot to do now. 
Lovely

**Comment by BrunchBee** [comment]
I would love this

**Comment by Dxhcky** [comment]
I believe this is a pixelmon mod side suggestion. Not sure if it possible for smash to do this

**Comment by SimaoAntunes26** [comment]
> I believe this is a pixelmon mod side suggestion. Not sure if it possible for smash to do this

I don't think so I don't remember if 50 boxes it's the limit in singleplayer mode but I know that are other servers that have more boxes so I thought it would be just an easy change of numbers from 50 to 75. I don't want the staff working on this if it's harder than that cuz they have better things to do.
Lovely <3

**Comment by BrunchBee** [comment]
> I believe this is a pixelmon mod side suggestion. Not sure if it possible for smash to do this

"The number of boxes can be changed in config, up to a maximum of 256 boxes (7,686 Pokémon including the player's party)."

Straight from the wiki :D

**Comment by Dxhcky** [comment]
> 

If it is possible, which I have just been told it is, then im sure management will take a look at this when they have the time

**Comment by Mikirae** [comment]
This is already 100 after reset :))))
