### ISSUE TITLE
Market

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#1024]
**Describe the suggestion**
Can there be a remodel of /warp market

**Which servers does this apply to?**
All

**Additional context**
I don’t really like how market is set up, last reset the market was 10 times better probably even more. It just looks like it was constructed within 10 mins (no disrespect to the builders). I just believe there can more effort into making a good looking market.

**Comment by Mikirae** [comment]
Markets are constructed in order to properly fit into spawn. Any huge remodel of it would require redoing a decent portion of the spawn. Besides, I personally think they look fine
