### ISSUE TITLE
STS

### ISSUE THREAD

**Issue by JohannErasure** [SmashMC-Development/Suggestions#1026]
**Describe the suggestion**
Add STS back to the game so that we can sell our high iv mons that are just sitting in the pc

**Which servers does this apply to?**
all servers

**Additional context**

Every server has seen economic struggles. this is because the only actual way to generate money is sit in boss tower and sell whatever u have. this is not even a good way of generating money, as most things don't sell or most things don't sell for much. econ and game quality would be so much better if sts was a thing because people would have money to buy things with.

**Comment by Mikirae** [comment]
Unfortunately STS and GTS have not yet been updated, so this is not possible as of now. When they are updated, they will be in the server :)
