### ISSUE TITLE
Grass in ultra space

### ISSUE THREAD

**Issue by xXbumisXx** [SmashMC-Development/Suggestions#1028]
Describe the suggestion
Make ultra space have spreadable grass

Which servers does this apply to?
All

Additional context
Grass doesn't spread, can interfere with player plan

**Comment by IsThief** [comment]
Which server are you on? Ultra space doesn't work at all on ray

**Comment by xXbumisXx** [comment]
zekrom

**Comment by Mikirae** [comment]
This is a bug, not a suggestion :) I did some fixes today that might resolve this, but I'm not entirely sure if ultra space was even impacted by what I did
