### ISSUE TITLE
Economy Idea

### ISSUE THREAD

**Issue by SimaoAntunes26** [SmashMC-Development/Suggestions#1031]
So, honestly I don't have a pretty defined idea about this but it's the beginning of the server and I can understand that it's pretty hard to make money, basically the only ways that I found were fighting trainer (that give like 300 coins) and voting (only once a day) so I was thinking about making some kind of easy/medium/hard daily quests, I don't know what the quests could be but making money now it's though. Besides some items should have their prices changed cuz for example I found a relic band, it usually sell for 100 000 coins in single player, I know that's a lot for a item so useless but reducing the price to 1000 is ridiculous.

**Comment by Mikirae** [comment]
Prices on servers are far different than prices on single player. The ways that you get items are different, and there is no need to maintain a balanced economy on singleplayer. The prices of items on servers will always be different.
That being said, we are looking to get Daily Quests implemented once again, but they are not yet updated. As soon as they're updated, they'll be in :)
