### ISSUE TITLE
Warzone glitch when battling

### ISSUE THREAD

**Issue by Octo6155** [SmashMC-Development/Suggestions#1032]
**When battling in warzone the battle may randomly glitch the player with higher rep will loose a bit of rep the Player with the least rep will gain some rep.**
so I notice this happens more with some poke than others for example ferrothorn will break the battle as it says the opposing pokemon hit the ferro multiple times making it die and crash the battle although this glitch has happened with tyranitar and other pokemon just completely randomly.

**All servers**
All servers

**Comment by Mikirae** [comment]
This SHOULD be fixed after the servers restart tonight. Now, when a battle errors, you won't lose reputation :)
