### ISSUE TITLE
Black market

### ISSUE THREAD

**Issue by jonathanb434** [SmashMC-Development/Suggestions#1035]
Back in charizard pre reset, the black market had z crystals red and blue orbs and much more rare items, then in the transition to groudon all the stuff was worthless. i would love to see the old black market

**Comment by Mikirae** [comment]
Pretty sure we removed these to create more of an economy amongst the players rather than simply purchasing it from the shop. Thank you for the suggestion, but I don't believe we have any plans on implementing these back into the market currently :(
