### ISSUE TITLE
Smash kit pokeballs

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Suggestions#1036]
**Describe the suggestion**
At the moment, smash ranks receive some dusk balls and jet balls from the kit. However, I believe elite receives ultra balls from theirs, and jet balls are far worse than ultra balls are, so this doesn't make sense. Ultra balls are also hard to get with the apricorn trees being slow to produce apricorns and with how hard it is to find a large quantity of platinum. My suggestion is to replace the jet balls in the smash kit with ultra balls, as jet balls are just kind of useless in comparison.  

**Which servers does this apply to?**
All

**Comment by Superfire96** [comment]
Kits were reviewed and updated!
