### ISSUE TITLE
No way to access creeper/wither skeleton skull

### ISSUE THREAD

**Issue by OverDr1v3** [SmashMC-Development/Suggestions#1039]
**Describe the suggestion**
Within the Pixelmon mod, there is no way to access the in game items Creeper head and Wither skeleton skull, as they can only be obtained from the mobs themselves. While this is not a game breaking issue, the most practical application of these items goes largely ignored: Banners. These items can be crafted into specific banner charge patterns which can then be imprinted onto banners for decorative purposes. As someone who really enjoys creating banners for myself and others, I was thoroughly disappointed that these items were made inaccessible. Whether they are sold in the shop, vote crate rewards, or quest rewards, I can see no possible downside from adding these items, as they can only enrich the experience.

**Which servers does this apply to?**
I'd like this to be implemented on all servers

**Additional context**
I have brought this issue up with Archie during the community meeting as well as other moderators/admins, and they seemed to agree that there was no reason to not implement this change, and that I should reach out on Github. I understand that it is not as simple as just "adding them", but I would really like to see these items added in an upcoming update/patch. Thank you for all of your hard work on the server thus far, and I look forward to future changes.
Attached are some screenshots of the banners I've made :)

![2022-06-20_12 16 04](https://user-images.githubusercontent.com/107460199/174643531-86dba80e-0992-47fc-a90a-39ea96b1fbe5.png)
![2022-06-20_12 16 08](https://user-images.githubusercontent.com/107460199/174643537-00edf3e2-533c-4ce8-9419-55897c36030a.png)

**Comment by Mikirae** [comment]
Nice banners :D Actually had no idea that heads had anything to do with banners lol. Never really made them. We'll look into getting them added here soon :)

**Comment by Superfire96** [comment]
Added some skulls to the /shop and shopkeepers
