### ISSUE TITLE
skin layers not working

### ISSUE THREAD

**Issue by Lupped** [SmashMC-Development/Suggestions#1040]
layers on minecraft skins do not work properly at the moment (besides in the hub, which i find weird)

I believe this is on all pixelmon servers

**Additional context**
![2022-06-21_20 56 12](https://user-images.githubusercontent.com/107329902/174920774-7e4a87eb-2455-4b2c-8d1a-7f16d75fd9c0.png)
^skin in a server
![2022-06-21_20 57 18](https://user-images.githubusercontent.com/107329902/174920835-91b5c67e-46eb-48cd-94e7-aa614e256d17.png)
^skin in hub

as you can see here the outer layer of skins does not work in the servers, this was not an issue pre server wipe, so idk if something was accidentally turned off but it would appear to not be working

this can cause skins to look very weird which just takes away from the experience

**Comment by WalkAway7** [comment]
Yeah same happens on my skin as well haha

**Comment by Mikirae** [comment]
I hear it targets big weebs only which is why it doesn't work for you two. But then I also heard that it's currently a Pixelmon bug  that I'm reporting right now.
