### ISSUE TITLE
abuse of admin

### ISSUE THREAD

**Issue by Chudspawn** [SmashMC-Development/Suggestions#1043]
**Describe the suggestion**

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.
fe4Rglint tping me and greasycop away from a town we were building a base in.

**Comment by M1n0j** [comment]
Hey @Chudspawn, If you are trying to report someone please make a ticket on our discord https://discord.gg/zgUYhree
Github is for suggestions and bugs only not reports!

**Comment by Mikirae** [comment]
No information provided.
