### ISSUE TITLE
Increase number of pokemon pairs to breed

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Suggestions#1054]
I have been receiving suggestions from other players that the breeding cap for pokemon pairs should be increased from 10 to 15-20 pairs, a total of 30-40 pokemon.

If lag is a factor in denying this, then maybe increase it to 15 pairs at least?

This should help breeders, breed more pokemon of different varieties, this could also stimulate the economy so that breeding could be a good source of income.

Warzone has A LOT of pokemon spawning at once, and in different areas at the same time depending if there are a lot of people on, so why not increase the breeding cap? there are a lot of pokemon in one area, sometimes in completely different areas/biomes/worlds.

If lag is a factor, then get this, wild pokemon insantly despawn once you leave far from the area or tp to another location like spawn or the nether.

If you are worried about the economy, well recently the economy is not that great since we dont have GTS yet, so this can potentially help in increase the economy

**Comment by Mikirae** [comment]
It's not about lag, it's about the economy. We've talked about increasing the breeding cap in the past, and have decided no, for the betterment of the economy. You should see GTS making its return soon, so be on the lookout for that :)
