### ISSUE TITLE
Eggs not appearing after being offline for hours

### ISSUE THREAD

**Issue by HarshilM67** [SmashMC-Development/Suggestions#1055]
**Describe the suggestion**
Normally when you go offline for a period of time eggs normally, however recently I have not been receiving eggs after long durations of time while being offline.

**Which servers does this apply to?**
All servers

**Additional context**
N/A

**Comment by Mikirae** [comment]
This sounds like Pixelmon either changed something, or it's a Pixelmon bug. Unfortunately, not something on our end :(
