### ISSUE TITLE
Woolo Drops

### ISSUE THREAD

**Issue by b00mhammer** [SmashMC-Development/Suggestions#1056]
**Wooloo drops are extremely broken** and I suggest they should be fixed. I was told to make a github which I can agree on but it might not be the server's problem, might just be the mod itself.
This is applied for all servers and here is what the drops look lik
![idk](https://user-images.githubusercontent.com/108588805/177011358-558a34b4-e16c-4a00-a92f-b17aaac8c5ae.png)

**Comment by Mikirae** [comment]
Should be fixed as of today. Thank you :D
