### ISSUE TITLE
Sableye's Mega Stone

### ISSUE THREAD

**Issue by Virulencia1** [SmashMC-Development/Suggestions#1057]
Ive noticed that Sableye's mega stone wasn't in the megastone crate key. This is very annoying considering I have bpha sableye but I can't even use it's mega. Please add it back to the Megastone Crate Key. Please and Thank You.

**Which servers does this apply to?**
All

**Comment by Archie4690** [comment]
Hey @Virulencia1, the Megastone is now in the crate! Thank for for making a suggestion!
