### ISSUE TITLE
Cant buy nothing on the pokemart 

### ISSUE THREAD

**Issue by Atenamiv** [SmashMC-Development/Suggestions#1064]
**Describe the suggestion**
I am playing in the rayquaza server and when I try to buy something in the pokemart it is just a blank screen

![2022-07-10_12 49 17](https://user-images.githubusercontent.com/109036596/178154894-79e6fe07-2939-464f-b3a1-9311a4786099.png)
Which servers does this apply to?
Every server in MC.POKESMASH.CO

**Comment by jantjewieger** [comment]
This has now been solved!
