### ISSUE TITLE
synchronize should be enabled tbh

### ISSUE THREAD

**Issue by twizzy0** [SmashMC-Development/Suggestions#1073]
It’ll be cool to be able to change the legendary natures that I catch, or really any pokemon, it’ll make it less of a struggle to catch good legends, I could get a amazing zacian but get a bad nature, it’ll rlly just make the server a lil better tbh, take it into consideration.

**Comment by Mikirae** [comment]
It’s not disabled. We don’t even have an option for that that I’m aware of.
If it’s not working, I’d have to assume it’s a Pixelmon bug :(
