### ISSUE TITLE
CAP Pokemon

### ISSUE THREAD

**Issue by TommyT1TWhiler** [SmashMC-Development/Suggestions#1074]
**Describe the suggestion**

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by TommyT1TWhiler** [comment]
I know there is a very small chance but it don't hurt to ask. can we get CAP Pokemon into Smash.MC mainly this beast Cawmodore

**Comment by Mikirae** [comment]
We can create our own Pokemon, but we wouldn't take the mons from Showdown and move them to here. Would have to get permission and a model and everything :(
