### ISSUE TITLE
Add /Fly to the buycraft

### ISSUE THREAD

**Issue by ItsCaeden** [SmashMC-Development/Suggestions#1077]
**Describe the suggestion**

I believe that the server should add access to /fly onto the buycraft website, I believe that this should be done for around £5-£10 and would be a good idea for the server.

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

All servers.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

N/A

**Comment by Mikirae** [comment]
We believe that it is a good incentive for buying a rank, so it will be staying in there for the time being.
Thank you for the suggestion, though!
