### ISSUE TITLE
breeding improvement

### ISSUE THREAD

**Issue by JJWarner777** [SmashMC-Development/Suggestions#1089]
add an idem that will auto collect eggs form ranch blocks and will hatch them over time or mage the one that hatches the egg called the egg incubator and the one that gets the eggs the ranch worker.
the only other thing that I would want is that the ranch worker would keep the chuck loaded so that if I'm at mart my breeder is still working also the ranch worker would put the egg in the incubator if there is one in range.  
also if there is no ranch worker the ranch block will stay above ground until the egg is token out

**Comment by jantjewieger** [comment]
I do not agree with this at all lol. If you were to have an item that would auto collect items over time you would be automatically farming the breeding /skill. Altho it's not working 100% properly rn, once it is it would just be automatic farming. Which is not allowed and just not something that should be on the server imo.

**Comment by Mikirae** [comment]
Yes, I agree that unfortunately this would make things way too easy and remove all sense of manual labor in the breeding process really.
Aside from that, it's not possible at all with how they're changing breeding unfortunately.
