### ISSUE TITLE
Add non legendary ability change papers to the legendary crates.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#109]
**Describe the suggestion**
Add non legendary ability change papers to the legendary crates. Hidden ability is an available option with these papers. 

**Which servers does this apply to?**
Network.

**Additional context**
Upon usage of this paper, the pokemon that it was used on becomes unbreedable.

**Comment by Mikirae** [comment]
I do believe we considered this previously and decided that it would be rather overpowered and as such declined it.
