### ISSUE TITLE
Move tutor

### ISSUE THREAD

**Issue by samuelrocks** [SmashMC-Development/Suggestions#1091]
Move tutors must either be added into /warp mart with a fee or completely free.

Finding moves like knock-off, which is super important for many teams, is challenging to find out in the wild with the low spawn rates and the tendency for the move tutors to despawn.

I assume this was also an issue in the past, however,/buymoves command doesn't seem to be a command anymore, and I would highly suggest this be added to the server to keep the format more competitive.

If this is not done, it will make it so much harder for newer players to catch up with veterans in warzone.

**Comment by Mikirae** [comment]
Move tutors would be added, except for the fact that they literally don't work with Pixelmon right now. They let you click the move and then they just exit the UI.
Once they're fixed, they'll be added :)

**Comment by samuelrocks** [comment]
apparently JackHelsby00 said that he just used a move tutor that spawn in the wild to teach his dragonite dual wingbeat. is it an npc issue, if its only an issue that comes up when you spawn in an npc manually. 

at least bump up the spawnrates for natural move tutors if possible.

**Comment by jantjewieger** [comment]
Its that sometimes they work and sometimes they don't. Sometimes it says a mon cannot learn something when the wiki says it should be able to learn it or that it says it can learn it but u can physically not click on the move to teach it to your mon. If you open a ticket a SrMod can put the move on your mon, provided its a move learnt by a move or transfer tutor
