### ISSUE TITLE
Wierd Volcanion

### ISSUE THREAD

**Issue by b00mhammer** [SmashMC-Development/Suggestions#1093]
Got a Wierd Volcanion after I opened a lucky block, 
![image_2022-08-12_155303104](https://user-images.githubusercontent.com/108588805/184367834-aa53647e-e3be-424e-8195-9763a0e2b2c2.png)
![image](https://user-images.githubusercontent.com/108588805/184367879-08922fd1-7eaa-45e7-b742-1c5bd71a183c.png)

**Comment by jantjewieger** [comment]
Issue was already resolved by Miki. If you could open a ticket we can get this sorted (If you haven't already). Closing this up
