### ISSUE TITLE
Ban the use of dusk tools in warzone

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#11]
**Describe the suggestion**
Remove dusk stone tools in warzone (all type of tools)

**Which servers does this apply to?**
all

**Additional context**
Dusk stone tools can make a player invisible, I been getting a ton of players reporting people abusing the tool to avoid the risk of warzone.

**Comment by HackuJacku** [comment]
@oLimooo - with the most recent Warzone update, this should now be fixed as it was a bug. Please can you confirm?

**Comment by oLimooo** [comment]
I can confirm! It works!

**Comment by HackuJacku** [comment]
Done.
