### ISSUE TITLE
Kits update

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Suggestions#1104]
**Describe the suggestion**
Before the 9.0.7 update some of the kits, I believe the Legend and Smash kit, gave hourglasses (silver and gold) for each /kit smash and /kit legend. However, with the most recent update all hourglasses have been removed so maybe update the kits with new hourglasses. The old golden hourglasses is similar to 2 new silver hourglasses. and the old silver hourglass is similar to the new Copper Hourglass. Maybe add those to the kits

**Which servers does this apply to?**
All

**Additional context**
N/A

**Comment by Mikirae** [comment]
Are you positive they were in there? I'm in the config for it right now and I don't see that they're in there (they should show with the old IDs in the config)

**Comment by jantjewieger** [comment]
Maybe Super has already removed em. But I know for a fact that they were in there (as i got some from them having Smash myself)

**Comment by Archie4690** [comment]
I never saw this GitHub before I fixed it, but Legend Kit now gets 1 silver hourglass and Smash should get 2 silver hourglasses. Ticket clsoed
