### ISSUE TITLE
Primal Groudon and Kyogre in Warzone

### ISSUE THREAD

**Issue by Twillight0420** [SmashMC-Development/Suggestions#1108]
There is no justification to not restrict the use of the two Primal mons in warzone. They are simply AG, same goes for other AG mons but they are already disabled. (Smeargle, Zacian and others). I suggest removing them from the current warzone format since it's really a weird move.

**Comment by Mikirae** [comment]
They've never been AG at any point in time to my knowledge. The only AG mons as of Gen 8 that I have seen are Mega Rayquaza and Zacian as they're simply beyond broken.
