### ISSUE TITLE
Textures for fused calyrex

### ISSUE THREAD

**Issue by HelsbyJ** [SmashMC-Development/Suggestions#1109]
When fusing calyrex and spectrier/glastrier should keep the texture for both pokemon, rather than fusing 2 galaxies together and only the calyrex having a texture and the spectrier/glastrier looking normal rather than textured as well.

**Comment by Mikirae** [comment]
I double checked our files, and we have textures for it, Pixelmon just doesn't accept it for some reason. Seems like a bug on their end, unfortunately.
