### ISSUE TITLE
i am banned from discord from a year ago and im not sure why 

### ISSUE THREAD

**Issue by megaaaaa453** [SmashMC-Development/Suggestions#1158]
idk where to put this so my suggestion is unban mega#0245 if u dm what i did i can try and appeal and i also got hacked and lost the megaaaaa account with multiple ranks on servers if i could get those back it would be cool

**Comment by Johnnyrickk** [comment]
> idk where to put this so my suggestion is unban mega#0245 if u dm what i did i can try and appeal and i also got hacked and lost the megaaaaa account with multiple ranks on servers if i could get those back it would be cool

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost account ,message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by Garettbillk** [comment]
> idk where to put this so my suggestion is unban mega#0245 if u dm what i did i can try and appeal and i also got hacked and lost the megaaaaa account with multiple ranks on servers if i could get those back it would be cool

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost account ,message him on telegram his telegram username is https://t.me/Blackhathacker11

**Comment by Rahman2326** [comment]
> idk where to put this so my suggestion is unban mega#0245 if u dm what i did i can try and appeal and i also got hacked and lost the megaaaaa account with multiple ranks on servers if i could get those back it would be cool

My Experience:
💗. Recovering Hacked WordPress Website
💗. Full Vulnerability Scan and WordPress website malware removal
💗. Vulnerability Assessment
💗. Antispam protection
💗. Analysis of database servers
💗. Restore a hacked website
💗. Ethical Hacking(White Hat Hacker)
💗. Hacked account recovery
💗. Password recovery
💗. Decode encrypted files
💗. Vulnerability Testing
💗....my WhatsApp number +8801314956025
