### ISSUE TITLE
Discord channels

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#116]
**Describe the suggestion**
Buy/sell for each individual Minecraft server in discord

**Which servers does this apply to?**
all

**Comment by Rasgnarok** [comment]
A Discord bot could be automating all of this with a market channel per server. Pokemon, items, etc could be saved to a database and shown-off in a market listing feed, through a Discord channel.

**Comment by Rasgnarok** [comment]
Bumped to https://github.com/SmashMC-Development/Suggestions/issues/456.
