### ISSUE TITLE
Add legendary held items to a new crate.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#122]
**Describe the suggestion**
Add items that are held by legendaries upon capture available in an all new crate. 

**Which servers does this apply to?**
Network.

**Additional context**
Pokemon caught in the warzone or via Vote Party don't hold their usual held items. By adding this crate, these items are available easier.

**Comment by HackuJacku** [comment]
We sadly won't be adding these to the legendary crate due to it being a paid item. However, we'll potentially add it to the `/warp mart` or some other form of method.
