### ISSUE TITLE
Add gym badges to the shop so players can make their unofficials gyms

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#13]
**Describe the suggestion**
The desire for players to have their gyms is really high, if we can manage to add gym badges to the shop so players can rename the item could make a very interesting underground gym system. 

**Which servers does this apply to?**
Everyone (maybe not Charizard, Kyogre and Rayquaza)

**Comment by Mikirae** [comment]
I don't think that this is necessarily a good idea, as badges should mainly be for those who have official gyms. Giving them out so people can make unofficial ones defeats the purpose of our gyms and gets rid of potential gym leaders.

**Comment by Mikirae** [comment]
Ah okay. That makes more sense :)
