### ISSUE TITLE
Warzone context

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#138]
**Describe the suggestion**
create add more warzone content

**Which servers does this apply to?**
all

**Additional context**
the point is the warzone gets boring example on palkia there is are only some players which do everything and no one think its wort to come in warzone I think new things like higher mega chance, higher ha Pokémon chance ,loot crates (master balls, crates, Pokémon pvp items)

**Comment by HackuJacku** [comment]
Such as please?

**Comment by HackuJacku** [comment]
This will be addressed in the Warzone overhaul but we'd love to hear more suggestions in the meantime. Added this to the Warzone master ticket.

**Comment by HackuJacku** [comment]
Implemented on the upcoming reset!
