### ISSUE TITLE
Random dex entry paper

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#142]
**Describe the suggestion**
create make an random dex entry paper ( a paper which give you one random dex entry)

**Which servers does this apply to?**
all

**Comment by HackuJacku** [comment]
What would the advantage over a random Pokémon paper be please?

**Comment by HackuJacku** [comment]
We sadly aren't going to add this because we already have random Pokémon papers, these are pretty common through `/skills` and other methods. Although this could randomly complete one of the remaining PokéDex entries, Warzone makes it easier to complete your PokéDex as well.
