### ISSUE TITLE
Fix auras

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#143]
**Describe the suggestion**
fix the auras cause if u put a legend aura on a Pokémon then u put it in your pc then take it out it disappears so aura keys are a scam basically

**Which servers does this apply to?**
all

**Comment by HackuJacku** [comment]
How are you removing the aura? If you're using the `/aura remove` command, it stats clearly that you will not get the aura back.

**Comment by HackuJacku** [comment]
Is there is an issue with auras, please create a report on our bugs-and-issues repository.
