### ISSUE TITLE
/vote count on tab

### ISSUE THREAD

**Issue by CaretsPuppy** [SmashMC-Development/Suggestions#145]
**Describe the suggestion**
Bring back vote count on tab

**Which servers does this apply to?**
All

**Additional context**
Easier to check, faster more efficient

**Comment by HackuJacku** [comment]
We won't be adding this as we wanted to remove placeholders (updating values) off the tablist and move them into something nicer - the VoteParty required voted are in both `/menu` and on the overlay tab.
