### ISSUE TITLE
Dex after server reset

### ISSUE THREAD

**Issue by CaretsPuppy** [SmashMC-Development/Suggestions#149]
**Describe the suggestion**
 make it not needed to be OT for when dexing for legendairy pokes, but still make it necessary for non legends

**Which servers does this apply to?**
All

**Additional context**
"since the resets, u can only dex if ur OT of the poke, which gives a nice challenge for the normal pokes, good but doable grind. but for legends its like nearly impossible"

**Comment by HackuJacku** [comment]
This is sadly something will not be doing
