### ISSUE TITLE
Update Wc

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#155]
**Describe the suggestion**
add a update of all banned Pokémon to the wc

**Which servers does this apply to?**
Wc

**Comment by HackuJacku** [comment]
Such as please?

**Comment by HackuJacku** [comment]
As we're approaching the finals, we won't be doing this. When we've posted about the World Cup, we've always linked back to the 'main' post which had a list of all banned Pokémon. The only additional Pokémon banned onto of any non-Generation 8 National Dex Pokémon is Kommo-o.
