### ISSUE TITLE
display a msg in chat when fighting someone in wz

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Suggestions#16]
when u engage someone in battle, could there be a msg along the likes of _you are now fighting playerX in warzone_ (which is only visible for the 2 players that are in battle). it would make tickets that deal with warzone crashes a whole lot simpler, since it kinda hard to proof sometimes who exactly it was that stole ur poke after u crashed midbattle

**Comment by Mikirae** [comment]
I think this is something that we can definitely add when we rewrite Warzone :)

**Comment by HackuJacku** [comment]
We'll be adding a couple of different methods such as this in Warzone 2.0 for both staff and players.
