### ISSUE TITLE
Warzone change

### ISSUE THREAD

**Issue by CaretsPuppy** [SmashMC-Development/Suggestions#171]
**Describe the suggestion**
Make Rayquaza's warzone the same as Charizard

**Which servers does this apply to?**
Rayquaza

**Additional context**
Ray wz too small in comparison

**Comment by HackuJacku** [comment]
Warzone is getting an over-haul. We won't be coping the Charizard Warzone because it causes a lot of issues currently - these aren't seen by the other servers' players.
