### ISSUE TITLE
Additional thing added to Ticket bot

### ISSUE THREAD

**Issue by Sparklix** [SmashMC-Development/Suggestions#18]
**Describe the suggestion**
I’ve been thinking a lot about the ticket system lately, and what tends to be a problem is that tickets drag on too long because they don’t actively look at their discord.

I had an idea but I don’t know practically if it is possible. What if we could make a ticket command like the following:
“-ticket notify (player) (server)”

This command would trigger a personal message on the server for them (just like the daily rewards) saying  “you’ve got a answer to your ticket click here to dismiss notification.”  And this message would come for example each 30 seconds or 1 minute to remember them they’ve gotten a reply to their ticket.

This would make players who mainly play without discord look at the ticket faster instead of not thinking about it when they’re online.
Idk if this all would be possible though but yeah thought I’d suggest my brain flow with all of you

**Which servers does this apply to?**
All servers

**Comment by Rasgnarok** [comment]
Love this idea. Tickets in general need to be overhauled. Bumping to master ticket.
