### ISSUE TITLE
Add a /warp leaderboards.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#180]
**Describe the suggestion**
Add a /warp leaderboards that show you the top player in all the skills, tournament wins etc. 

**Which servers does this apply to?**
Network.

**Additional context**

**Comment by HackuJacku** [comment]
As it currently is, `/skill` has a leaderboard in the menu UI. Warzone will be getting this down the line and hopefully hunts too - these are all in the works.
