### ISSUE TITLE
Warzone timer

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#182]
**Describe the suggestion**
Rework the timer when fighting 'throw' teams

**Which servers does this apply to?**
All

**Additional context**
when fighting someone in warzone, the 45 second timer is great against competitive battles. But when a random person brings a team of 6 furfrous and keeps the battle in waiting until the last second should have some punishment. Anyone can say they're thinking for that long but for real what are you thinking when you choose quick attack 6 times in a row on 6 pokemon while fighting a xerneas. If the battle has already been relived several times with the same person losing over and over again with the same low team there should be a way to understand that the person who is winning can clearly win and thus the person who is waiting for the timer to run out should face some sort of punishment. Makes good players lose a lot of time

**Comment by HackuJacku** [comment]
Added to the warzone master ticket. This will be addressed in the upcoming Warzone overhaul.
