### ISSUE TITLE
Rework the ./vote way.

### ISSUE THREAD

**Issue by Daddyricardo** [SmashMC-Development/Suggestions#186]
**Describe the suggestion**

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**

**Comment by HackuJacku** [comment]
What does this mean please?

**Comment by HackuJacku** [comment]
Closing as Ricardo isn't the original author - moved from Discord. If this is still a valid suggestion, please create a new request.
