### ISSUE TITLE
Wc

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#187]
**Describe the suggestion**
ban mega beedril from the wc its broken

**Which servers does this apply to?**
all

**Comment by HackuJacku** [comment]
Will be discussed in the Warzone overhaul - this does not mean that it will be banned though. In the meantime, I'd like people's thoughts please.

**Comment by HackuJacku** [comment]
As we are approaching the finals, we won't be doing this. It's not broken in terms of gameplay so anyone can use it if they won't - I don't believe anyone is though.
