### ISSUE TITLE
Let people apply for gymleader on all pixelmon servers

### ISSUE THREAD

**Issue by Sparklix** [SmashMC-Development/Suggestions#19]
**Describe the suggestion**
Open up gym applications for all servers

**Which servers does this apply to?**
All Pixelmon servers

**Additional context**
As far as I'm aware, 2 servers already started making their own gyms (Giratina & Darkrai) since there is no possibility to apply for a gymleader position on their server. This way we can also see how the much interest there is for gyms on that server.

**Comment by Mikirae** [comment]
@Rasgnarok We were looking into this right now, correct?

**Comment by Rasgnarok** [comment]
Applications are actually already all open as of two Fridays ago. Closing!
