### ISSUE TITLE
Bring back /showdown.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#192]
**Describe the suggestion**
Reintroduce the /showdown command.

**Which servers does this apply to?**
Network.

**Comment by HackuJacku** [comment]
We will be doing this in the future but the current plugin available is no longer supported and I believe it does not work - there are issues with it anyways. Once the plugin I plan to replace this with is available, we'll add it but until then I'll keep this open.

**Comment by HackuJacku** [comment]
We sadly won't be adding this due to the Warzone leaderboard addition
