### ISSUE TITLE
Higher the spawnrate of mega bosses

### ISSUE THREAD

**Issue by Daddyricardo** [SmashMC-Development/Suggestions#198]
**Describe the suggestion**

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**

**Comment by HackuJacku** [comment]
We won't be increasing the mega-boss rates due to the bosstower being accessible. This is for economical and balancing reasons - the bosstower will be nerfed in the future as it is.
