### ISSUE TITLE
Make a warning channel 

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#20]
I would like to see a warning channel of staff members sending a player a warning. I understand notes are a thing, but sometimes players say they haven't been warned. Also, notes are based only on our words (staff), with no proof, and imo seems a bit unbalanced. Like a staff member can add a note to a certain user without warning them or forget to warn them. Which is a huge issue as they player will not be aware they are doing wrong.  With this channel it would show the player being warned, having proof of them getting a warning, and not having a excuses of not being warned ('I didn't get a warning'). Basically the same concept of punishment reports but instead with warnings. Like !warn (user), warned, (reason), (sever), proof (sending a picture of a mail being send) 

**Which servers does this apply to?**
Discord

**Additional context**
This might have a lot of typing to do for the helpers or mods, but imo it makes the warning system much more efficient. When warning we only depend on notes with no proof.

**Comment by Rasgnarok** [comment]
I actually think it would be best if noting a player automatically sends them a warning mail. Or perhaps, prompt the staff to click in chat, and the warn would be sent. I wouldn't make another channel for it - and just have the bot catch the warnings as well as the noting automatically.

**Comment by Rasgnarok** [comment]
Bumped it to master ticket, as we need an automatic feed of these moderation actions... through a better Discord bot.
