### ISSUE TITLE
zygarde cells and cubes

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#202]
**Describe the suggestion**
Look into the zygarde cube. What I mean is that for some reason when the cube collects cores, it does not allow the OT to teach the zugarde any moves. Also, since the cores and cells only spawn in new chunks, maybe put some as a reward or daily login prize. TY <3

**Which servers does this apply to?**
All

**Comment by HackuJacku** [comment]
Already being looked into.
