### ISSUE TITLE
Warzone feature

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#206]
**Describe the suggestion**
grace period after you catch (and or battle) a Pokémon in wz. If your Pokémon are low health and someone attacks you right after you catch that Pokémon, it gives you an unfair advantage in the battle.

**Which servers does this apply to?**
All

**Comment by HackuJacku** [comment]
Added to the Warzone master ticket. This will be addressed with the Warzone overhaul.
