### ISSUE TITLE
Add JEI, NEI and Code Chicked mods to the modpack.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#218]
**Describe the suggestion**
Add the Just Enough Items mod, Not Enough Items mod and Code Chicken mods to the modpack. 

**Which servers does this apply to?**
Network.

**Comment by HackuJacku** [comment]
JEI will be part of the modpack when we update to 8.2 - NEI is the same. ChickenBonesCore (mods) won't be required.
