### ISSUE TITLE
Add a cooldown for using /warp warzone after losing 

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Suggestions#23]
**Describe the suggestion**
adding a cooldown of around 15s to use /warp warzone, so that players cant instantly get in warzone after losing so they cant go in with 5 pokemon
**Which servers does this apply to?**
all servers

**Additional context**
(a player being able to steal from 5 pokemon) 
![image0 (4)](https://user-images.githubusercontent.com/83245837/117391070-7c6c1c80-aeac-11eb-9047-19da048db466.jpg)

**Comment by HackuJacku** [comment]
Similar to #294
