### ISSUE TITLE
Add Kubfu banners and gmax mushrooms to /warp mart

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#24]
**Describe the suggestion**
Add the Kubfu banners and Gmax mushrooms at /warp mart upon next update.

**Which servers does this apply to?**
Network.

**Comment by Mikirae** [comment]
What are Kubfu banners?

**Comment by LifelessDingus** [comment]
The banners to evolve Kubfu into Urshifu.

**Comment by HackuJacku** [comment]
We'll be implementing unique, custom methods of obtaining the Scrolls and already have one for obtaining the Max Mushroom. I'll forward this onto the economy-related master ticket though.
