### ISSUE TITLE
Auto  Roles in discord

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#25]
**Describe the suggestion**
add autoroles for every server so members can give themselves the role for the servers they play in making it easier to find people who play on the same server as you

**Which servers does this apply to?**
Discord

**Additional context**
There is already auto roles, /link and #role-notificattions

**Comment by Rasgnarok** [comment]
It would be better for them to be opt-in, or rather, automatic with opt-out. Either way, duplicate as one is now linked to https://github.com/SmashMC-Development/Suggestions/issues/452
