### ISSUE TITLE
Add: creeper heads, enchanted golden apples and skeleton skulls to the NPC's in /warp mart.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#274]
**Describe the suggestion**
Add creeper heads, enchanted golden apples and skeleton skulls to /warp mart, so that people who make banners can still do this.

**Which servers does this apply to?**
Network.

**Comment by HackuJacku** [comment]
Which server(s) is this for please?

**Comment by Rasgnarok** [comment]
Forwarded to main tracker, duplicate of #319.
