### ISSUE TITLE
Change login rewards

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#28]
**Describe the suggestion**
Change login rewards

**Comment by Mikirae** [comment]
Would need more details on this. Mainly suggestions on what to change things to.

**Comment by Lun17** [comment]
Player didn't provide more infos

Il mer 19 mag 2021, 02:16 Mikirae ***@***.***> ha scritto:

**Comment by Mikirae** [comment]
Thanks for replying bb. Going to be closing this then as there's really not enough to go on.
