### ISSUE TITLE
There really needs to be an easy way for people to price check pokemon

### ISSUE THREAD

**Issue by Daddyricardo** [SmashMC-Development/Suggestions#295]
**Describe the suggestion**
A way to check for prices on pokemon

**Which servers does this apply to?**
All

**Comment by Rasgnarok** [comment]
Forwarded to main tracker, though note that we won't be enforcing a price list outside of minimum GTS pricing because this is heavily dependent on demand vs supply. Prices are not static. That said, this could also fall on the eco book recommended in #523. Closing.
