### ISSUE TITLE
Add an anti-cheat on the server

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#30]
**Describe the suggestion**
Add an anti-cheat on the server to stop grief and real hacks,

**Comment by jahangir6969** [comment]
@Lun17 What server?

**Comment by jahangir6969** [comment]
#199

**Comment by Lun17** [comment]
Suggestion was mostly on pixelmon, but it can be said for full network

Il lun 10 mag 2021, 19:08 jahangir6969 ***@***.***> ha
scritto:

**Comment by Mikirae** [comment]
We have mods that ban certain clientside mods that we can detect. Currently not possible for us to get hacked either. We've got everything going on to prevent being hacked that we can and there's really nothing more that we could do.
