### ISSUE TITLE
Custom Prices

### ISSUE THREAD

**Issue by Daddyricardo** [SmashMC-Development/Suggestions#308]
**Describe the suggestion**
can we get like a sign on /gts sell that can let us do custom prices?

**Which servers does this apply to?**
All

**Comment by HackuJacku** [comment]
Custom prices for what please?

When we update to Pixelmon 8.2, we will be introducing minimum enforced GTS prices for legendaries/mythicals and hidden abilities.

**Comment by Rasgnarok** [comment]
Closing since this is both a minimum pricing enforcement, or a custom one that circumvents minimum pricing, which defeats minimum pricing. See https://github.com/SmashMC-Development/Suggestions/issues/522 for a list of economy improvements to discuss.
