### ISSUE TITLE
Add Kermit emotes to the discord.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#33]
**Describe the suggestion**
Add a few Kermit the Frog emotes to the discord server.

**Which servers does this apply to?**
Discord. 

**Additional context**
/

**Comment by Rasgnarok** [comment]
Examples?

**Comment by Rasgnarok** [comment]
After reviewing the examples provided, I'll decline this suggestion since it is not related to Pixelmon/Pokemon in any way. Maybe use Nitro for that kind of content to share.
