### ISSUE TITLE
Ranch Upgrades 

### ISSUE THREAD

**Issue by Daddyricardo** [SmashMC-Development/Suggestions#361]
**Describe the suggestion**
Ranch blocks should not lose their upgrades when you go to move or remove them. 

**Which servers does this apply to?**
All

**Comment by Rasgnarok** [comment]
This is a Pixelmon balancing decision, and it makes sense for it to have a mechanic to decay upgrades. I'll be declining this one, as there needs to be some form of loss if upgrades are to be worth something.
