### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by Daddyricardo** [SmashMC-Development/Suggestions#366]
**Describe the suggestion**
A trainer at spawn with a strike form pokemon for the galar bird quests

**Which servers does this apply to?**
All

**Comment by HackuJacku** [comment]
Although this suggestion is great, we sadly won't be adding it as this would make getting the Galarian Birds much easier - this would have economical and balancing impacts. As it is, we're looking into making it so the non-Galarian Birds harder to get/worth more.
