### ISSUE TITLE
Their should be more minigames aside from events that can be played whenever.

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#37]
Their should be more minigames aside from events that can be played whenever. maybe even be able to make money/rc off it too. Depends on the minigame, the game can only start when their is a certain number of players and their can only be 1 game up and going at a time so their is a waiting list for people waiting to come into the next game so it still takes time if u want to use as a way to make all your money so it cant be abused to be rich

**Comment by Mikirae** [comment]
Automated events are exceptionally hard to handle, but we can look into getting something for this :)

**Comment by HackuJacku** [comment]
Already part of the roadmap for the future - expect greatness over the summer!
