### ISSUE TITLE
Palkia

### ISSUE THREAD

**Issue by Daddyricardo** [SmashMC-Development/Suggestions#379]
**Describe the suggestion**
Fix palkia. its a great server but no staff plays,warzone is bugged, and boss tower isnt as good

**Which servers does this apply to?**
Palkia

**Comment by HackuJacku** [comment]
@Daddyricardo - although this isn't your suggestion, I need more information than this please as I have zero clue what the issue is. The 'warzone is bugged' needs to be on the bugs and issues repository and what exactly is wrong with the boss tower?

**Comment by Mikirae** [comment]
Have not heard about it being bugged but the boss tower is quite literally the exact same as the rest of the servers.
