### ISSUE TITLE
pokemon daycare

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#386]
for new players it is really complicated to know how to breed and you have to pay like a price for how fast you want your egg

**Comment by Mikirae** [comment]
This is currently a plugin that we could purchase and configure. I can look into it this week :)

**Comment by Rasgnarok** [comment]
It would be extremely hard, near impossible, to adjust the pricing of your egg to the value of the egg resulting. I don't think it's as simple as egg = $, and it'll be based on every server's eco, not withstanding the current, normal ranch block egg pricing.
