### ISSUE TITLE
make a system where warzone legends are guaranteed to spawn every 1 hour to 2

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#39]
make a system where warzone legends are guaranteed to spawn every 1 hour to 2 and a half hours the rates aren't very good and if its randomly spawning in that time frame it would make warzone a bit more active

**Comment by Mikirae** [comment]
Legends already spawn very frequently in Warzone, and adding a guarantee is just going to overflow the market.
