### ISSUE TITLE
Buff legendary and shiny spawn rates in /warp safari. 

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#397]
**Describe the suggestion**
Buff legendary and shiny pokemon rates in /warp safari, so that the spawnrates are somewhere in between warzone's- and the overworld's spawnrates. 

**Which servers does this apply to?**
Network.

**Comment by HackuJacku** [comment]
Although this is a great suggestion, we won't be adding it as it takes away from Warzone - the high rewards aspect. Due to these high rewards, it has a high risk for balancing/content reasons.
