### ISSUE TITLE
Player warp shops

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#40]
**Describe the suggestion**
There should be player warp shop where players pay to have a warp to there personal shops and people can freely warp to your shop without you having to promote it. 

**Which servers does this apply to?**
All

**Comment by Mikirae** [comment]
We could potentially get GUI shops in the future, however I'm unsure about ones that players can teleport too.

**Comment by HackuJacku** [comment]
Implemented on the upcoming reset! Master (Dex), Legend (Paid) and Smash (Paid) ranks now give you a PlayerWarp token. This can be used to set a public warp for players
