### ISSUE TITLE
add a command to where we can see the price ranges of each things (last price sold for and highest price sold for)

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#403]
add a command to where we can see the price ranges of each things (last price sold for and highest price sold for)

**Comment by Rasgnarok** [comment]
This would require significant logging, and I am not sure it's a good idea - it would be auto checking every item sold ever. Moreover, it wouldn't be useful when it comes to regulating the market. If anything, it would help narrow exactly what the next lowest price is, as everything devaluates.

**Comment by Rasgnarok** [comment]
Moved to the main ticket for economy suggestions.
