### ISSUE TITLE
a way to get IV boosts other than crates

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#409]
a way to get IV boosts other than crates cuz people just hoard them and its really hard to get them from buying cuz of that

**Comment by HackuJacku** [comment]
We will be introducing some additional (free) ways to get reward papers soon but only a couple of them will be available.

With the crate rewards being buffed, it's possible to get keys for the higher crates without paying from them. Removing all the papers from the crates would take away from the crates, this is something we don't wish in doing.
