### ISSUE TITLE
Add quests to obtain legendary pokemon.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#41]
**Describe the suggestion**
Add quests that give you the option to battle a legendary pokemon upon completion. 

**Which servers does this apply to?**
Network. 

**Additional context**
This makes it possible to get legendaries in quests, rather than risking to lose pokemon in warzone to complete the dex.

**Comment by Mikirae** [comment]
Legends also spawn outside of Warzone, but we can discuss making certain legends available via quests.

**Comment by HackuJacku** [comment]
Already on the roadmap for the future - quest team.
