### ISSUE TITLE
Implement a "peace zone" or "friend zone". 

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#412]
**Describe the suggestion**
Make a peace zone or friend zone. In this warp, pokemon spawn like they would in warzone, but the rates are slightly decreased. People can battle here for fun without pokemon being stolen. 

**Which servers does this apply to?**
Network.

**Comment by HackuJacku** [comment]
Although this suggestion is great, it sadly won't be added as it'll be taking away from Warzone. It would also be unbalanced as there is no risk of going there, whereas Warzone has those high rewards for those high rewards.
