### ISSUE TITLE
make the boss tower have the spawns faster

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#413]
make the boss tower have the spawns faster because the only efficient level in the boss tower is the ghost types.

**Comment by HackuJacku** [comment]
@Lun17 - are these regarding the naturally spawning boss towers or `/warp boss`?

**Comment by Lun17** [comment]
/warp boss

Il sab 8 mag 2021, 21:22 HackoJacko ***@***.***> ha scritto:
