### ISSUE TITLE
Golem With No Sturdy

### ISSUE THREAD

**Issue by Daddyricardo** [SmashMC-Development/Suggestions#42]
At ./warp training no golem with sturdy makes it harder to kill also no shines spawning and bosses because it teases us not able to be caught or rewards to be dropped.

**Comment by Mikirae** [comment]
I thought there were no more golems at EVs. Is this a super old suggestion or are they still on some servers?

**Comment by HackuJacku** [comment]
@Sparklix will be doing this either on Friday or Saturday.

**Comment by Sparklix** [comment]
@Daddyricardo Golem has been removed from the training area's. Thank you for your suggestion
