### ISSUE TITLE
Add a cooldown before entering warzone after being kicked out / leaving.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#421]
**Describe the suggestion**
Add a cooldown before entering warzone after leaving / being forced out. This so people can't quickly enter the warzone after being kicked out, entering again with 5 pokemon. 

**Which servers does this apply to?**
Network.

**Comment by Mikirae** [comment]
I think that we can make a check in Warzone itself every X seconds that can prevent those with 5 Pokemon from being in there, and being kicked out upon discovery.

**Comment by HackuJacku** [comment]
Added to the Master Warzone ticket. This will be taken into consideration when we overhaul Warzone.
