### ISSUE TITLE
random raid Pokémon spawns in warzone but with low possibility of them spawning.

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#423]

**Comment by Lun17** [comment]
Yep

Il sab 8 mag 2021, 21:14 HackoJacko ***@***.***> ha scritto:

**Comment by Mikirae** [comment]
I personally don't see this as a good idea, as I think there's going to be a lot of issues with people sitting in there avoiding fights by just being in the raid boss battle for an extended period of time, and only leaving when a legend spawns, or people just in general doing things in ways that I haven't thought of yet.

**Comment by HackuJacku** [comment]
Added to the Master Warzone ticket. This will be taken into consideration when we overhaul Warzone.
