### ISSUE TITLE
Touch up the Battle Tower a little

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#425]
Why not add a doubles section. If we’re being fancy, why not even some Battle Frontier style formats too? It gets a little grind-y playing the same singles with the same movesets.

**Comment by HackuJacku** [comment]
@Lun17 - Battle Frontier is something which Waterdude/myself are working on. I've been working on a spec for a while but it won't be added soon sadly. 

Once it's available, I'll bring it up to get it added.
