### ISSUE TITLE
a way to claim the /dex claim reward for master cuz for the 10% milestones we usually get a reward and for master we cant

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#431]

**Comment by HackuJacku** [comment]
Currently a bug with the PokéDexRewards plugin - we're looking into a replacement for future-proofing. The current issue is making the plugin work and converting the current data from the existing to replacement.

**Comment by HackuJacku** [comment]
Replacing plugin with a new, fixed version.
