### ISSUE TITLE
Cheaper building blocks in /warp mart

### ISSUE THREAD

**Issue by Ryan1595** [SmashMC-Development/Suggestions#441]
**Describe the suggestion**
Add almost all building blocks to /warp mart for like $1-2 per block. Since large red stone contraptions are banned, and there are no mobs, many building blocks are hard to obtain. As is currently is, it is about 80k for an inventory of dark prismarine (which is hard to obtain without guardians). This also won't screw up the economy because I have never really seen anyone selling blocks on gts.

**Which servers does this apply to?**
All pixelmon servers

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
What I'd like to know, is which blocks you think are too expensive, and what the price drop compares to the amount of money that can be generated - eg, the effort vs the worth of the blocks buying.

**Comment by HackuJacku** [comment]
Implemented on the reset
