### ISSUE TITLE
Warzone is not high risk, it needs to change.

### ISSUE THREAD

**Issue by JaggyL** [SmashMC-Development/Suggestions#443]
When I first joined this server i was under the impression that warzone was a "high risk for high reward area", this is currently as far from the truth as possible as players are literally bringing 6 level 75 sevipers/zangoose/magikarps to run in whenever something spawns with no risk whatsoever. Its gotten to the point that players know the people actually trying to compete wont bother them anymore because they only bring crap thats not worth been stuck in battle for 20 mins. i have lost numerous legends to people that run in with 6 level 75s and instantly safeplace after nabbing the legend that spawns. The only difference this server has to any other pixelmon server out there is warzone, it is the deciding factor on whether people will join or not imo and it has been left behind to rot without much consideration into the rules. please consider raising the level cap to 100 and implementing a rule where you cannot leave within 5 mins of entering warzone. this will highly discourage people using throws anymore because its alot more effort to get them to level 100 and completely stop the players with no intention of fighting even entering in the first place if they know they cannot sp for 5 mins. I understand the majority of the player base are casuals and you have to tend to their needs but warzone should be end game content, it shouldnt be the place everyone rushes to with level 75s. Please rework the warzone to be more competitive like its advertised as. I cannot stress enough the level of play currently going on is really bad.
![wzisntfun](https://user-images.githubusercontent.com/84136271/118132590-c34f9a00-b3f7-11eb-9cf6-1b77eca0ba91.png)

**Comment by Rasgnarok** [comment]
This can be segmented into different issues.
1) Players shouldn't have first evo species
2) Level requirement should be higher
3) Trainer level could be taken into consideration (and how can we define a Trainer's level?)
4) Rewards should be equal to effort
5) Some Warzones are under the control of a select few - is this what we want, or is this something we need to reconsider in rebalancing the gamemodes/difficulties?

Inviting my peers, @HackuJacku @Mikirae @AmsterDaan to the table.

**Comment by HackuJacku** [comment]
Warzone 2 is introducing a lot of new elements to the Warzone. It'll become very high risk (forcing you to battle players) and high reward (using throw teams will put you at a disadvantage now...)
