### ISSUE TITLE
Stuff to add to /warp mart

### ISSUE THREAD

**Issue by whitesaber31** [SmashMC-Development/Suggestions#444]
**Describe the suggestion**

Add Notch Apple and creeper head in mart or as boss drops.
Or also move wither skull into mart since they are useful for creating banners in 12.2

Add Gracidea, galarica twig, sweet apple, and sweets for milcery in black market at /warp mart

Add Mail vendor in mart so some players can buy empty mails to use

Add End Rod, andesite,diorite, granite in building shop, because it's still missing.

**Which servers does this apply to?**
All the server

**Additional context**
'N/A'.

**Comment by HackuJacku** [comment]
Implemented on the reset
