### ISSUE TITLE
Apricorn limit

### ISSUE THREAD

**Issue by LePlasma** [SmashMC-Development/Suggestions#447]
**Describe the suggestion**
Increase the apricorn amount per chunk to 36, 32 at least.
The vast majority of servers have decided that 32 is a good amount, and I see no reason as to why it is not. 25 apricorns for a server with 25-30 players on at a time just seems too small.

**Which servers does this apply to?**
All of them, or at least Dialga :))

**Comment by Rasgnarok** [comment]
It is indeed per chunk, and so therefore, you can spread it across two chunks with no problem. Having it lower will actually impact low-performing players. This config option isn't for server lag, but for FPS lag - client side.
