### ISSUE TITLE
Increase berry/chunk limit

### ISSUE THREAD

**Issue by SolaceKairos** [SmashMC-Development/Suggestions#448]
**Describe the suggestion**
Increase in berry plants allowed in one chunk (currently 15).

**Which servers does this apply to?**
All, likely. (Charizard at least)

**Additional context**
There is an option in the config that allows there the be different berry plant amounts per chunk. This limit of 15 is too small for farming and very few players farm berries.

**Comment by HackuJacku** [comment]
Why should it be increased?

**Comment by Rasgnarok** [comment]
What Hacko was asking in this case, @SolaceKairos , is why should it be higher when you can plant 15 per chunk (and therefore plant cross-chunk, limiting the amount of lag). I know that it might seem like a small number, but let me do some math with ya - view-distance is of 6, meaning you can see 6 chunks in radius around you. 

This means that you see about 113 chunks at all times, in maximum. if each of those chunks have 15 berry/apricorn trees, you could see up to 1695 trees by standing still. That's a lot of lag. 

Granted, not every player will plant that much, but that's the physical limit that we can only manage by setting a limit to the amount of trees per chunk. It could be easily abused already, and increasing it would only make it worse. I hope you understand.
