### ISSUE TITLE
Better permanent way to obtain Zygarde Cells

### ISSUE THREAD

**Issue by SolaceKairos** [SmashMC-Development/Suggestions#449]
**Describe the suggestion**
Add a way for Zygarde Cells/Cores to be allowed to continue spawning past the first 30 minutes of a chunk being loaded (possibly with reduced rates).

**Which servers does this apply to?**
All, hopefully.

**Additional context**
To obtain Zygarde cells, new chunks must be located. Due to the server having a relatively small border (compared to server playtime) a massive amount of the available chunks have been located with very few methods to check if a chunk is new (without hacking). There is one solution: Warzone has Zygarde, but many players enjoy getting legendaries through the intended means.

**Comment by HackuJacku** [comment]
Same as #9

**Comment by SolaceKairos** [comment]
This is not the same as #9. #9 asks to get Zygarde >without cells<, I am asking to be able to get cells through a new means. Please reconsider this or be more specific.
