### ISSUE TITLE
Add roles for different servers.

### ISSUE THREAD

**Issue by Asunaaaaaaa** [SmashMC-Development/Suggestions#452]
**Describe the suggestion**
Add a role for each server, that way people won't be pinged when something is happening that does not effect them. For example, @Charizard for whenever an event is about to happen on Charizard as opposed to @everyone when it has nothing to do with other people. More people are being pinged that aren't involved than those that are.

**Which servers does this apply to?**
All servers

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
I really like this idea, it'll have to be brought up in a master ticket for Discord bot ideas.

**Comment by Charizard** [comment]
Hi 👋 I am @Charizard!
