### ISSUE TITLE
Event-Host roles 

### ISSUE THREAD

**Issue by Awlk** [SmashMC-Development/Suggestions#453]
**Describe the suggestion**
possible to make the event host tags into [p] and [v]eventhost so the right event hosts will be pinged

**Which servers does this apply to?**
discord 

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by Rasgnarok** [comment]
Done setup, duplicated events channel to now divide between Pixelmon and Vanilla.
