### ISSUE TITLE
#22158-zygardespawnquestion

### ISSUE THREAD

**Issue by SolaceKairos** [SmashMC-Development/Suggestions#454]
**Describe the suggestion**
Check out the spawning of Zygarde cells and cores because they are seemingly not functional.

**Which servers does this apply to?**
Charizard, at least.

**Additional context**
I went onto the discord and asked about the spawning on the server as a result of my trialing.
I was curious as to if the spawning was disabled or just hard to find (or both).

I needed to find new chunks and found a way to verify that they are: new water/lava flowing from places they would have flown from before if previously generated. If I were to witness water/lava falling from a position it would have done if previously generated, I was able to know the area was NEWLY generated. Then, I would search around the area with a zygarde_cube in-hand. I tested this in the dimensions of ultra-space and the overworld. I spent around 4-6 hours in new chunks for both.
During that time, I was able to obtain 0 cells and 0 cores (in new chunks).

I went into singleplayer to test if I even knew what I was doing, moments after creating the world, I was able to find multiple. After but only half an hour of time, I was able to find 4 cores in singleplayer. I'm aware singleplayer and multiplayer are quite different, but this is still indicative of some issue.

I went onto discord and asked about this and was told they weren't disabled; then opened a ticket to query about this.
Knalboy_YT, DiegoKek, and Asuna_Yuuk1 answered the questions, over-all stating that it wasn't disabled. However, Knalboy_YT ran an experiment very similar to mine and found 0 cells and 0 cores (but only spent under and hour on it).

I was then recommended to make a suggestion here. I did this in the past and my suggestion was (I believe) inaccurately closed for being similar to post #9. I'd like to highlight how this is not similar to #9: it asks for a way to obtain Zygarde without cells, I am not asking this; I would like to obtain Zygarde in the intended way. (New chunks have been found easy (for the moment) to find by myself and others- even on Charizard.)

**Comment by HackuJacku** [comment]
Zygarde cells and cores do not currently spawn. You're able to get them from de-assembling a Zygarde (you can get these from Warzone, crates, the store, ETC). We'll be adding a unique, custom method of getting these items in the future - we appreciate any ideas for this.
