### ISSUE TITLE
[Master Ticket] Warzone

### ISSUE THREAD

**Issue by Rasgnarok** [SmashMC-Development/Suggestions#458]
Master ticket for all the Warzone issues, suggestions and comments to be linked to. Once linked here, the original ticket will be closed so it all links back to this master ticket.

**Comment by HackuJacku** [comment]
#483

**Comment by HackuJacku** [comment]
#485

**Comment by HackuJacku** [comment]
#482

**Comment by HackuJacku** [comment]
#429

**Comment by HackuJacku** [comment]
#423

**Comment by HackuJacku** [comment]
#421

**Comment by HackuJacku** [comment]
#416

**Comment by HackuJacku** [comment]
#368

**Comment by HackuJacku** [comment]
#358

**Comment by HackuJacku** [comment]
#350

**Comment by HackuJacku** [comment]
#325

**Comment by HackuJacku** [comment]
#294

**Comment by HackuJacku** [comment]
#290

**Comment by HackuJacku** [comment]
#289

**Comment by HackuJacku** [comment]
#283

**Comment by HackuJacku** [comment]
#278

**Comment by HackuJacku** [comment]
#271

**Comment by HackuJacku** [comment]
#264

**Comment by HackuJacku** [comment]
#259

**Comment by HackuJacku** [comment]
#246

**Comment by HackuJacku** [comment]
#213

**Comment by HackuJacku** [comment]
#206

**Comment by HackuJacku** [comment]
#185

**Comment by HackuJacku** [comment]
#182

**Comment by HackuJacku** [comment]
#167

**Comment by HackuJacku** [comment]
#138

**Comment by Rasgnarok** [comment]
https://github.com/SmashMC-Development/Bugs-and-Issues/issues/239

**Comment by Rasgnarok** [comment]
https://github.com/SmashMC-Development/Suggestions/issues/513

**Comment by Rasgnarok** [comment]
https://github.com/SmashMC-Development/Suggestions/issues/494

**Comment by Rasgnarok** [comment]
Custom music: https://github.com/SmashMC-Development/Suggestions/issues/497

**Comment by Rasgnarok** [comment]
Battle rules display and rework: https://github.com/SmashMC-Development/Suggestions/issues/481

**Comment by Rasgnarok** [comment]
Warzone and lack of difficulty: https://github.com/SmashMC-Development/Suggestions/issues/443

**Comment by Rasgnarok** [comment]
Network warzone: https://github.com/SmashMC-Development/Suggestions/issues/261

**Comment by HackuJacku** [comment]
Safeplace Timer Increase: #27

**Comment by HackuJacku** [comment]
Boosts: #66

**Comment by HackuJacku** [comment]
SmashMC-Development/Bugs-and-Issues#90

**Comment by Rasgnarok** [comment]
Special textures: https://github.com/SmashMC-Development/Suggestions/issues/555

**Comment by HackuJacku** [comment]
Implemented on the reset
