### ISSUE TITLE
Adding more decorative/building blocks to /warp mart

### ISSUE THREAD

**Issue by Unitzero007** [SmashMC-Development/Suggestions#459]
**Describe the suggestion**
I am requesting for the addition of blocks like 
>concrete (powdered and non-powdered forms) 
>gravel/sand
>red dyes
> pixelmon streetlights
> dispensers
> camera film
> item frames

**Which servers does this apply to?**
All Servers Pixelmon-Side

**Additional context**
If there are too many variation of concrete to add, just add sand + gravel instead. It is actually pretty hard to get a lot of gravel easily especially with how slow you mine in the ocean and how few layers of gravel that are actually present.

As for the dispensers, I am requesting for those as string is not so common to find and dispensers are mainly used as breeding blocks for flying types (the other option at 3 points are beacons which are too expensive).

**Comment by HackuJacku** [comment]
All added to the internal list - does not guarantee they all will be added but in review.
