### ISSUE TITLE
warzone legendary spawn rate

### ISSUE THREAD

**Issue by harrybow9187** [SmashMC-Development/Suggestions#461]
**Describe the suggestion**
increase the legendary spawn rate as it has been turned down too low in the last 20 since this suggestion is being made there has been 1 legendary spawn and it was a ho-oh since then nothing has spawned after it and it has been 20 hours this is not right the spawn rate is to low.

**Which servers does this apply to?**
Palkia

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Same as #462
