### ISSUE TITLE
Spawn rate of legendaries in warzone

### ISSUE THREAD

**Issue by Zekalfra** [SmashMC-Development/Suggestions#462]
Hello staff,

So I've been in Giratina today for 6 hours with 5-8 people always in warzone. At the moment only 1 legendary spawned in all this time. Something isn't right, could be the fast spawn of normal pokes that cancel the spawn of legendaries or other issue.

Thanks a lot,
Zekalfra

**Comment by HackuJacku** [comment]
It's not an issue with the rates, it's an issue with something else. It's fixed but we will not be going back to the insane rates that Warzone was previously for weeks before the update.
