### ISSUE TITLE
Set NPC's back to equal rather than legendary (player suggestion)

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#463]
**Describe the suggestion**
The levels of NPC Gyms and Mrs. Eevee have been buffed to lvl 140 when using a legendary, rather than staying at lvl 100. The bosses, are now legendary type, rather than equal. Please change this back.

**Which servers does this apply to?**
Network.

**Additional context**
N/A.

**Comment by HackuJacku** [comment]
Pixelmon bug caused by an update. Unsure if it's still an issue - create a bug report if it is please.
