### ISSUE TITLE
Adding chat channels

### ISSUE THREAD

**Issue by SolaceKairos** [SmashMC-Development/Suggestions#464]
**Describe the suggestion**
Add chat channels: local & global. And one for players verified over the age of 12: one where different rules are in place for the moderation of chat.

**Which servers does this apply to?**
At least charizard.

**Additional context**
The rules against things like passive (non-aggressive) swearing and other "minor-knowledge-aimed" rules enforced make me feel as though I have walked into a daycare and decided to stay for some reason.

**Comment by SolaceKairos** [comment]
Maybe a profanity filter that allows texts with swears to go through or not

**Comment by SolaceKairos** [comment]
Or maybe a filter for certain ranks and above given you achieve a certain rank

**Comment by SolaceKairos** [comment]
Maybe an additional feature of seeing only what staff says in main chat too

**Comment by SolaceKairos** [comment]
Oh! maybe have a customizable list of words (for each player) that can be edited and has swears by default

**Comment by HackuJacku** [comment]
From a logistical point of view, we don't want to divide up the chat because this will open up a lot of complicated issues.
