### ISSUE TITLE
Add Special Textures to the gts

### ISSUE THREAD

**Issue by sjhaalki** [SmashMC-Development/Suggestions#465]
**Describe the suggestion**
It would really help a lot if you could add a description to the gts for pokemon with a special texture.
The old gts would tell you if a pokemon is a shadow/galaxy etc, and that obviously boosts the value.
People won't buy a galaxy that's worth 150k, if they only see the pokemon as a normal one without a texture.

**Which servers does this apply to?**
Every Server

**Comment by HackuJacku** [comment]
Added.
