### ISSUE TITLE
Remove the chance for chickens to spawn from eggs

### ISSUE THREAD

**Issue by Unitzero007** [SmashMC-Development/Suggestions#466]
**Describe the suggestion**
Baby Chickens can spawn from eggs and they are lagging out the server, disable the ability for eggs to spawn chickens.

**Which servers does this apply to?**
All (At least Pixelmon)

**Additional context**
N/A

**Comment by SolaceKairos** [comment]
Are they really lagging the server? I never knew this was possible and am now interested. There must be massively more pixelmon than chickens, right? Maybe an admin can give data from the server on this :o

**Comment by Unitzero007** [comment]
I believe its more because of how many can be spawned in one chunk and the fact that an immense amount of them can be spawned  in one area, while the Pixelmon are all spread out. Though whether or not it lags out the server is just my poor wording, It really just affected my framerates and I could not move for a bit cause of the sheer amount of entities that were there.

**Comment by HackuJacku** [comment]
Developed a plugin. Will be added soon.
