### ISSUE TITLE
dmax band

### ISSUE THREAD

**Issue by theZhaZha** [SmashMC-Development/Suggestions#467]
remove dmax band quests, it makes that noone wants to fight the gyms anymore + before ppl that got the dmax band by beating the gyms makes the band a symbol of being good, being good at battling, but now every1 has the chance to have it, makes the dmax band common.

**Comment by HackuJacku** [comment]
The Gym rewards will be getting an overhaul in the future. We'd like to make Dynamax accessible to everyone, through hard work.
