### ISSUE TITLE
Make Chisel and Curry Ingredient Accessible

### ISSUE THREAD

**Issue by whitesaber31** [SmashMC-Development/Suggestions#468]
**Describe the suggestion**
Make chisel and curry ingredients affordable or craftable in the game, so people can craft pokemon sculptures easily or make curry for fun

**Which servers does this apply to?**
all servers

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
The chisel will not become accessible for players. We will look into the curry ingredients.

**Comment by Rasgnarok** [comment]
Forwarded to the master ticket.
