### ISSUE TITLE
Shrines and GTS

### ISSUE THREAD

**Issue by lebarnez** [SmashMC-Development/Suggestions#473]
Lower or get rid of the summoning price for all of the shrines. Remove the GTS tax. This applies to all servers. I think that it is dumb to have a summoning price for shrines and a tax for GTS. I understand that players can save up a lot of orbs and summon birds at once, but that is because they grinded to fill the orb, or paid money for someone to fill it for them. I believe that is a fair way of making money, especially for newer players. If there really is an issue about the economy and spamming shrines to make money, then simply lower the sts price of the legendaries summoned. I don’t think it’s right to charge a player money, especially 10k, to summon these legendaries. For the GTS tax, I do not understand why this was added at all. I do not think that players should be forced to pay a certain amount of money to put items or pokemon on GTS. GTS is to make money and sell goods, and if no one is purchasing them, you ultimately will lose money. I am concerned for the players starting off, who have no money. They would not even be able to afford to put items on GTS. I do not understand how this is supposed to help the economy, and I feel like it would make people less likely to put their things on GTS. If there are specific reasons for GTS taxing and a summoning price, please do not be afraid to talk to me, but I think that these additions are completely unnecessary and a bit extreme, especially 10k to summon.

**Comment by Junioriwnl** [comment]
I totally agree with this statement

**Comment by Rasgnarok** [comment]
Moving this to the main ticket so it can be discussed further - feel free to keep explaining things as you need, I'll have more input soon.
