### ISSUE TITLE
Max Mushrooms and Dynamax Candy 

### ISSUE THREAD

**Issue by xPrimordial** [SmashMC-Development/Suggestions#474]
**Give players an easier time farming**
Since Max Mushrooms are supposed to spawn naturally, what about adding them to the /timeshop so players can get them for just playing on the server.

**Applies to all servers**
I think this would be a good additions to all servers. 

**Additional context**
N/A

**Comment by HackuJacku** [comment]
We'll look into additional ways to get both of these items but it may not be the TimeShop.

**Comment by Rasgnarok** [comment]
Forwarded to master ticket on economy
