### ISSUE TITLE
Tax changes

### ISSUE THREAD

**Issue by sjhaalki** [SmashMC-Development/Suggestions#475]
**Describe the suggestion**
Change the taxes so it charges you AFTER the item sells, not before. This is how it's done in literally every game and it works for a reason. The way it is now, people are too hesitant to use the Gts because they don't want to pay taxes for something that will most likely not sell that fast. It just doesn't make sense to charge you before actually selling anything and it impacts the market a lot.

**Which servers does this apply to?**
Every Server

**Comment by Mikirae** [comment]
Pretty sure Hacko was looking into something like this before.

**Comment by Rasgnarok** [comment]
Forwarded to the main ticket, since GTS is a contentious topic, yet still eco-related.
