### ISSUE TITLE
Tax changes (player suggestion)

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#476]
**Describe the suggestion**
My suggestion is to remove the new payments for the legendary pokemon shrines due to me and other players,this was implumented into the servers after fixing the shrine glitches to prevent people from getting a ton of legendarys and abusing it.However,I think that that change was unessisary, after doing some reasearch,i descovered that the shrines already have a feature to prevent people from abusing the shrines(atleast with the celibi and the creation trio+arceus shrines,not sure about the legendary birds but they are not that good anyway so it dont matter). on top of this 
getting the requirements to summon those legendarys/myhicals are already a chore to do, the creation trio requireing you to have all 3 of the lake trio (which are already
very hard to find outside of warzone) plus the orb for the persific pokemon you want, as for arceus, you have to find all 17 plates to summon arceus, which is very time 
time consuming (asuming you are using the wormhole technique which already needs you to find a wormhole which is hard already)plus abit of rng is involved
 since theres a chance u wont get the last plates you need and might get something like safety goggles/memorys/beast balls or z crystals.as for celibi im not sure how likely
 it is to get a gs ball but im asumming its hard to get. Overall i think that the payment of the shrines are unnessisary and annoying to alot of players.

**Which servers does this apply to?**
as for what servers this applys on, im hoping this will apply to all servers (myself being in giratina).

**Additional context**
Made by WoomyLord41 aka WoomyOverlord

**Comment by HackuJacku** [comment]
The taxs will remain. They have already taken a great deal out of the economy which is exactly what we're after. Warzone makes it very easy to get the items required to spawn legendaries. Due to Warzone and the free shrines at spawn, these legendaries are worth very little and are typically used for money farming.
