### ISSUE TITLE
Calyrex Reins

### ISSUE THREAD

**Issue by Zekalfra** [SmashMC-Development/Suggestions#477]
Hello staff,

I wonder if we could get the item "reins of unity" added to the calyrex that spawn in warzone. It's really hard to find calyrex in the wild and there are other legendaries that are way stronger than calyrex with a horse and can be found normally in warzone.
I would suggest to add the item to calyrex in warzone or have like a type of quest that you have to do to acquire that item.

Thank you,
Zekalfra754

**Comment by sjhaalki** [comment]
I doubt it tbh. The held items never were included in WZ spawns, not for Kyurem, nor for Necrozma etc

**Comment by Zekalfra** [comment]
> I doubt it tbh. The held items never were included in WZ spawns, not for Kyurem, nor for Necrozma etc

i mean, they could sell in market aswell as the others items

**Comment by DragonBallBreakersRandomizer** [comment]
Makes it rare and if it did spawn in wz with it it wouldn't be worth much

**Comment by Mikirae** [comment]
Held items won't be included on Warzone spawns, but like I said in the other ticket, we're adding a way to get them for the average player :)
