### ISSUE TITLE
Galaxy texture for Mew

### ISSUE THREAD

**Issue by sjhaalki** [SmashMC-Development/Suggestions#478]
**Describe the suggestion**
Mew doesn't have a galaxy texture yet, considering how old it is

**Which servers does this apply to?**
Every Server

**Comment by HackuJacku** [comment]
Mew will not get a Galaxy texture currently, the UV map is poorly created and means the texture will not appear as good as we're after. Once Pixelmon replace its UV map, we will add a Galaxy Mew texture.
