### ISSUE TITLE
Change, Remake or Add onto the Player Gym Rewards

### ISSUE THREAD

**Issue by Unitzero007** [SmashMC-Development/Suggestions#479]
**Describe the suggestion**
With the release of 8,2 and the availability of the Dynamax Band from NPC quests, the final reward of the gym (which is the Dynamax Band) has become redundant. It is much easier to complete the requirements for the NPC Quest for the Dynamax Band than it is to complete all 8 Player Gyms. This has caused less and less people to try and challenge the player gyms as there is much less of an incentive to complete them. 

I am suggesting for a change/remake/addition to the Player Gym rewards, most notably the 8th and final Player Gym reward. There could be a variety of rewards to choose from that may help increase the presence of Player Gyms and their importance in a server. While I am not sure on what exactly may constitute as a "fair" reward, I can list some individual reward ideas such as the following down below:

- Max Soup
- Max Mushrooms
- Crate Keys
- Papers (Similar to the ones from the skill rewards)
- Some sort of cosmetic
- Other difficult items to get in-game

**Which servers does this apply to?**
All Pixelmon Servers

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
We will be reviewing rewards at the same time as we review the gym structure - keeping this in mind for June 12th

**Comment by Rasgnarok** [comment]
Forwarded to the main ticket for eco changes, since it is related

**Comment by DiegoKek** [comment]
Max soup and max mushroom are very common, crate keys are indeed a good reward along with papers
cosmetics would be interesting but i dont know if it would be actually possible,
as for other rewards there arent many that would be balanced

**Comment by Rasgnarok** [comment]
Duplicate here, https://github.com/SmashMC-Development/Suggestions/issues/388

**Comment by Unitzero007** [comment]
I personally believe that one of the things that directly influence the kind of rewards the Player Gyms should have is linked to their value or worth (how challenging it is, how hard it is to obtain the badges, the amount of effort/grinding a player may need to go through to complete all the challenges, etc.). I had mentioned in my post that : "I am not sure on what exactly may constitute as a "fair" reward", these words tie in with my current sentiment on how it may be easier to judge what rewards to give the Player Gyms once we are able to assign some sort of value to the system as a whole.

So here I am requesting if it is possible to discuss the current state of affairs regarding the Player Gym system before we discuss what the rewards may be. Most discussions that we have over in the voice chats regarding the Player Gym systems and their respective rewards always end up devolving into a chat about what the purpose of the gyms are and who we are supposed to be catering towards. Knowing this, one of the most common topics we are unable to settle on is whether Player Gyms are meant to be a more casual, player-friendly experience, or if it was meant to be geared more towards the "competitive" player base, whom of which include players that are willing to learn the rules and grind for the Pokemon needed to counter the respective gyms).

Personally, I am on the side of the Player Gyms being an experience that leans more towards the "competitive" side of the player base. However, that does not necessarily mean I am against the idea of a more casual experience being implemented. Personally, I feel as if the server is somewhat similar to an MMORPG, wherein there are players who play the game for the Player vs Monsters (PvM/PvE) aspect and there are those who would rather play the game for the Player vs Player (PvP) aspect. I would recommend that instead of shifting the Player Gyms towards a more casual, player-friendly system, instead create more PvE aspects such as the projects that Mikirae is working on, the NPC Gyms, and the NPC House. 

All of these ideas, however, are coming from the perspective of a mere Gym Leader, I am not sure of the plans that are happening in the background or of the future of the server, but I hope what I have said may be of some use moving forward.

Though regardless of what I have stated, I can still provide a general list of ideas/items/rewards that I believe might be appropriate for the Player Gym Reward, though this was made without regard to the supposed value of the Player Gyms. Additionally, if the supposed system was to be geared towards more competitive players, I would suggest that the rewards be of some benefit to them and with respect to the metagame present within the warzone.

- Legendary/Non-Legendary IV Boost Max
- Legendary/Non-Legendary Shiny Converts
- Random/Specific Legendary/Pokemon
- Megastone Crate Keys (though my opinion of this is quite sour especially with the current meta of the warzone being filled to the brim of dynamax abusers because of how the system of 8.2 works)
- Pokedollars (maybe in larger amounts, especially when one realizes that the players beating the gyms are probably economically sound having used potentially Battle Perfect Pokemons when attempting to beat the leaders)
- Actual Physical Badges or something related to the progression system that the players can show off
- Rare Candies (the value of these have been notably diminished after the release of smash reacts)
- Items that are valuable and quite hard to get(these may include, Rusted Swords, Rusted Shields, Utility Umbrella, Terrain Extender, Red Orb, Blue Orb, DNA Splicers, Reins of Unity, Kubfu Banners, Azure Flutes,  etc.)
- Items that have some sort of Value to competitive Pokemon (Choice Items, Terrain Seeds, etc.)
- Access to previously inaccessible commands, preferably ones that are purely cosmetic (/nick, /pokecolor, etc)
- Something similar to the rewards from completing the pokedex such as more homes or a Title/Tag.

**Comment by Jarviboi** [comment]
I agree with this statement other than the fact that Charizard (maybe other servers too) doesn't have access to NPC quests so on Charizard there is still a lot of incentive to complete the player gyms.

**Comment by DiegoKek** [comment]
I personally believe a hard mode for gyms should be implemented, which would be more directed at the competitive players while the current gyms would be a normal mode for more casual players, each mode should give different rewards as one takes more skill and resources than the other, i also agree with the fact that the server is an mmorpg, but we lack certain features a mmorpg has like progression (outside of gyms) server quests, etc. implementing more progression by adding hard mode gyms would be great in my opnion

**Comment by Unitzero007** [comment]
> I agree with this statement other than the fact that Charizard (maybe other servers too) doesn't have access to NPC quests so on Charizard there is still a lot of incentive to complete the player gyms.

I wish that it was kept like this tbh, but all other servers aside from char have NPC quests enabled so its quite unfortunate

**Comment by Rasgnarok** [comment]
https://github.com/SmashMC-Development/Suggestions/issues/535
