### ISSUE TITLE
Able to tpa people to UltraSpace

### ISSUE THREAD

**Issue by Jumbleds** [SmashMC-Development/Suggestions#480]
Describe the Bug
When you /tpahere (username) in the overworld and go to ultraspace, they're able to teleport to you in ultraspace.

To Reproduce
1. /tpahere your friend in the overworld
2. Have them wait for you to go into ultraspace
3. Once you're in UltraSpace, tell them to accept the tpahere request and they'll be teleported into ultraspace where you are.

Servers with the Bug
Jirachi, and most likely all other servers

Expected behavior
The person in the overworld that is teleporting to ultraspace shouldn't be allowed to tpa to the person in ultraspace.

Screenshots
N/A

**Comment by HackuJacku** [comment]
Implemented on the reset
