### ISSUE TITLE
Warzone changes

### ISSUE THREAD

**Issue by AlphaRay01** [SmashMC-Development/Suggestions#481]
With the coming changes to warzone, I feel like the hot topic of rules should be adressed. Especially the rules regarding what is and whats not allowed in warzone battles.

First of all I would like to say that I recommend looking at standard rules in all battling tiers like the sleep clause/ohko clause/one of each species clause. Most of these rules would be appreciated by the general player base if I'm not mistaken, and others like the "One of each species" would have to be discussed or changed accordingly. 
Using a restricting format like National Dex OU is not the way to go in my opinion since warzone is meant to be end game content and is one of the only if not the only place to put good Uber tier legends to use. Banning these Uber tier legendaries from being used in warzone would remove the entire purpose of having/grinding for them.

This is what comes to mind at first glance about battling rules, if you have anything to add or any questions feel free to do so.

**Which servers does this apply to?**
All

**Additional context**
N/A

**Comment by Unitzero007** [comment]
I love the idea of adding sleep clause, but maybe the species clause can be restricted to just three pokemon? Though in AG you rarely even see teams of things like 6 arceus and if one is good enough that team is way more manageable then fighting a proper, well-built, AG team.

Also maybe ban evasion moves :)

**Comment by Rasgnarok** [comment]
Moving this to our main ticket for Warzone, I like the idea of A) rules displaying better, and B) reworking it to answer more competitive standards.
