### ISSUE TITLE
Confirm /warp warzone

### ISSUE THREAD

**Issue by KovanEmpire** [SmashMC-Development/Suggestions#482]
I think /warp warzone is a great idea, but I think a confirmation button to prevent accidental warps should be considered. Something similar to the buttons in chat to accept or deny a /tpa (though there doesnt have to be a "deny" option for warzone).

**Which servers does this apply to?**
All

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Added to the Master Warzone ticket. All of these suggestions will be taken into account when we work on Warzone. Thank you!
