### ISSUE TITLE
My List of WZ changes we need or should implement

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#483]
**Describe the suggestion**
WZ is why a lot of people came to smash so if you guys redo it we need to make it better, more fun, awesome, so here's my list of things that should stay, be added, removed.
#Warzone should keep the idea of steal from someone in battle but it the steal menu should change to also tell us the held item the pokemon has and skin as someone should bring a full team of Mewtwo's with one being mega, or one being shiny, there would be no way of finding out and same if its HA.
#Special pokemon skins shouldn't be found in wz unless they have a very very very rare change for example the AZ Florette spawns a lot in wz and I t think that should be nerfed and maybe you could make alter pokemon spawn very rarely like in the wild.
#WZ events should be added next update which should be like maybe wz Dynamax bosses like gmax bosses or legend bosses or mega bosses and they give nice rewards if u beat them like max mushrooms, mega stones, scrolls, z crystals depending on the boss, Legendary items(rusted sword/shield, reins of unity, DNA splicers, i.e). there can also be wz battle events where the battle format for wz changes once a day once a weak like (Double battle, uu only, OU unless) and the proper clauses will be added for the events when they happen. A WZ event we should add maybe is a wz ever all was on all servers combine for 24 hours and u can transfer a box of pokemon over and bring your rewards over after. A WZ event that should be added is maybe a drop party in wz. I think also in the next wz update is a new map for the servers that cant get a map that char and Darkrai so it's fair. Another WZ event could be a hunger games event like with only the pokemon u can catch in wz but in the end, u can keep the pokemon. Also WZ king of the hill.
#The WZ ship shouldn't let legends spawn on it at all.
#Add loot boxes in wz or supply drops.
#Dont added drowned pokemon from the drowned dimension to spawn in wz.
#Add a raid den or dens in the new wz where the Dynamax bosses will spawn.
#Prevent people from stalling in a pokemon battle
#A debug command for players if there in waiting in a wz battle and both have to agree to debug.
#A wz tournament like the tournament plugging but wz style and u get a crate if your the last one alive.
#WZ clans where u can make teams in wz and have a private chat for clans and you can make it so u have to be in this clan or u can be in several. and u cant steal from clan members if the leader sets it to that
#Lower UB spawns to be SUPER rare. 

That's all I can think off

**Which servers does this apply to**
ALL

**Comment by HackuJacku** [comment]
Added to the Master Warzone ticket. All of these suggestions will be taken into account when we work on Warzone. Thank you!
