### ISSUE TITLE
Suggestions for the Warzone Remake

### ISSUE THREAD

**Issue by Unitzero007** [SmashMC-Development/Suggestions#485]
**Describe the suggestion**
Here are some suggestions of what I want changed/added into the SmashMC Warzone

**Add a Team Preview**
Make it so that when you engage/ are engaged on by another person a team preview screen shows up where you are able to select a lead.  I am also okay with either the team preview that was shown in the tournament (wherein neither side could see their opponent's pokemon, but could still choose a lead), or the team preview present in the pixelmon gyms (wherein both sides could see their respective opponent's pokemon and choose a lead accordingly). I believe this will add an extra layer of skill to warzone.

**Add certain clauses**
I am unsure of the current implementation of the Smogon clauses in Warzone, though I do believe in adding the following:
- Sleep Clause
- OHKO Clause
- Endless Battle Clause (Ban on the **combination** of Leppa Berry + Recycle/Harvest + Any berry regaining skill + Heal Pulse + Recovery moves like Slack Off or Recover)

Both of the mechanics covered by these clauses make the game way more uncompetitive and RNG based. 

Also ban the ability No Guard when it is used in conjunction with an OHKO move (e.g. No Guard Fissure Machamp). There should currently not be any Pokemon that has that ability and can an OHKO move,  most of the Pokemon that probably do, are transferred from the virtual console games and are always 100% guaranteed to have their Hidden Ability (in the main series games).

**Ban building blocks of any kind**
Block Glitching...

**The issue with Dynamax and Mega**
As of writing this suggestion, in the current version of the Pixelmon Mod, the Dynamax Band completely cancels out Mega Evolutions in player vs player battling (you are unable to use a mega if the opponent has a Dynamax Band equipped). This means that the usage of Mega-Evolved Pokemon in warzone is completely unviable, especially with the sheer amount of people who have the Dynamax Band equipped due to the NPC Quest system.
I am not exactly sure on what to do about this topic in that regard, as asking for a ban on the Dynamax mechanic may be too much. I am just disappointed in how Mega-Evolutions and Z moves, which are such huge components of the current National Dex Meta (across all tiers), are unable to be used. Maybe it's possible to have days where warzone allows Mega-Evolutions and days where Dynamax is allowed, I don't really have any ideas regarding that, just wanted to point it out.

Also Dynamax + choice items are also bugged, You're not supposed to stay choice locked when you Dynamax a mon (the mechanic only works normally when your first move after being sent out is a Max Move, but if your first move is a normal move that gets choice locked and you proceed to Dynamax afterwards it gets locked in to that move).
 
**Which servers does this apply to?**
All Pixelmon Servers

**Additional context**
N/A

**Comment by arjun-gangwar** [comment]
Really nice insight.

**Comment by HackuJacku** [comment]
Added to the Master Warzone ticket. All of these suggestions will be taken into account when we work on Warzone. Thank you!
