### ISSUE TITLE
Warzone idea

### ISSUE THREAD

**Issue by xTrentx82** [SmashMC-Development/Suggestions#486]
I would like it to be where you have to confirm the battle with another trainer instead of being forced into it. Players that have been there a while are bullying newer ones taking their Pokémon they grinded just to get in there.

Jirachi 

Example I grinded a team out and took it in only to be for my legendary to be taken from me so I had to grind and use my money just to get back in and it happened again.

**Comment by HackuJacku** [comment]
We won't be implementing this because Warzone (high spawn rates for legendaries, UBs, shinies, ETC) need to have some form of risk. The risk is that players can steal your Pixelmon. By removing this, the Warzone will no longer be as balanced.
