### ISSUE TITLE
Add the ability to create the new legend items

### ISSUE THREAD

**Issue by KingofTheThicc** [SmashMC-Development/Suggestions#488]
**Describe the suggestion**
Since you can only get rusted sword, reins of unity, etc from either buying the pokemon from the store or getting lucky with a vote party it would be nice to be able to craft the new legend items for those caught in the warzone. It is already a mechanic as it is on other Pixelmon servers, and I feel it would be a nice addition.
**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.
All servers
**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by DragonBallBreakersRandomizer** [comment]
U dont get the items when u buy the pokemon in the online shop and even tho this seems like a good idea u gotta think of the rareity of  the item and how u wanna preserve it, Also the crafting thing is the pixelmon mod and not smash so if u want there to be a crafting recipe u gotta ask the pixelmon devs them selfs

**Comment by Rasgnarok** [comment]
Forwarded to our eco ticket, though it is correct that crafting is more of a suggestion for PixelmonMod itself. We have forums for suggestions, I recommend taking a look: https://pixelmonmod.com/viewforum.php?f=146
