### ISSUE TITLE
Make an Elite Four+Champion that are universal to the server not to each server.

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#49]

**Comment by Mikirae** [comment]
Is this saying to have Elite Four and Champions that can manage their gyms on every server? Because I can't imagine this would be a very effective method unfortunately.

**Comment by Lun17** [comment]
I believe player was trying to say to make a League with e4 that is
accessible only for players that already beat the previous 8 player gyms in
their servers

Il mer 19 mag 2021, 02:41 Mikirae ***@***.***> ha scritto:

**Comment by Mikirae** [comment]
Ah, that's something that we're looking at when we get enough gym leaders to accommodate all of the gyms, I believe!

**Comment by HackuJacku** [comment]
Already on the roadmap for the future.
