### ISSUE TITLE
New skins Idea

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#490]
**Describe the suggestion**
A skin for a couple of the new legends like a crate for skins that could be uniqe
Regidraco = look like a gaster blaster from undertale (search it up they look the same)
Regileki = A Metal ball with wires coming out or and octopus,
Calryex , Look like a galdeator (same with the horse)
Zacian, A real like dog holding a bone
Zamazenta, Idk a husky
Mewtwo= Shadow mewtwo from Pokemon dx (same with mega X)
Mewtwo = blue like cooler from dbz
Kyogre = A real-life whale colours
Groudon = God Zilla

There could be more skins but these r some ideas I had

**Which servers does this apply to?**
All

**Additional context**
Their other forms have the skins to and stuff.

**Comment by Rasgnarok** [comment]
Much like all the other 'more skins' tickets, we can absolutely do them - we just have to make sure not to overdo it. I am tagging in Hacko, since he takes care of cosmetics.
