### ISSUE TITLE
Faster Tree Decay

### ISSUE THREAD

**Issue by whitesaber31** [SmashMC-Development/Suggestions#493]
**Describe the suggestion**
A simple addition, make leaves decay faster in pixelmon servers. Since sometimes leaves decay way slower than we can chop. Making lots of flying leaves that's bothering the new sapling to grow. Meanwhile people don't make tree farms in pixelmon except for builder. So I don't think it'll be overpowering.

**Which servers does this apply to?**
pixelmon server

**Additional context**
'N/A'.

**Comment by Mikirae** [comment]
Implemented :) Thank you!
