### ISSUE TITLE
WZ suggest part 2 (with friends)

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#494]
**Describe the suggestion**
A list of new WZ stuff my friends and I wanted to add

- Add Dyanmax bosses that drop max mushroom and dynamx candies if u bet them, Also u can fight the boss solo or up 2 4 people.-(Omniking)

- Add timers to random pokemon battles so people can't stall in battle (except legendaries)-(Darkassassin)

- Add an option to either steal pokemon or money.-(Darkassassin)

-Add Warzone game modes and tournaments to wz. - (darkassassin)

-WZ quest -(Crownless)

-  Hard NPC in wz (Darkassassin)

- Battle tower in wz or a tower where u battle them and u can evolve cubfu at the top (Darkassassin)

- Make it so u can select where u safe place like home or spawn (Cat_Tip)

- Make a map where the map can be Very hudge but there me a map with dots but no names to show you where people are in wz (Cat_Tip, Darkassassin)

- Forced into a battle in wz if your close to them (Darkassassin)

-Add a WZ list like a clan system/gang/friends, and your group can choose a glow for your group and you can wear something to make your group stand out like flags on our heads. (Darkassassin,Cat_Tip)

-Add biomes in wz and make them separately noticeably. (Cat_Tip)

-Make a center area in each biome were groups can take over for points and builds such as that(Cat_Tip)

**Which servers does this apply to?**
all

**Additional context**
N/A'.

**Comment by Mikirae** [comment]
Just going to comment on a few of these.
I like timers, stealing money, NPC (already had this in mind).

Quests are already going to be a thing in Warzone I believe

The map one I'm not sure would be helpful unless you have it in your hand like on Hypixel Murder Mystery. 

Battle tower just sounds like something not for Warzone.

Biomes wouldn't work because the map is already made.

**Comment by DragonBallBreakersRandomizer** [comment]
The map could be in your off-hand

I agree with battle tower

Biomes well that makes sense

**Comment by Rasgnarok** [comment]
Moving this into our master ticket for Warzone, so we can redirect all accepted suggestions into that.
