### ISSUE TITLE
Custom WZ music

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#497]
**Describe the suggestion**
Add Custom Battle Music For Warzone

**Which servers does this apply to?**
All

**Additional context**
'N/A'.

**Comment by Mikirae** [comment]
Would have to check into this to see what's possible honestly

**Comment by Rasgnarok** [comment]
It should technically be possible with Pixelmon's new music blocks, but a dev would be able to explain how to rig it better.
