### ISSUE TITLE
Calyrex's Reins being dropped in legendary pokémon paper

### ISSUE THREAD

**Issue by Zekalfra** [SmashMC-Development/Suggestions#498]
Hello staff,

So basically, you can get the calyrex's reins by getting a legendary pokémon paper and get a calyrex. 
In this situation the server becomes more pay 2 win instead of a grinding system. In my opinion these reins and other items like that should be obtained by doing something that requires some effort, like a quest.

Thanks,
Zekalfra

**Comment by Mikirae** [comment]
Well we're going to be putting these and other legendary items into something else that anyone can do. They used to actually not be included on the Pokemon but a lot of people, including non-donors complained that it was making it so there weren't enough items for the legends on the server and things.
