### ISSUE TITLE
Galexy Crate Of All OU Mons On national Dex

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#499]
**Describe the suggestion**
A Galexy Crate of all ou pokemons national dex smogon on showdown

**Which servers does this apply to?**
All

**Additional context**
maybe if the ou mon is galaxy and needs to be HA it will be unbreedable maybe?

**Comment by Mikirae** [comment]
Well, if we were to make this HAs would be exceptionally rare. And we'd need to actually get Galaxy Mons made for OU mons as most of the ones that we have now are just legendaries. We'll think on it :)

**Comment by HackuJacku** [comment]
The Galaxy crate will remain Legendaries and Ultra Beasts. We want to add more custom textures so please feel free to suggest some Pokémon/themes.
