### ISSUE TITLE
Increase time on smash trivia

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#50]
**Describe the suggestion**
increase the time between smash trivia, the chat is way too flooded if it happens so often

**Which servers does this apply to?**
All

**Comment by Mikirae** [comment]
I think that this needs to be adjusted on a per-server basis as certain servers will have a more flooded chat with more players on.

**Comment by HackuJacku** [comment]
Does this still need to occur?

**Comment by HackuJacku** [comment]
I'll be closing this due to Lun not being the original author - copied from Discord. If it's still valid, please create a new suggestion.
