### ISSUE TITLE
Stop pokemon's griefing

### ISSUE THREAD

**Issue by whitesaber31** [SmashMC-Development/Suggestions#501]
**Describe the suggestion**
I'm not sure it is possible or not. but sometimes it is annoying when spawned pokemons tramples your field or opens up a pressure plate. If its possible, can it be blocked? so they don't unintentionally griefed tilled land?

**Which servers does this apply to?**
Pixelmon server

**Additional context**
Flying pokemons is the worst offender. like pidove or vivillon, since they need to jump around and basically trampling any field they fly through

**Comment by Mikirae** [comment]
Seems like a decent QOL issue but I don't know if denying block damage thingy from Pixelmon would hurt anything else.

**Comment by Rasgnarok** [comment]
I think I actually have an idea of how to go about this, I'll look it over the weekend.

**Comment by Rasgnarok** [comment]
GriefDefender isn't actually picking up the trampling source - I'll have to see if this can be prevented world-wide, server-side.

**Comment by HackuJacku** [comment]
Implemented on the reset
