### ISSUE TITLE
Add Gen 8. Legendary held items to the item shop

### ISSUE THREAD

**Issue by mnky-frt** [SmashMC-Development/Suggestions#503]
**Describe the suggestion**
Possibly add the held items for legendaries to the item shop. Like the rusted sword/shield for the wolves or the scrolls for urshifu etc...

**Which servers does this apply to?**
All servers

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Shops will be revised to add Gen 8 additions, more details on what those items/blocks coming soon (tm).

**Comment by DragonBallBreakersRandomizer** [comment]
Dont added the rusted sword and shield to shop please. same with reins of unity to preserve unity

**Comment by Rasgnarok** [comment]
Forwarded to master ticket.
