### ISSUE TITLE
Scroll of water/dark

### ISSUE THREAD

**Issue by Firemelon66** [SmashMC-Development/Suggestions#505]
**Describe the suggestion**
Its about to put the scrolls of water/dark into the :warp shrines and maybe you have to pay to use cause its kinda impossible to get the scrolls and normally you can evolve them somewhere in the wild anyways

**Which servers does this apply to?**
For all servers 
**Additional context* it would let people evolve their kubfus to urshifu/rapidstrike form

**Comment by HackuJacku** [comment]
We won't be adding it to `/warp shrines`. We'll be adding a unique, custom way of getting it.

**Comment by Firemelon66** [comment]
like when you guys gonna do that?
