### ISSUE TITLE
Add Charizards WZ map to other Server

### ISSUE THREAD

**Issue by Spigii** [SmashMC-Development/Suggestions#508]
**Describe the suggestion**
Add Charizards WZ map to the other server

**Which servers does this apply to?**
All

**Additional context**
Chrizards Map so big, rest so smol

**Comment by HackuJacku** [comment]
The Charizard Warzone build causes the most issues out of all the builds. Warzone will be getting overhauled in the next coming weeks both in terms of the plugin and builds.
