### ISSUE TITLE
Add a new minigame

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#509]
**Describe the suggestion**
Add a hide and seek minigame like either as blocks or as pokemon hiding among another pokemon.

**Which servers does this apply to?**
All

**Additional context**
The pokemon on you can move around (same with NPC pokemon)

**Comment by HackuJacku** [comment]
Yes

**Comment by Rasgnarok** [comment]
Very related to #511, it could be divided into different gamemodes.
