### ISSUE TITLE
Minigame Murder Mystery

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#511]
**Describe the suggestion**
Add a murder mystery game to the server but the imposter turns into ditto if they win. and the pokemon everyone can pick what pokemon they wanna be like Charmander, Amongus (especially among us skin), Shiny, etc

**Which servers does this apply to?**
All.

**Additional context**
N/A.

**Comment by Rasgnarok** [comment]
I've seen a mock concept of this, where two teams, Trainers vs Pokemon challenge and defeat eachother before all Trainers catch the Pokemon-disguised players. It's a really cool concept, and tons of fun. Even funnier if normal Pokemon spawn among the Pokedisguised players. 

It might not be implemented out of the first interation of Minigames, but I'll keep this open once we do, and add it to a master ticket for Minigames, so we don't forget!
