### ISSUE TITLE
Quest Idea For Kubfu

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#512]
**Describe the suggestion**
So I hear about a custom quest so I have an idea for cubfu.
For Cubfu you can evolve it but like at a custom battle tower where u gotta beat 10 trainers with only your kubfu, then u beat the boss trainer kubfu to kubfu. Then after your win, your kubfu will evolve into an ursifu.

**Which servers does this apply to?**
All.

**Additional context**
There's to towers and they represent which one u want like in the games.

**Comment by Rasgnarok** [comment]
We are currently working on a battle-tower'ish feature called Dungeons, which could answer your suggestion actually. It might be a nicer, more organic way of evolving your Cubfu. I either way really like the integration of a challenge.

Pixelmon has trainers spawn in large, Japanese-themed towers found in new worlds after 8.2. At the top of the tower is the required scroll to evolve your Cubfu. This idea would replicate the intended mechanic.

Thoughts, @Mikirae ?

**Comment by Mikirae** [comment]
I'm definitely down to add it as a reward for the upcoming one :)

**Comment by HackuJacku** [comment]
Implemented on the reset
