### ISSUE TITLE
bingo card bug

### ISSUE THREAD

**Issue by LeNoope** [SmashMC-Development/Suggestions#516]
**Describe the suggestion**
i just completed my bingo card and clicked on the claim reward and i didnt get anything
**Which servers does this apply to?**
Deoxys

https://user-images.githubusercontent.com/84600550/120932426-94260300-c6ed-11eb-8b6c-2ca1dc5a8559.mp4

**Comment by LeNoope** [comment]
my ign is Le_Nope

**Comment by DragonBallBreakersRandomizer** [comment]
This is suggestions, Report this in Bugs and issues: https://github.com/SmashMC-Development/Bugs-and-Issues/issues

**Comment by HackuJacku** [comment]
Fixed from next reboot. Next time please post this in the correct place and use the format.
