### ISSUE TITLE
Grookey spawn

### ISSUE THREAD

**Issue by Davideheh** [SmashMC-Development/Suggestions#520]
**Describe the suggestion**
Please, make the Grookey spawn from the particles that sometimes pop up from the ground.

**Which servers does this apply to?**
All the servers.

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Will discuss this with the admins.

**Comment by AmsterDaan** [comment]
I feel adding this will ruin the rarity of one of the best and but looked after HAs, so i don't think changing the meta to just make the rarest HA common is a good idea

**Comment by AmsterDaan** [comment]
so sorry we won't be making this change.
