### ISSUE TITLE
Tournaments

### ISSUE THREAD

**Issue by DiegoKek** [SmashMC-Development/Suggestions#525]
Add weekly/monthly tournaments to the server being played in multiple formats (OU, UU, RU, NU, PU, ZU, Monotype)

All

PokeSmash is a very competitive server (player-wise) but it doesn't have many competitive aspects other than the warzone (which is AG) i believe having small tournaments every once in a while would benefit the competitive side a lot

**Comment by Sadkeemstar112** [comment]
Sounds good

**Comment by HackuJacku** [comment]
Same as #569
