### ISSUE TITLE
Items me and my friends should be added to the shop

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#526]
**Describe the suggestion**
Items me and my friends think it should be added to the shop

- Rare Candies for 2000 apiece (nukez)
- Cobwebs (Crownless)
- Battle items i.e focus sashes, wide lens, air ballons etc. (Nukez)
- Terracotta (Cat_Tip)
- Concrete (all colours) (Crownless)
- Beast Balls (Crownless)
- dispensers (Fakoz)
- Ice and packed ice (Cat_Tip)
- Sell all the ores (Cat_Tip)

**Which servers does this apply to?**
All.

**Additional context**
'N/A'.

**Comment by HackuJacku** [comment]
Forwarding to main ticket on economy.
