### ISSUE TITLE
GitHubs

### ISSUE THREAD

**Issue by PescadoMan** [SmashMC-Development/Suggestions#529]
**Describe the suggestion**
Make Bug and Issues area on GitHubs private so only op user and staff can see them. For example, if someone reports a dupe glitch the whole server can see it. Though you should keep suggestions public to get feedback from others.

**Which servers does this apply to?**
Discord/GitHubs

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Github doesn't support privated tickets, sadly. See https://github.com/isaacs/github/issues/37 for further information. For security issues, we sadly will have to relay on external forums or forms.
