### ISSUE TITLE
More PC Space

### ISSUE THREAD

**Issue by HenchGingerBloke** [SmashMC-Development/Suggestions#536]
I think we should have more space in our PC as people like me who are bad at getting rid of stuff are bad at getting rid of stuff and have the problem of things getting just removed from existence cause their PC is full up, You can implement this by either way of ranks, The more you dex the more space you get from Trainer-Master this will help a lot and everyone will enjoy it 🗡️

**Comment by DragonBallBreakersRandomizer** [comment]
This is a mod thing so I dont think smash can do much about it.

**Comment by HackuJacku** [comment]
Even though we're able to do this, we've chosen not to as it would require code deemed as 'hacky' and viewed as potentially unstable/not safe, opening the risk of data loss. We'll look into potentially increasing the number of boxes in the PC but not ranks having additional boxes.

In the future, please also follow the template provided.
