### ISSUE TITLE
Progression

### ISSUE THREAD

**Issue by DiegoKek** [SmashMC-Development/Suggestions#537]
**Describe the suggestion**
I believe more forms of quests, objectives, etc. should be added, recently ive been looking at what there is to do on the server once you reach the point where you have a decent amount of money and items and ive found little to nothing to do in the endgame, endgame players probably have already finished gyms and are close to completong the pokedex and once they do, there isnt anything other than farming for cash endlessly, warzone can be fun but once you play it for a few hours it gets useless and boring, and for more casual players there is nothing to do (except breeding endlessly) as all of the endgame content is competitive and this has made the game pointless to me, the only reason i get on every now and then is to help people and to talk in chat as there isnt anywhere else i need to go or anything i need to do, even though i love this server from the bottom of my heart, it has become boring to actually play.

**Which servers does this apply to?**
Pixelmon (all)

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Implemented on the reset
