### ISSUE TITLE
For Future Breeding Skill

### ISSUE THREAD

**Issue by whitesaber31** [SmashMC-Development/Suggestions#538]
**Describe the suggestion**
I heard that breeding skill will come soon in the future. As a breeder, I would like to suggest what perks that would be interesting:
1. Better chance to get higher/the same IV as the parents
2. Better chance to get shiny from breeding 

**Which servers does this apply to?**
Pixelmon Server

**Additional context**
for number 2, is because at level 100+ catching shiny will spawn more often nearby you, so I'm thinking why not the same with breeding?

**Comment by DragonBallBreakersRandomizer** [comment]
That's nice maybe at lv 200 the chance for eggs to be shiny goes up? Also another skill;l could be double hatching skill

**Comment by HackuJacku** [comment]
Implemented on the reset
