### ISSUE TITLE
Fix and improve /warp boss

### ISSUE THREAD

**Issue by whitesaber31** [SmashMC-Development/Suggestions#539]
**Describe the suggestion**
since the new update, boss tower spawn bosses at extremely low pace, to the point that barely anyone hunts there anymore. making prices for the drops became unstable or even skyrocket. I hope that its spawn rate would be fixed like before or even better. Also, it would be a lot more fun to add more levels and elements, or more varieties of the enemies that will pop out on the boss towers.

**Which servers does this apply to?**
pixelmon servers

**Additional context**
'N/A'.

**Comment by HackuJacku** [comment]
No rates have changed. They're intended to be low so they're balanced and players don't constantly AFK there to farm money - something we don't like.
