### ISSUE TITLE
for new players i wish there was some form of thing like an intro

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#54]
Make an intro or a tutorial so new players can get to know everything without having to ask to staff/players

**Comment by Mikirae** [comment]
We have considered this, but I think that a better option could be a /intro command that tells people various common commands.

**Comment by HackuJacku** [comment]
The `/menu` will be getting overhauled in the future. One of the changes I'd want made is along of the lines of this. I will keep this open until then.

**Comment by HackuJacku** [comment]
Added to the SmashMenu master ticket.
