### ISSUE TITLE
Ranked Tier Warzone

### ISSUE THREAD

**Issue by Jumbleds** [SmashMC-Development/Suggestions#541]
**Describe the suggestion**
Multiple warzones for different tiers of battling (AG, OU, UU, RU, NU and etc) for the players that like only playing specific tiers of battle.

**Which servers does this apply to?**
All

**Additional context**
N/A

**Comment by HackuJacku** [comment]
We won't be doing this but the next version of Warzone should make teams more balanced and stop individuals 'controlling' the Warzone.
