### ISSUE TITLE
/Glow in survival shop

### ISSUE THREAD

**Issue by Archie4690** [SmashMC-Development/Suggestions#545]
I think it would be nice to have the ability to be able to purchase glow colours in the online shop or i think it would be nice to have them to be progressively earnt throughout the ingame ranks like how it is in pixelmon.

Survival

I am aware that this is already a buyable thing and that is comes with hexcolours but i think that being able to buy certain glows which are the standard minecraft colours would be a cool thing that many people would buy due to not everyone being able to and/or not wanting to spend $100 on a rank.

**Comment by jahangir6969** [comment]
This is not been added. It will only stay as a top rank perk. I do not want to give it out to all ranks or give it within the game. They may be a special event where you can get it but will not be added as a separate thing.
