### ISSUE TITLE
Disable skills (specifically first-aid) in warzone

### ISSUE THREAD

**Issue by ujmki10** [SmashMC-Development/Suggestions#546]
With the ability to force people into waiting glitches it becomes impossible to enter to beat someone without the skills. One could say well just go get the skill but it does damage to the newer players that wanna grind out a team and go straight into warzone. These skills are amazing QoL features to have in the game but they have no place for warzone.

**Comment by Mikirae** [comment]
The ability to disable skills in a certain world will come in an update soon, so stay tuned for that! :)
