### ISSUE TITLE
Way to dispose items easier on survival

### ISSUE THREAD

**Issue by Awlk** [SmashMC-Development/Suggestions#548]
**Describe the suggestion**
A command that gives you a menu where you can trow items in which wil be destroyed once you close this same menu

**Which servers does this apply to?**
Menu

**Additional context**
I have also seen this in another way. Instead a command you right click a sign to get the same menu to dispose items in

**Comment by Awlk** [comment]
Not sure why I put "menu" there should be survival

**Comment by Rasgnarok** [comment]
What you are talking about is referred to as 'trash UI'. Should be easy on Vanilla thanks to Spigot, but that's a @jahangir6969 question. As for Pixelmon, I believe we already have /trash.

**Comment by Awlk** [comment]
We already have a command link that just needs adding for ranks

**Comment by jahangir6969** [comment]
Added to all rank.
