### ISSUE TITLE
Remove gts tax

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Suggestions#549]
**Describe the suggestion**
Remove the gts tax. This should be removed because it has made gts become very dead is almost not even used as much from what I have noticed. Instead of people using the gts they just use /pay and /gift now to sell things which basically makes the whole gts plugin useless. We shouldn't be taxed when we don't even need the gts to sell things as there are work arounds like what I said with /pay and /gift. If this was to try and fix eco problems it's not working and not the right way to try and fix them by taxing players. It would be nice to be able to use it and not be charged and also see what other people are selling because more people would use it if the gts tax wasn't a thing. 

**Which servers does this apply to?**
All pixelmon servers

**Comment by Skeletonio000** [comment]
i think this suggestion is good

**Comment by Rasgnarok** [comment]
GTS' tax is part of a larger economy debate, one which I recommend weighing in on, https://github.com/SmashMC-Development/Suggestions/issues/522. Closing this one as it's technically a duplicate.
