### ISSUE TITLE
Shinies are rare

### ISSUE THREAD

**Issue by Jumbleds** [SmashMC-Development/Suggestions#550]
**Describe the suggestion**
Make shiny pokemon alot more rare to find so that they're actually worth something in game. Because at the current state, it is so common to find a shiny pokemon in warzone. So if they were non-existent or just not in warzone altogether, maybe they would be worth more than they're currently.

**Which servers does this apply to?**
All

**Additional context**
N/A

**Comment by HackuJacku** [comment]
We have significance reduced the Shiny spawn rate of Warzone. This is something we wish to do moving forward but there is little that we currently can do but we have plans for the future.
