### ISSUE TITLE
Kits survival 

### ISSUE THREAD

**Issue by 19Rambo99** [SmashMC-Development/Suggestions#552]
**Describe the suggestion**
A clear and concise description of what you want to happen:: I would like a time reduce on the kits emperor 7 days warlord 3 days and all below that 1 day 20 days is a bit heavy in my opinion:D all love from rambo1654 <3

**Which servers does this apply to?
Survival

**Comment by jahangir6969** [comment]
No way. That Will make kits way too overpowered. I will nerf the days to 17 days for all kits but I will not be doing any lower then that.

**Comment by 19Rambo99** [comment]
> No way. That Will make kite way too overpowered. I will nerf the days to 17 days for all kits but I will not be doing any lower then that.



> No way. That Will make kite way too overpowered. I will nerf the days to 17 days for all kits but I will not be doing any lower then that.

17days for gatherer hunter  and warrior?! They good but not overpowered warlord and emperor is op yes i

**Comment by jahangir6969** [comment]
Good point I will change them kits to 14 days but it not going any lower then 2 weeks.
