### ISSUE TITLE
Concers About Dynamax And Game balance

### ISSUE THREAD

**Issue by Painyboi** [SmashMC-Development/Suggestions#553]
**Describe the suggestion**

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by Rasgnarok** [comment]
Closing, duplicate.

**Comment by Rasgnarok** [comment]
https://github.com/SmashMC-Development/Suggestions/issues/554
