### ISSUE TITLE
Concers About Dynamax And Game Balance

### ISSUE THREAD

**Issue by Painyboi** [SmashMC-Development/Suggestions#554]
**Describe the suggestion**
In my opinion should dynamax be nerfed, bcs when u fight someone with the "Dynamax Band" and if u are using a mega bracelet, u cant mega no matter what. if they fight you, u cant mega. if u fight them, u cant mega. i have lost so many battles bcs of this dynamax band
**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.
I usually play on Palkia
**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.
N/A

**Comment by Rasgnarok** [comment]
This is a Pixelmon behaviour, and not one we can change, sadly. It's a pending suggestion for Pixelmon itself at the moment.
