### ISSUE TITLE
Suggestion for next warzone

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Suggestions#555]
**Describe the suggestion**
So I’ve seen and assuming you all have seen players are very unhappy currently with the custom textured legends being removed from Warzone. I think it would be a good  idea to create new custom textured legendaries you can only find in warzone and can’t buy from crates. This could replace the shadow and galaxy legends that were taken by adding some cool new custom ones. I think this would be a great replacement as these would be exclusive to warzone and shouldn’t be able to be bought in crates. 

**Which servers does this apply to?**
Pixelmon servers

**Comment by DragonBallBreakersRandomizer** [comment]
Golden bois skins

**Comment by Rasgnarok** [comment]
Yes, not everyone likes the added value for the textures that used to spawn freely in Warzone. I don't mind the idea of Warzone-exclusive textures, on a really, rare basis, however, this could significantly raise the size of the modpack, which not everyone can load sucessfully already. Keeping this ticket up, it's a good idea.

**Comment by HackuJacku** [comment]
Implemented on the reset
