### ISSUE TITLE
Re-playable multiplayer dungeon

### ISSUE THREAD

**Issue by JaggyL** [SmashMC-Development/Suggestions#559]
**Describe the suggestion**

I think the idea of a low income 2-4 multiplayer replayable dungeon would be a lot of fun, the rewards could be nerfed in comparison to the single player 1 attempt a day dungeons. I think this would give a different aspect to the game as most of the content is fighting other players instead of group content which could be fun. 

(While I’m here I’d Also like to say although the dungeon is fun the rewards seem to be poor, is there any significant low odds rewards? I’ve played every day since release and I’m averaging 3-6k value for 20 mins, mostly low amounts of cash and pokeballs. This doesn’t feel appropriate or rewarding to me as it basically requires a battle ready ou team to play and most of us who have that available won’t care to play for 32 ultra balls and 3k cash. My latest run today literally only gave 32 ultra balls and I’m confident I can make more than that from scratch in that time if I needed to.)

**Additional context**

Not really although I like the other suggestion of wz exclusive textured legends, warzone activity is  dropping a lot and most people bring throws anyway which is the biggest warzone problem imo, 0 risk for 0 reward currently.

**Comment by HackuJacku** [comment]
As Miki said when the first dungeon was released, we have plans to add more and are working on more. The first dungeon is intended to be an easy, starting-game one for new players. It's not intended to be for the better players, the harder dungeons will be.

Please see #563 about team based dungeons.
