### ISSUE TITLE
Allow users to set their price in GTS rather than there being a minimum

### ISSUE THREAD

**Issue by mnky-frt** [SmashMC-Development/Suggestions#561]
**Describe the suggestion**
As a breeder, I feel like some of the minimum prices for pokemon are a little too high. For instance, if I want to sell a bp Joltik, the GTS says I have to sell it for 25k. However, in my mind and others, a bp Joltik really isn't worth that much. So I try to sell it any way but no one buys it because the price is too high. At this point I've tried auctioning stuff at prices I feel are more suitable to the pokemon but I can only auction something every so often.

From what I've heard the server I play on (Palkia) is one of the poorest servers. So this minimum price on the GTS hurts us even more because it is harder to afford. I've also noticed an influx of new players joining our server. I'm not sure if this applies to all server but in Palkia I have noticed more and more new people every day. Overall, it is very hard to sell things and very hard for players to afford things with this minimum price in GTS.

With all this in mind, I am suggesting that the user should be able to lower the minimum price for a pokemon on GTS if they so please. If I want to sell some bp pokemon for less than 25k, it should prompt me with a warning or something that ensures that this is the price I want to sell it at. This would help our economy and new/poorer players be able to afford more things than they would not be able to before.

**Which servers does this apply to?**
Palkia, but all servers as well.

**Additional context**
N/A

**Comment by mnky-frt** [comment]
hey just a reminder this is still opened lmaoooooooo

**Comment by HackuJacku** [comment]
Implemented to a degree on the reset
