### ISSUE TITLE
Gym reward idea

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#562]
**Describe the suggestion**
For the gyms, I have an idea for rewards:  Rainbow glow that either changes colour every 3 seconds or a rainbow wave, Mythic key, A special item to wear that can old be achieved when u beat em all like a cloak.

**Which servers does this apply to?**
All.

**Additional context**
N/A'.

**Comment by HackuJacku** [comment]
Implemented to a degree on the reset
