### ISSUE TITLE
Dungeon idea

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#563]
**Describe the suggestion**
A dungeon where only a party of 4 can do it

**Which servers does this apply to?**
All.

**Additional context**
The final boss can be a Dynamax raid on a dyana pokemon or maybe a gmax pokemon and it switches every time.

**Comment by HackuJacku** [comment]
Would require a full re-write of Dungeons. Won't be done any time soon but potentially might in the far future? Already known to the dev though
