### ISSUE TITLE
Idea for all spawns and wzs

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#565]
**Describe the suggestion**
For the new wz their should be a giant statue of the pokemon for the server it represents, And same in wz and the wz leaderbored is on the statue

**Which servers does this apply to?**
ALL.

**Additional context**
maybe the mons can hold a sign or wooden plank with the leaderbored.

**Comment by HackuJacku** [comment]
If we were to do this, we won't add statues due to the amount of issues caused in the future.
