### ISSUE TITLE
Have a weekly/biweekly tiered tournament for players to partipate in

### ISSUE THREAD

**Issue by mnky-frt** [SmashMC-Development/Suggestions#569]
**Describe the suggestion**
Kind of like how we had the world cup every week in the national dex tier, I think we should do something like this again only local to the server not all of Smash MC

So every week (or every other week) there will be an announcement saying this week's tournament will be OU, UU, Ubers, etc... and players will have time to prepare for the tournament and participate. 

Just kind of gives players incentive to try out other pokemon in different tiers instead of only having warzone (anything goes) to fight in

**Which servers does this apply to?**
All

**Additional context**
N/A

**Comment by mnky-frt** [comment]
Also if possible, for winning the tournament we could get like an epic key or something so players have more of a reason to try and compete

**Comment by DragonBallBreakersRandomizer** [comment]
maybe mythic if its weekly

**Comment by mnky-frt** [comment]
so yall gonna respond or

**Comment by HackuJacku** [comment]
We sadly won't be implementing this
