### ISSUE TITLE
Add Destiny Knots to /mart

### ISSUE THREAD

**Issue by iiAse** [SmashMC-Development/Suggestions#570]
Idk about other servers but on mew theres a big shortage on destiny knots, all the breeders are way behind on them and everyone would be happy to see them added to the mart. Although they are in timeshop everyone prefers to buy a mball instead, and theres mor demand than supply of them. Im talking for a lot of breeders when i say, adding them to mart would be amazing and would help improve this great server.

**Comment by HackuJacku** [comment]
Might be on the list but we've been working on ways to overhaul the shop without it being OP.
