### ISSUE TITLE
GTS upgrade suggestion

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#572]
**Describe the suggestion**
The new gts is great and all but here's 2 things that need 2 be added
1. Show moves
2. No taxes

**Which servers does this apply to?**
All.

**Additional context**
N/A'.

**Comment by HackuJacku** [comment]
Moves will be added. The tax will remain, as we have said multiple times, but the implementation will change in the future.
