### ISSUE TITLE
WZ suggestion 

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#573]
**Describe the suggestion**
For the new wz I think this should be added because this is an issue if people are scared of you. In wz they can see who online with tab, and people can see if the person their scared of hops on in chat. The new wz I wanna recommend a way for  these people to not see the chat and tab unless they leave wz, then it pops back up

**Which servers does this apply to?**
All

**Additional context**
 'N/A'.

**Comment by HackuJacku** [comment]
Sadly this is not possible.
