### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by galactic4204315** [SmashMC-Development/Suggestions#576]
So i was thinking that the urshifu scrolls are dummy rare for multiple reasons:

1. We dont have the towers spawn.
2. The spawns in boss tower got lowered.

I was thinking that we could add the scrolls to ./warp mart the same way the solarizers and dna splicers are. Could make them a high price like the other merging items to keep then rare but not as rare as they are at the minute.

Not sure how if this is the same on other servers but in giratina no one has water scroll or dark scroll.

Thank you for considering this suggestion :)

**Comment by HackuJacku** [comment]
We won't be adding these items to the `/warp mart` but will be adding other methods to get these. Will close this as it's currently in the works.
