### ISSUE TITLE
Bring back galaxy and shadow legs 

### ISSUE THREAD

**Issue by biggabage1** [SmashMC-Development/Suggestions#579]
I want to bring back Galaxy and shadow leg spawning in wz its been over a month with out them
on top of that one of the biggest appeals to this server was custom textures hiding them behind a pay wall sucks to any player who wants them 

i would like this on all servers 

So its been a month with out the galaxy's and we really want them back

**Comment by DragonBallBreakersRandomizer** [comment]
Ngl it kinda ruined the point of buying a galaxy crate when the galaxy spawned in wz, shadow legends I understand but maybe another texture for wz mons?

**Comment by biggabage1** [comment]
but why do we even have galaxy legend crates if you hide stuff behind pay walls that used to be a hard but simple enough to get it could drive people away

**Comment by Waferthingaming** [comment]
Well it’s just a cosmetic and all it does it change the look of the Pokémon and if you want a galaxy Pokémon you can just trade for it. (Also it ruined galaxy crates)

**Comment by Rasgnarok** [comment]
Duplicate of https://github.com/SmashMC-Development/Bugs-and-Issues/issues/327. As I discussed there, the decision to remove Galaxy spawns from Warzone was far more than simply a decision to 'paywall'. Closing, as it's a duplicate.
