### ISSUE TITLE
Renew the stealing GUI in warzone

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#58]
**Describe the suggestion**
Renew the stealing GUI after winning a warzone match in warzone. 

**Which servers does this apply to?**
Network. 

**Additional context**
Make it so the GUI shows: stats, nature, item that the pokemon is holding, ability and size.

**Comment by Mikirae** [comment]
This is something that can and will be added in the new Warzone rewrite.
