### ISSUE TITLE
GTS implementation for HA's Breedables/Unbreedable Price Feature

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Suggestions#582]
**Describe the suggestion**
Before players are allowed to sell their pokemons or eggs on gts, make it so that the minimum price for breedable HA, doesn't matter about IVs, are priced at 200k minimum otherwise we have players ruining the market in every server and warning doesn't do much.

**Which servers does this apply to?**
All the servers, but I am from Charizard and its happening right now

**Additional context**
![image](https://user-images.githubusercontent.com/77503363/128339380-cb5a3546-42ff-4512-8a0f-7b28177f5cef.png)
![image](https://user-images.githubusercontent.com/77503363/128339429-9bb2ed2f-8e73-47eb-a520-7892c0801f41.png)
![image](https://user-images.githubusercontent.com/77503363/128339470-b2a34bed-b7db-4d03-92d5-17a7c8eed7ca.png)

**Comment by HackuJacku** [comment]
We sadly decided against this in the end based on other ideas we'll be implementing.
