### ISSUE TITLE
I have talked to a lot of players in multiple servers. We have all come to the conclusion that we think the z crystal Ultra Necrozium z should be added to the mart on all servers. 

### ISSUE THREAD

**Issue by SlaxyBoy** [SmashMC-Development/Suggestions#584]
**Describe the suggestion**

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
We will not be adding these to the mart. They will remain how they are, kill Necrozmas which spawn naturally (not in the Warzone).
