### ISSUE TITLE
Bring Back Epic Crate Rewards for Tourneys!

### ISSUE THREAD

**Issue by leelingmao** [SmashMC-Development/Suggestions#589]
I want epic crates to be the reward again for tourneys.

Rare crates are just not enough of a reward, and barely anyone does tourneys anymore.

I say add epic crates to tourneys so more people would be interested in battling in them, and it won't just be 4 people battling for a rare crate just to get 2 Shiny pokemon. Also, nowadays non-legendary iv boosts are worth 100k, compared to before when they were worth about 20k, talk about inflation. This is most likely because of the change of tourney rewards. Many people probably also lost interest in the server because of this subtle, but impactful change. 

So I say consider bringing epic crates back, as the pixelmon servers are not as alive and hyped up as they used to be with these changes.

**Comment by HackuJacku** [comment]
Based on our future plans and direction we wish to go in, we won't be making this change. This change is part of a bigger set which will be releasing very shortly - one of them being is that we want weekly events, e.g: Raids, to give better rewards whereas a tournament which happens every 3 hours should not give the exact same reward as a weekly event.

From a Rare Crate, you're able to work your way to get a Legendary crate key, the crates are significantly better compared to what they once were.
