### ISSUE TITLE
NPC House Fix

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#591]
**Describe the suggestion**
So On Jirachi The npc house is in the middle of a snow field, while on rayquaza its at spawn. I was gonna ask if the npc house  can be moved to spawn so new players can find it.

**Which servers does this apply to?**
Jirachi

**Additional context**
Jirachi
![image](https://user-images.githubusercontent.com/84050975/131024868-74958e38-4ddb-484e-936d-b519bba38ad9.png)
Rayquaza
![image](https://user-images.githubusercontent.com/84050975/131025060-8516c876-9978-44e5-9445-c3d1241bf8dc.png)

**Comment by HackuJacku** [comment]
Implemented on the reset
