### ISSUE TITLE
Converters

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#592]
**Describe the suggestion**
(This is my friend's suggestion btw), So theirs papers that  can convert shiny mons so maybe their can be a legendary shadow converter, like shadow converter can be only found in boss raid as legend rarity for the legend one and the non legend as mytic rarity.

 I also have an idea for a galexy converter (listen first), The galexy converter has the rarity of the galaxy battle bond greninja but can only be used on Legends (Not garchomp, greninja, zapdos, Whooper for rarity) and its only avabile in the galaxy crate as A chance.

**Which servers does this apply to?**
All.

**Additional context**
Maybe add shadow crates for the shadow converter if u don't wanna make it avabile in raid

**Comment by HackuJacku** [comment]
We sadly won't be adding Texture Converters. Shiny converts will be rarer on the reset
