### ISSUE TITLE
quest glitch

### ISSUE THREAD

**Issue by Fozito** [SmashMC-Development/Suggestions#596]
bascially i couldnt abandon any quests i had started whenever i clicked on the quests it deselects the quest. Also whenever i log back onto the server my chat pops up "a galarian zapdos appears" which was one of the quest that i had already completed for now it appears in chat but i could never find the zapdos

-Dialga server

**Comment by HackuJacku** [comment]
Not a suggestion, please create a bug report. You're provided with a template/format, use it please.
