### ISSUE TITLE
New /timeshop item

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#598]
**Describe the suggestion**
Add an item to timeshop, terrian extender as timeshop item s are useful for wz and terrian extender is good too.

**Which servers does this apply to?**
All

**Additional context**
Add it next to mballs maybe 
![image](https://user-images.githubusercontent.com/84050975/131775191-320c26f1-1ac0-403f-aecf-64bd5b311737.png)

**Comment by DragonBallBreakersRandomizer** [comment]
Maybe also kings rock :)

**Comment by HackuJacku** [comment]
The TimeShop is removed on the reset
