### ISSUE TITLE
Mega Evolution not working properly

### ISSUE THREAD

**Issue by Restlezzz** [SmashMC-Development/Suggestions#599]
Describe the Bug
Some Mega Evolution ability are not working properly 

Mega evolve Mawile, it will get intimidate ability 2x instead of huge power.
Mega evolve Gengar, Shadow tag sometimes not working. 

Servers with the Bug
Charizard

Expected behavior
Mawile should gain Huge Power ability instead of Intimidate 

Screenshots
N/A

**Comment by HackuJacku** [comment]
Not a suggestion, please create a bug report. You're provided with a template/format, use it please.
