### ISSUE TITLE
Charizard Name

### ISSUE THREAD

**Issue by Sslooshyy** [SmashMC-Development/Suggestions#6]
**Describe the suggestion**
Change the name of Charizard to Groudon like we talked about after the reset, before all of the new servers got added
**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.
Charizard
**Additional context**
Charizard feels like an outcast since all of the other servers are named after legends and it'd complete the trio with ray and kyogre

**Comment by HackuJacku** [comment]
Whenever Charizard is next reset (fresh start), it will be renamed to Groudon.
