### ISSUE TITLE
Machamp

### ISSUE THREAD

**Issue by ajdawg48** [SmashMC-Development/Suggestions#604]
**Describe the suggestion**
Add fissure machamp back to warzone. If people are allowed to run full arceus teams I think people should be able to run a team of machamp both unbalanced but for some reason one is banned but the other isn’t.

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.
All
**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
We won't be doing this, we're putting something in place to stop the full Arceus teams from being bought into the Warzone.
