### ISSUE TITLE
New feature called Daycare

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Suggestions#606]
**Describe the suggestion**
./daycare feature that allows players to send their pokemon to auto-earn exp. Basically something like a afk exp farm instead of players manually farming exp. There can be a limit to the number of pokemon they can put in the daycare or maybe something like a AFK exp level limit. Like they can only earn exp until lvl 80 or something. 

**Which servers does this apply to?**
Charizard since its a very competitive server where many players fights the most.

**Additional context**
NIL

**Comment by HackuJacku** [comment]
There are some really cool Daycare features out there but we sadly decided against adding it :/
