### ISSUE TITLE
Bottle cap trade

### ISSUE THREAD

**Issue by AskUrDaddy** [SmashMC-Development/Suggestions#607]
When fishing you have a chance of getting and item called silver bottle cap from a !!! but it is a banned item so it is removed from your inventory. I feel that's a waste of a !!! drop and it prevents from you from getting blue shard drops. A trader should be added to the mart that allows you to trade a certain amount of bottle caps for a red or blue shards.

**Comment by DragonBallBreakersRandomizer** [comment]
good idea

**Comment by HackuJacku** [comment]
Implemented on the reset
