### ISSUE TITLE
STS changes.

### ISSUE THREAD

**Issue by King-Thor** [SmashMC-Development/Suggestions#608]
A few suggested changes for STS.
1. Instead of Max IV bonuses, they should be set to give you bonuses for also 29 and 30 IVs -taking into account breeding in hidden power types.
2. A nature bonus of 100, for the ideal nature of that Pokemon.
3. - And the most important. Please, for the love of all things holy remove single pokemon sales. Default mode should be bulk sales. There is nothing more frustrating, and infuriating than misclicking and having to wait 15 minutes to sell off some pokemon.

This should be default on all servers.

**Comment by DragonBallBreakersRandomizer** [comment]
1. that would have no point then ngl 
2. Their so many sets a pokemon could have so their would be a lot of nature and theirs no "ideal" nature for a pokemon.
3. Maybe check the vending machine first before sts

**Comment by King-Thor** [comment]
1. It still has a point, as 29-30 in the IV column are still considered battle perfect by battlers, because of Hidden Power types. It's point would be to squeeze a couple more dollars to give to the community. Make more people slightly more encouraged to go hunting wild mons, as there's a higher chance that there could be some monetary value.
2. I mean, it's an additional 100 dollars, and you can only have one of a few 'perfect' natures per mon.
3. Or, just remove the single Pokemon sale option, which doesn't hurt things at all. You add your one pokemon to your one pokemon list, and then you sell it. 
It's a quality of life change that makes things simpler. Simple is easy. Easy is better. Imagine, being able to fire up the STS after a server restart and you not needing to check the vending machine? Wow. Simple. I don't need to worry about accidently selling just one mon and waiting fifteen minutes to sell another. Also wow. I want to play the game more now, instead of logging off and playing something else for 15 minutes.

**Comment by HackuJacku** [comment]
Implemented to a degree on the reset
