### ISSUE TITLE
Server Reset

### ISSUE THREAD

**Issue by Firemelon66** [SmashMC-Development/Suggestions#610]
**Describe the suggestion**
I want to suggest abt an Server Reset, 

**Which servers does this apply to?**
To every server

**Additional context**
I Want  an server reset with everything like the market will be resetted everyone will start from scratch, 
-1st we will be able to bring 3 unbreedable pokemons with us 
-2nd A lot players will come back
-3rd  we can fight again cause everyone will play again a lot
-4rd The economy will be normal again 
thats the ideas i have why i want the server reset

**Comment by HackuJacku** [comment]
Sometime in the future, yes. When that'll be, who knows currently.
