### ISSUE TITLE
Bring back Drop Parties 

### ISSUE THREAD

**Issue by biggabage1** [SmashMC-Development/Suggestions#611]
I haven't seen a drop party is so long it was super fun and i find it as a way for the staff to give back for the support of the player base.
**Which servers does this apply to?**
All servers
The drop parties was something a lot of players looked forward to per month it was fun. You also could walk away with some pretty good stuff. It was a way of giving back and most player found that as a nice thing it also might bring back some players bc the servers are dieing

**Comment by DragonBallBreakersRandomizer** [comment]
Personally I dont think this is a good idea as this puts a bit of damage into the eco of each server.

**Comment by HackuJacku** [comment]
We sadly won't be bringing back drop parties due to each time we did them, there was a significant increase in the number of complaints due to players not liking what they got or did not get anything. This is very sad honestly but we've decided moving forward it'll be best not to do them.
