### ISSUE TITLE
WARZONE

### ISSUE THREAD

**Issue by JayCoates** [SmashMC-Development/Suggestions#612]
hey Smash People,
In warzone there is a massive glitch were if you throw your Pokeball of the map you have to relog to then throw it back out.
Also in Warzone there is some legendaries that spawn on the ship and we arent able to get them.some also spawn in the wall.

**Comment by HackuJacku** [comment]
Fixed in Warzone 2.0. Please also create a bug report instead of a suggestion in the future, follow the format provided too.
