### ISSUE TITLE
MASTER RANK

### ISSUE THREAD

**Issue by JayCoates** [SmashMC-Development/Suggestions#613]
Hey Smash people,
 there is another massive when you are master and have completed the game there is nothing for us to do except chill in wz for no reason. I have asked multiple people about this and that is one of the reasons why people leave the game because they just get bored. adding in additional tournaments or events would be better or something like that. Also bringing in UBERS to the warzone is annoying for everyone.

**Comment by HackuJacku** [comment]
This is not a suggestion, please can you explicitly state what you're suggestion please?

**Comment by HackuJacku** [comment]
Implemented on the reset
