### ISSUE TITLE
Different ways of making money.

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Suggestions#615]
**Describe the suggestion**
I would like another way to make money on the server in the form of a job. ive seen a plugin on other pixelmon servers (im not sure which server) where you can be a certain job and get paid for doing the things that the job would entail, for example a miner gets money for mining. 
**Which servers does this apply to?**
All.

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Implemented on the reset
