### ISSUE TITLE
Merging of Servers

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Suggestions#621]
**Describe the suggestion**
There are some servers with less than 10 people online, or A.K.A dead servers you may call them. So I was wondering if you devs, would consider merging those dead servers with active servers like Ray or Char. Although the economy might be messed up or smth, I think the players might be able to handle it themselves. Although a Server-wide vote might be good to get everyone's suggestion. I'm just suggesting this since there are no server resets in place atm. How people are gonna bring their stuff over to another server, i have no clue. :D

**Which servers does this apply to?**
All of the Servers

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Implemented on the reset
