### ISSUE TITLE
Make bosses spawn faster in ./warp boss

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Suggestions#624]
**Describe the suggestion**
I find that the bosses spawns quite slow, maybe you can make it spawn faster for the players. Why? So that players can farm drops from bosses faster and increase the rates of the different types of bosses(Legendary, Ultimate, Rare, Common, Uncommon) etc.

**Which servers does this apply to?**
All of the servers

**Additional context**
N/A

**Comment by HackuJacku** [comment]
Implemented on the reset
