### ISSUE TITLE
Legend spawns

### ISSUE THREAD

**Issue by Coolpool558** [SmashMC-Development/Suggestions#629]
I understand that warzone is a high risk high reward way to get legends. But I believe I speak on many peoples behalf’s and don’t want to sit around for 48 hours and wait for one legend to spawn. So I believe that because of the new and timed warzone that the legend spawn rates should be increased just a little bit so they are easier to obtain.( this idea has been shut down in the past because of the warzone and with its change maybe people will listen)

**Comment by HackuJacku** [comment]
Warzone from the reset now uses a completely new spawning system, it's very different to the existing one. Therefore, this suggestion can't be used sadly until you've experienced the new Warzone but the spawn rates will not go back to what they once were as that was very broken.

**Comment by Coolpool558** [comment]
I am speaking about the spawnrates outside the warzone not within. I do agree the old spawnrates were broken. But the spawnrates outside of the warzone are painfully low compared to what their standards are I feel
