### ISSUE TITLE
plis make it so u safeplace it sends u rigth into the safeplace arena or so make it so ppl cant figth u when u safeplace

### ISSUE THREAD

**Issue by loltord** [SmashMC-Development/Suggestions#630]
**Describe the suggestion**

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
This is sadly a suggestion we won't be implementing.
