### ISSUE TITLE
I believe the number of pokemon u can breed at a time should be increased.

### ISSUE THREAD

**Issue by ThePapaChunks** [SmashMC-Development/Suggestions#632]
**Describe the suggestion**
I believe the amount of breeders should be changed from allowed 7 to be possibly 22-30 I knows it meant to help the economy but I also believe it could hurt the economy, I 100% agree there should be a cap but not this low as alot of people enjoy the breeding aspect of the game and it is good for money making. But I think you should add more and maybe add time based on the amount you have(more time it takes for them to breed) or someway to balance it but personally as someone with 200+ breeders I trashed every non Battle Perfect egg, or make a limit to amount of things you can sts or gts in a certain amount of time. You could also lower there value in price to make them a less efficient money making method.
Also breeding already costs so much time in general, and with it taking so much time i think there should be more for the breeders.
**Which servers does this apply to?**
All of the new servers .

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by DragonBallBreakersRandomizer** [comment]
ngl I like the cap, before the eco was all based on breeding so not many people were putting money into the economy so that crashed many server ecos.

**Comment by ThePapaChunks** [comment]
> ngl I like the cap, before the eco was all based on breeding so not many people were putting money into the economy so that crashed many server ecos.

Ive played other servers caps have caused downfalls i dont mind a cap I think it should be higher tho 7 is extremely low when u need 6 mons to make a team that means you gotta breed the 6 mons you want for your team. Also they could lower the value of bps to make it a less efficient money maker

**Comment by DragonBallBreakersRandomizer** [comment]
Tho who breed will breed, but it will encourage people to grind for boss loot for cash

**Comment by ghost** [comment]
idk if the the real problem is with the number of breeders. It is with distribution of bp breedables. Breeding already takes up so much time and limited it to 7 breeders will disincentivise ppl to do it. Moreover some ppl just enjoy breeding and like to compete with other breeders in the variety of pokemon they breed, including me, which would not be possible with just 7 breeding pairs

**Comment by ThePapaChunks** [comment]
> idk if the the real problem is with the number of breeders. It is with distribution of bp breedables. Breeding already takes up so much time and limited it to 7 breeders will disincentivise ppl to do it. Moreover some ppl just enjoy breeding and like to compete with other breeders in the variety of pokemon they breed, including me, which would not be possible with just 7 breeding pairs

I agree I actually do find breeding as something that is competitve and part of the fun of it is that for me and I also love the variety options.

**Comment by Rasgnarok** [comment]
Duplicate: https://github.com/SmashMC-Development/Suggestions/issues/635

**Comment by Rasgnarok** [comment]
> 
> 
> idk if the the real problem is with the number of breeders. It is with distribution of bp breedables. Breeding already takes up so much time and limited it to 7 breeders will disincentivise ppl to do it. Moreover some ppl just enjoy breeding and like to compete with other breeders in the variety of Pokemon they breed, including me, which would not be possible with just 7 breeding pairs

While I understand what you mean, the fun aspect of breeding isn't being ignored here, it's being accommodated to make sure the future of the breeding activity remains as healthy as possible. It's not about bp breedables, it's about the value placed on breeding efforts. By limiting the rate of egg production, you value egg creation more, forcing the player to be more selective in what they breed, and when they do it.

**Comment by Rasgnarok** [comment]
> 
> 
> **Describe the suggestion** I believe the amount of breeders should be changed from allowed 7 to be possibly 22-30 I knows it meant to help the economy but I also believe it could hurt the economy, I 100% agree there should be a cap but not this low as alot of people enjoy the breeding aspect of the game and it is good for money making. But I think you should add more and maybe add time based on the amount you have(more time it takes for them to breed) or someway to balance it but personally as someone with 200+ breeders I trashed every non Battle Perfect egg, or make a limit to amount of things you can sts or gts in a certain amount of time. You could also lower there value in price to make them a less efficient money making method. Also breeding already costs so much time in general, and with it taking so much time i think there should be more for the breeders. **Which servers does this apply to?** All of the new servers .
> 
> **Additional context** Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

As I mentioned before, it makes sense to limit somehow, and while not everyone breeds as much as you used to, it's definitely in excess for a minority of people responsible for the market's downfall. I don't think everyone is as self-aware when it comes to managing breed-jects as you, which is why the cap had to be enforced in the first place.

Speaking of numbers, while I am flexible when it comes to a change, I think asking for 3 to 4 times the amount of egg production currently planned is... intense.

**Comment by ThePapaChunks** [comment]
> > **Describe the suggestion** I believe the amount of breeders should be changed from allowed 7 to be possibly 22-30 I knows it meant to help the economy but I also believe it could hurt the economy, I 100% agree there should be a cap but not this low as alot of people enjoy the breeding aspect of the game and it is good for money making. But I think you should add more and maybe add time based on the amount you have(more time it takes for them to breed) or someway to balance it but personally as someone with 200+ breeders I trashed every non Battle Perfect egg, or make a limit to amount of things you can sts or gts in a certain amount of time. You could also lower there value in price to make them a less efficient money making method. Also breeding already costs so much time in general, and with it taking so much time i think there should be more for the breeders. **Which servers does this apply to?** All of the new servers .
> > **Additional context** Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.
> 
> As I mentioned before, it makes sense to limit somehow, and while not everyone breeds as much as you used to, it's definitely in excess for a minority of people responsible for the market's downfall. I don't think everyone is as self-aware when it comes to managing breed-jects as you, which is why the cap had to be enforced in the first place.
> 
> Speaking of numbers, while I am flexible when it comes to a change, I think asking for 3 to 4 times the amount of egg production currently planned is... intense.

I can understand what you mean by doing a ton is intense but what if we say atm something like 12-14 enough to be able to make 2 different teams with the amount we breed?
Or atleast a little higher to some extent.

**Comment by Rasgnarok** [comment]
> 
> 
> > > **Describe the suggestion** I believe the amount of breeders should be changed from allowed 7 to be possibly 22-30 I knows it meant to help the economy but I also believe it could hurt the economy, I 100% agree there should be a cap but not this low as alot of people enjoy the breeding aspect of the game and it is good for money making. But I think you should add more and maybe add time based on the amount you have(more time it takes for them to breed) or someway to balance it but personally as someone with 200+ breeders I trashed every non Battle Perfect egg, or make a limit to amount of things you can sts or gts in a certain amount of time. You could also lower there value in price to make them a less efficient money making method. Also breeding already costs so much time in general, and with it taking so much time i think there should be more for the breeders. **Which servers does this apply to?** All of the new servers .
> > > **Additional context** Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.
> > 
> > 
> > As I mentioned before, it makes sense to limit somehow, and while not everyone breeds as much as you used to, it's definitely in excess for a minority of people responsible for the market's downfall. I don't think everyone is as self-aware when it comes to managing breed-jects as you, which is why the cap had to be enforced in the first place.
> > Speaking of numbers, while I am flexible when it comes to a change, I think asking for 3 to 4 times the amount of egg production currently planned is... intense.
> 
> I can understand what you mean by doing a ton is intense but what if we say atm something like 12-14 enough to be able to make 2 different teams with the amount we breed? Or atleast a little higher to some extent.

The number is currently at 14, I could increase it to 20. Would that be a good start? It implies 10 breeding pairs at any one time.

**Comment by ThePapaChunks** [comment]
> > > > **Describe the suggestion** I believe the amount of breeders should be changed from allowed 7 to be possibly 22-30 I knows it meant to help the economy but I also believe it could hurt the economy, I 100% agree there should be a cap but not this low as alot of people enjoy the breeding aspect of the game and it is good for money making. But I think you should add more and maybe add time based on the amount you have(more time it takes for them to breed) or someway to balance it but personally as someone with 200+ breeders I trashed every non Battle Perfect egg, or make a limit to amount of things you can sts or gts in a certain amount of time. You could also lower there value in price to make them a less efficient money making method. Also breeding already costs so much time in general, and with it taking so much time i think there should be more for the breeders. **Which servers does this apply to?** All of the new servers .
> > > > **Additional context** Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.
> > > 
> > > 
> > > As I mentioned before, it makes sense to limit somehow, and while not everyone breeds as much as you used to, it's definitely in excess for a minority of people responsible for the market's downfall. I don't think everyone is as self-aware when it comes to managing breed-jects as you, which is why the cap had to be enforced in the first place.
> > > Speaking of numbers, while I am flexible when it comes to a change, I think asking for 3 to 4 times the amount of egg production currently planned is... intense.
> > 
> > 
> > I can understand what you mean by doing a ton is intense but what if we say atm something like 12-14 enough to be able to make 2 different teams with the amount we breed? Or atleast a little higher to some extent.
> 
> The number is currently at 14, I could increase it to 20. Would that be a good start? It implies 10 breeding pairs at any one time.

I think 20 is a good start yes prob the perfect number to be honest, but maybe you could add a way down the line to get more like maybe if skills come back lv 200 breeder could get u 5 more or something.

**Comment by ghost** [comment]
It is not just about the variety and fun of breeding... As a breeder and a battler less amount of bps severely restricts team building as it takes time to breed new pokemon. If not done simultaneously, ppl can easily counter team you in wz.

**Comment by ThePapaChunks** [comment]
> It is not just about the variety and fun of breeding... As a breeder and a battler less amount of bps severely restricts team building as it takes time to breed new pokemon. If not done simultaneously, ppl can easily counter team you in wz.

This is why i said maybe make it more over time thats why I kept strongly mentioning that 7 is only 1 team and 1 extra mon.

**Comment by Rasgnarok** [comment]
Resolved: bumped from 14 to 20 Pokémon cap in Ranch Blocks.
