### ISSUE TITLE
Breeding cap.

### ISSUE THREAD

**Issue by WalkAway7** [SmashMC-Development/Suggestions#633]
**Describe the suggestion**
So, with this breeding cap. I agree that there should be some sort of cap on the ranch blocks, but as a player who very much enjoys the aspect of breeding, and also someone who loves to show of all of the cool pokemon I have found, it is quite a blow for me. I would love if there was a way in the near future for it to change for only a cap on breeding partners, this way, we can still have wonderful builds that include ranch blocks to show off pokemon.

**Which servers does this apply to?**
I would like this to be implemented on all pixelmon servers.

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
Pixelmon actually plans on including display blocks for Pokemon, sadly though, this is not something that we could support with the current config. A good suggestion for Pixelmon itself though.
