### ISSUE TITLE
Hidden Ability Pokemon

### ISSUE THREAD

**Issue by EmptyAnimation** [SmashMC-Development/Suggestions#634]
I think that there should be catch combos like in Pokemon Let's Go Eevee/Pikachu. For increased odds of finding a Hidden Ability Pokemon. Up to say 35? or something to help make the Pokemon spawn more. Since the Hidden Ability Pokemon will be unbreedable if you aren't the original trainer at least make it easier for the people who are spending hours hunting Hidden Abilities to be able to find them *somewhat* easier. Or maybe increase chances in raid dens? Idk which ever works :)

**Comment by Rasgnarok** [comment]
Raids actually already increase dens, "If your lucky you can find Shiny Pokémon, Gigantamax Pokémon, and Pokémon that have their Hidden abilities. The higher the star level, the higher the odds are of finding these. " Good call, though already applicable, https://pixelmonmod.com/wiki/Max_Raid_Battles.
