### ISSUE TITLE
Breeding cap improvement ideas

### ISSUE THREAD

**Issue by Thor20213** [SmashMC-Development/Suggestions#635]
So, I don't agree with the new breeding stuff but I get that you probably won't change your mind so I have a suggestion to improve it. If you want to have a cap on breeding atleast make it so that the amount you can breed increases with your dex rank, the max will be master rank which I think should be atleast 20. And if your gonna make it so that HA pokemon can't be bred by non OT players than make the HA pokemon more common or just don't implement the HA feature.

**Comment by ThePapaChunks** [comment]
I actually could see this and it does actually make sense, If you get more mons you should be able to breed more. And for the HA thing I think if they let us use the HA lures it would be a good fix to it.

**Comment by Rasgnarok** [comment]
Duplicate, closing in favour of https://github.com/SmashMC-Development/Suggestions/issues/632
