### ISSUE TITLE
Trainers should be able to set more than 1 home right now.

### ISSUE THREAD

**Issue by SilentOfChaos** [SmashMC-Development/Suggestions#648]
**Describe the suggestion**
Trainers should be able to set more than 1 home right now. As otherwise, players would hv to wait till next week to get back their ranks in order to be able to set more than 1 home. I believe the starting limit for ./sethome should be around 3-5, and it increases as they buy or upgrade their ranks(Paid/Free ranks).  Or is this going to be the norm from now onwards? Maximum home limit is 1 for fresh players? 

**Which servers does this apply to?**
All of the servers

**Additional context**
![image](https://user-images.githubusercontent.com/77503363/138560406-ab7d26f9-125e-40fa-af29-0c0e3d27df14.png)

**Comment by SilentOfChaos** [comment]
And also there's no evolution stone being sold in the ./warp mart as before and ./sts is not working. pls add it in ty

**Comment by HackuJacku** [comment]
Fixed
