### ISSUE TITLE
/breeding no work

### ISSUE THREAD

**Issue by Thor20213** [SmashMC-Development/Suggestions#651]
When I do /breeding and try to click one of the tutorial stuff they just pop out and don't open anything 

I'm on reshiram idk abt other servers 

![16350072968152596331037133715423](https://user-images.githubusercontent.com/92854365/138564657-f8649192-f58a-4cd0-b2d9-7dcf350d8c5f.jpg)

**Comment by HackuJacku** [comment]
Fixed - next time report as a bug please @Thor20213
