### ISSUE TITLE
npc bug

### ISSUE THREAD

**Issue by gusiong** [SmashMC-Development/Suggestions#655]
**Battle npc or trainer npc some time bug**
if you battle them its fine but if you use a move it will say a battle error has occurred check the console for details and report this to the pixelmon developers

**reshiram?**
on reshiram

**not only npc are bug**
the villager is bug to they dont give a quest not even one i wait 3 hours no quest bruhhhhhh

**Comment by HackuJacku** [comment]
Pixelmon battle glitch, forwarded onto them.
