### ISSUE TITLE
Boosts in warzone! 

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#66]
something in warzone that people can go and stand on for a certain time and claim to get boosts of some sort like movement speed, invisiblity, heal etc.. etc..

**Comment by Mikirae** [comment]
This could potentially be good as it could force players to become "targets" in favor of some sort of gain.

**Comment by HackuJacku** [comment]
Boosts will be adding as part of Warzone 2.0 - they'll be balanced though in regards to how they're implemented. Will forward to the master Warzone ticket.
