### ISSUE TITLE
Suggestion Fix Warzone

### ISSUE THREAD

**Issue by Lukeymac** [SmashMC-Development/Suggestions#664]
Remove the warzone fee and timer, add more pokemon spawns to the warzone and allow players to battle one another

Groudon, But all I presume

Yall had it right last map but with a few bugs if remove the fee and the timer and fix the bug not allowing players to battle it will make a more competitive warzone. Especially early on where nobody has money to afford 2500/1min it just makes it boring.

**Comment by HackuJacku** [comment]
Both the timer and the fee will remain. This is because people used to sit and AFK in Warzone all day and took away from what it was intended to be. It's intended for to battle and be at risk, not 'safe'.
