### ISSUE TITLE
FIX WZ!

### ISSUE THREAD

**Issue by Coolpool558** [SmashMC-Development/Suggestions#666]
Wz is so dumb. I know so many people who quit bc you have to pay to get to wz. There are other ways to prevent afking in wz. Make it so people have to keep moving or get kicked. This isn’t the only issue. Legs still spawn outside of wz, very few mons actually spawn in wz, and wz is way too big for anyone who actually goes. There are so few people in wz so everything is so spread out and it sucks because no one wants to pay to go in. This makes it hard for stuff to spawn and no one can find the things the want and battling is broken. FIX THE SERVER AND CHANGE WZ!

**Comment by HackuJacku** [comment]
Provide a constructive suggestion, this doesn't help us to improve the server @Coolpool558.
