### ISSUE TITLE
Warzone.

### ISSUE THREAD

**Issue by NetherGoddess** [SmashMC-Development/Suggestions#670]
I'll start this by saying I've been playing for a year, and I am not opposed to change at all. If its for the better. There are so many other solutions to the afking in warzone other than paying. "Oh you can kill/catch Pokémon in WZ for more time" the Pokémon are so few and far in-between that its not even helpful. I'm asking y'all, for everyone in the community, find a better solution. Because so many people, including me, only play this server for the excitement of warzone, without it this is the same as any other pixelmon server.

**Comment by HackuJacku** [comment]
There were no better solutions, we discussed it at great length. We don't want players to spend hours in the Warzone either.
