### ISSUE TITLE
Increase home limit 

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Suggestions#671]
**Describe the suggestion**
We should get more than 1 home when we first started in the game because it's hard to move around having only 1 home when we want to go to different biomes. Since we have a limit of 3 claims, I think it's only fair that we get 3 homes too.

**Which servers does this apply to?**
All servers

**Additional context**
It's a little unfair that you have to pay money to buy ranks in order to increase your home limit which will make the server more of a P2W server than a server that people play for fun and enjoyment.

**Comment by ThePapaChunks** [comment]
Yeah having only 1 is annoying.

**Comment by AngryRedHead101** [comment]
i agree too with needing ranks for more homes. 3 homes is a good amount to have, especially since alot of people are older players from previous servers like jirachi and charizard. The experianced players have no way to grind and farm for pokemon. the game shouldn't be p2w
