### ISSUE TITLE
Team preview in warzone.

### ISSUE THREAD

**Issue by LifelessDingus** [SmashMC-Development/Suggestions#68]
**Describe the suggestion**
Allow a team preview in warzone, as well as the option to choose the pokemon you lead upon engaging another player.

**Which servers does this apply to?**
Network.

**Additional context**
This is already active for gym battles and custom battles.

**Comment by Mikirae** [comment]
There's not really a good way to do this, as people could delay the battle during the team selection screen. The entire point of the engagement is to force people into a battle immediately.

That being said, this is something that could potentially be discussed for the rewrite of Warzone.
