### ISSUE TITLE
Get rid of spawn shrine fees

### ISSUE THREAD

**Issue by met21** [SmashMC-Development/Suggestions#684]
**Describe the suggestion**
I want you to remove shrine fees.

**Which servers does this apply to?**
All, Zekrom especially. I'm not sure if other servers have the same issue.

**Additional context**
The coin sink with Warzone is substantial enough to make the shrine fees unecessary for the economy. Aside from that, Zapdos shrines seem to just not spawn (at least on Zekrom). I've spent at least 4 hours searching in various savannah biomes to no avail. I'd rather not spend 50k on a legendary bird because the shrines didn't spawn naturally.

**Comment by HackuJacku** [comment]
The shrine fees will remain as they're provided by us which means you do not have to find them yourself. As a result, we will charge a fee to use them.
