### ISSUE TITLE
Get rid of warzone fees

### ISSUE THREAD

**Issue by xFlynnRH** [SmashMC-Development/Suggestions#691]
**Describe the suggestion**
The warzone cost should be removed allowing players to enter for free

**Which servers does this apply to?**
All of them

**Additional context**
I think the warzone cost would've been a good idea if players entered warzone more. Before reset warzone was completely empty and adding a cost to warzone would just make players be less likely to enter.

**Comment by HackuJacku** [comment]
The fees will remain, we won't be removing them.
