### ISSUE TITLE
Add dex remaining command 

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Suggestions#695]
**Describe the suggestion**
Sorry if this is already on here but it can be helpful to be able to see what pokes you have left to dex. On /dex on the "missing Pokemon" it still shows all Pokemon. I think before there was a /dex remaining so if there could be something like that that would be cool :)
**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.
all servers
**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
`/dexcheck`
