### ISSUE TITLE
can you please add /pokeheal beacuse its really annoying to always go to the /warp pokecenter when you pokemon fainted

### ISSUE THREAD

**Issue by Alonchips** [SmashMC-Development/Suggestions#699]
**Describe the suggestion**

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by Dxhcky** [comment]
It's a thing you just have to have a paid rank to use it. Every paid rank gives access to /pokeheal

**Comment by HackuJacku** [comment]
We're sadly not going to do this as we wish to keep it to the paid ranks. Sorry if this has caused any issues.
