### ISSUE TITLE
disable potions in wz

### ISSUE THREAD

**Issue by Bruhbert1999** [SmashMC-Development/Suggestions#7]
**Describe the suggestion**

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**

**Comment by Bruhbert1999** [comment]
disable potions from either being brought into wz or from being usable in wz. armor got banned for the buffs u receive from it, so potions (for speed or invis) should be treated equally imo

**Comment by HackuJacku** [comment]
@Bruhbert1999 - which type of potions are these please? Pixelmon or vanilla?

**Comment by HackuJacku** [comment]
In Warzone 2.0, the plan is as follows:

- If you try and enter the Warzone dimension with Minecraft potions, the effect will be cleared and returned on leaving.
- If you try and enter the Warzone dimension then drink it, the action will be blocked.
- You won't have the option/ability to use Pixelmon potions in battle.

Therefore, all cases are covered in the new version.
