### ISSUE TITLE
Make the amount of money you spend on warzone time appear in logs

### ISSUE THREAD

**Issue by M1n0j** [SmashMC-Development/Suggestions#704]
**Describe the suggestion**
Make the amount of time or money spent/bought on warzone appear in logs. This would help prove how much money was spent if a server crashed or the player got stuck for some reason and would make it easier to refund if needed.

**Which servers does this apply to?**
All

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Not required due to Warzone returning the money if the server reboots.
