### ISSUE TITLE
Improve Warzone Spawnrate or lower the price

### ISSUE THREAD

**Issue by CelinaPeng** [SmashMC-Development/Suggestions#707]
I really love the new Warzone but I think it has a couple problems attached to it. First I wan't to mention spawns out of map / suffering in a wall out of map. Often times it says that something spawned but u can't seem to find it, nobody caught it and it neither said that it despawned, that means that it obviously sufficated. You pay 16k and most of the time you don't even get a spawn and if u get one, theres no way to find it. Casual players can get really frustrated through that.

**Comment by HackuJacku** [comment]
I checked earlier and nothing spawns outside of the Warzone, it's impossible. Pokémon are also unable to suffocate, it's a visual issue.

The spawn mechanics have been slightly changed on the next reboot, improving the spawns tenfold.
