### ISSUE TITLE
Unbreed command

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Suggestions#709]
People only take ubers to warzone because no one wants to have a breedable bp taken from them and bred for themselves. This isn't just bad for warzone battles, but its also bad for people who need to make money by selling BP's. If you can only sell breedables, your hard work wont be needed as everyone can just breed the mons for themselves and so you have no business. It'd be good for the economy and for warzone fights to implement the unbreed command

**Comment by HackuJacku** [comment]
#741
