### ISSUE TITLE
Stat changing papers don't stack (iv boost, nat change, shiny conv etc)

### ISSUE THREAD

**Issue by Leamyyy** [SmashMC-Development/Suggestions#720]
**Describe the suggestion**

The papers you get from crates do not stack.

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

I think all servers, but I've noticed it on say. Br also said this happend to him.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.
![Uploading 2021-10-29_21.58.18.png
![2021-10-29_21 58 17](https://user-images.githubusercontent.com/93057830/139494998-46e37523-8f79-4fe1-8020-220eab0467cc.png)
…]()

**Comment by HackuJacku** [comment]
This is intended due to the anti-duplication logic. We had to give stacking up over stopping people from duplicating the papers like in the past
