### ISSUE TITLE
Not being able to use {item} or /show {pokemon1,2,3,4,5,6}

### ISSUE THREAD

**Issue by Leamyyy** [SmashMC-Development/Suggestions#722]
**Describe the suggestion**

The plugins about {item} and {pokemon} (/show) don't work

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

I think only on rayquaza

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Believe this is working fine, if not, please create a bug report.
