### ISSUE TITLE
/rtp still has no cooldown

### ISSUE THREAD

**Issue by Leamyyy** [SmashMC-Development/Suggestions#725]
**Describe the suggestion**

Whenever you type /rtp you can do this without cooldown, while other servers do have a 120? cooldown.
I suggest adding the 120 cooldown on rayquaza aswell

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

Only rayquaza

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Fixed
