### ISSUE TITLE
Warzone update suggestion

### ISSUE THREAD

**Issue by ehhhkody** [SmashMC-Development/Suggestions#732]
Instead of having an entry fee related to the amount of time you can spend in warzone, why not make a base entry fee with no timer. Lets say 10k to enter.

While inside warzone if you catch anything you are given a timer before you can leave warzone. Lets say 2 minutes. If you catch more than one pokemon, don't compound the timer, just set it back to 2 minutes each time. If you log to avoid timer, you lose your caught pokemon in your warzone bank. 

Once you leave warzone you have a timer before you can re enter.

**Comment by HackuJacku** [comment]
I'm sorry but we won't be implementing this suggestion, we want to limit how long players can be in the Warzone and not camp it.
