### ISSUE TITLE
Mythic Rank

### ISSUE THREAD

**Issue by AnticIsALPHA** [SmashMC-Development/Suggestions#734]
Hello I would like to make a request/suggestion for Prio queue to be added back to Mythic ranks as one of the main features before the wipe happened was Prio queue and me and many others feel it is unfair that it was taken away. Some of us bought mythic only for the Prio queue
With all due respect please add Prio queue back to mythic

**Comment by Bkdevileu** [comment]
Paid ranks never had prio queue, only staff

**Comment by AnticIsALPHA** [comment]
> o

Paid Ranks always had Prio but now its only legend above used to be mythic above

**Comment by Bkdevileu** [comment]
Like I said, paid ranks having prio queue was never a thing, it was discussed several times, only ones with prio queue are staff so they can enter the servers to deal with issues

**Comment by HackuJacku** [comment]
Paid ranks have never had priority to join, only staff. This is how it has always been. The Smash rank has the ability to join the server when it is full however.
