### ISSUE TITLE
Remove berries and fossils from boss drops!

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Suggestions#736]
**Describe the suggestion**
Remove berries and fossils from boss drop. It is honestly just a waste of time. You can buy berries at mart or just grow them and it is very easy to get fossils in wild. And since you can't sell them anyways, it makes them a wasted boss drop.

**Which servers does this apply to?**
I play on Groudon but probably apply to all.

**Comment by Rasgnarok** [comment]
We've reworked boss drops to include more varied rewards, but berries and fossils are only one of the many rewards possible. Just because one reward is obtainable elsewhere doesn't make it a valid one for those that prefer it there. Closing, as per rework.
