### ISSUE TITLE
Smash reacts Shorter time

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Suggestions#74]
**Describe the suggestion**
make the smash reacts in-between time shorter

**Which servers does this apply to?**
All

**Comment by HackuJacku** [comment]
SmashReact is no longer used - is this an issue with the SmashTrivia?

**Comment by HackuJacku** [comment]
Closing as Lun is not the original suggester - copied from Discord. If it's still a valid suggestion, please create a new request.
