### ISSUE TITLE
/unbreed

### ISSUE THREAD

**Issue by borkborkdog** [SmashMC-Development/Suggestions#741]
**Describe the suggestion**
Add back /unbreed so that you can sell pokemon and not let others breed it

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.
All I know so far is Kyogre

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.
N/A

**Comment by HackuJacku** [comment]
Added the command but recoded the logic so once a Pokémon is unbreedable, it can't be changed.
