### ISSUE TITLE
Wz Suggestion

### ISSUE THREAD

**Issue by morrow12** [SmashMC-Development/Suggestions#749]
Hello,  the problem with warzone you guys  took out the comp groups no longer have a reason to particularly grind for comp also it feels janky having to pay to go in the new warzone.  The old warzone was competitive , and fun.
A top of that it just feels like you got rid of the old one due to everyone camping warzone. I'm okay with the fee but I dont like the timer a lot of people dont too, this is completely up to you guys if you wanna listen to this suggestion.
 

Hope this helps. Thanks

**Comment by HackuJacku** [comment]
Sadly calling the old Warzone "broken" was an understatement. That old system will not come back in the future. I do encourage you to be constructive with the new version and make suggestions.
