### ISSUE TITLE
GTS not working properly, and now not at all.

### ISSUE THREAD

**Issue by NetherGoddess** [SmashMC-Development/Suggestions#750]
So earlier in the week the seller wouldnt get the money from any sales made on GTS and now GTS isnt working at all, cant click any of the icons. If yall would like the economy to stay stable, this needs to be fixed. Or ill start selling HAs at 10k

Which servers does this apply to?
all

**Comment by DinglePringleUwU** [comment]
Can confirm that. Multiple players had this issue and not a single player received the money. (Kyogre)
I would also suggest to set the default timer of the auctions from the plugin to 24H, as many players previously overlooked that and only put their sales up for 10 Minutes without knowing. 
This would especially be a quality of life improvement for new players with great synergy.

**Comment by HackuJacku** [comment]
This version of GTS will start to be phased out soon and replaced with a GTS which allows you to sell Pokémon/items to both players and the server itself. Zekrom will be trailing this and allow us to resolve discovered bugs.
