### ISSUE TITLE
Warzone price/ticket system 

### ISSUE THREAD

**Issue by Sadkeemstar112** [SmashMC-Development/Suggestions#757]
Hello i think most people on the servers can agree on that the warzone is to expensive and its not really what it is before. People on Rayquaza atleast dont go to warzone and its not that many pokemons or legendarys that spawn. I have never seen any of the tapus spawn, zeroara and other mons but that is not what this is about. I want to lower the price of warzone. Or make a new system like a ticket system or something so u buy a ticket for warzone but when u get defeated or leave warzone the ticket is used and u get on a coldown for 10 minutes. There is nothing wrong on the current warzone system the concept is good but its just a little bit to expensive for people to feel rewarded by going to warzone and risking their pokemons. And maybe make more legends spawn to attract more people i have been in warzone a lot but i have only gotten 2 legends. 
**Which servers does this apply to?**
All servers

**Additional context**
No :)

**Comment by HackuJacku** [comment]
Decreased the price.
