### ISSUE TITLE
Warzone

### ISSUE THREAD

**Issue by MarissaSins** [SmashMC-Development/Suggestions#758]
**Describe the suggestion**
Hey so after having been to wz and seeing other people comment on wz, most of us are in agreement that wz doesn't really feel worth it.

The timer is an amazing addition but, i feel like 10min is too short and the price is kinda harsh if you're gonna be going multiple times. The problem seems to be this has harshly decreased the amount of people going to wz therefore decreasing the spawn rates as well. Most complaints I see in chat are that there are no legendries spawning on ppl when entering wz yet there's always so many pokemon despawning. 

And well, the pokemon are despawning BECAUSE you can only be in wz for 10min!! By the time something finally spawns its likely you'll be kicked due to your timer running out. 

So I have a suggestion, it isn't 100% thought out or perfect but this system seriously needs to be rebalanced. My idea was that you need a general entry fee, 5k-15k range. After doing /safeplace, being battled or doing anything that causes you to leave wz, you will need to pay the entry fee again once the 10min cooldown ends after leaving wz. But I haven't quite figured out the timer part. Players shouldn't be in warzone for more than 20-25min, due to obvious reasons of camping incoming players, unlimited shinies/legends and other problems from last seasons wz. Other than that I'm not sure what else to suggest about changing the timer.

Either way thank you for making wz a bit better but I hope this helps bring an idea around editing the system some more.

**Which servers does this apply to?**
all servers

**Comment by HackuJacku** [comment]
The number of people don't impact the rates. The area is constantly loaded and is intended to spawn Pokémon even when players aren't there. We have changed the spawn system so that it significantly better around players than trying to spawn on the other side of the Warzone.

The price has been decreased and the entry cooldown has been removed.

**Comment by ghost** [comment]
Hacko most of the legends are still despawning because no one can find them. I would say 80% of the legend are it found in warzone.
