### ISSUE TITLE
Want to get people to stop complaining about wz

### ISSUE THREAD

**Issue by Lukeymac** [SmashMC-Development/Suggestions#759]
Make it 12.5k to enter, unlimited time no cooldown, this solves your eco problem and makes everyone happy. If you wanted you could also encourage battling by making it so how ever much score/elo you have makes the fee lower.

**Comment by HackuJacku** [comment]
These changes aren't just related to "eco problems", it's related to future-proofing. We've reduced the price but the limited time in the Warzone itself will remain.
