### ISSUE TITLE
Legends spawning mechanics in Warzone!

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Suggestions#763]
**Describe the suggestion**
Most of the time I have been in wz, it has been extremely difficult to find legends and that is assuming that they are even in wz. I think most of the time legends are not spawning in wz. Most legends you can just despawn without anyone finding them which you can probably check in server logs.  I have been to wz  a lot and tons of legends have spawned while I was there...but I have only evert caught 3. And believe me I searched the enitre wz (courtesy of /fly working before). I don't think that the new mechanics of legends not spawning around player is working. Please take a look into it, as it costs a lot to go wz and players are not getting much in return.

**Which servers does this apply to?**
I play on Groudon but I think it applies for all.

**Additional context**
I think legends should spawn around players in wz for it would be easier to find them.

**Comment by HackuJacku** [comment]
Same topic as #784 - see my response please.

**Comment by ghost** [comment]
This issue is completely different from the thread you have linked. I am saying 75-80% of legend spawns are bugged as in the legends are not in warzone. There is also a issue in the diversity of the legends that are spawning. I haven't seen a single landorus or tapus spawn.
