### ISSUE TITLE
Waiting Glitch is back

### ISSUE THREAD

**Issue by Lukeymac** [SmashMC-Development/Suggestions#765]
waiting glitch is back in wz and tournys idk how you guys keep breaking your code but its back

**Comment by HackuJacku** [comment]
It's an issue in the PixelmonMod itself, not on our end. As you would have seen if you read their changelogs, the main cause is gone but of course there will still be single case issues. If you come across these, you need to provide a **detailed** report so we can reproduce them. If we can't reproduce them, it won't get fixed.
