### ISSUE TITLE
Store Suggestions (Purchaseable Unbans)

### ISSUE THREAD

**Issue by Lukeymac** [SmashMC-Development/Suggestions#766]
I wanted to suggest adding Unbans to the smash store, it's essentially a purchasable thing like keys or ranks and for a set price a banned player can purchase it/one for a price to play again after having an appeal denied, This would give you guys another source of income and alow players a 2nd/3rd chance. Even if the player does go ahead and break the rules you will make another $x amount of money.

NOTE: THIS CAN BE FOR ALL BANNED PLAYERS OR EXCLUDE PLAYERS THAT HAVE BEEN PUNISHED FOR THINGS SUCH AS DOXXING/DDOSSING

**Comment by morrow12** [comment]
This would be nice, i agree on some bans cant be unappealable

**Comment by Rasgnarok** [comment]
No, we will not be making a 'get out of jail card' for money on our store. Behaviour cannot be remediated with money, and we won't take advantage of that either.
