### ISSUE TITLE
Rotom can't learn Pain Split from move tutor

### ISSUE THREAD

**Issue by Leamyyy** [SmashMC-Development/Suggestions#772]
**Describe the suggestion**

Rotom can learn Pain Split on showdown and can also learn it via tutor in generation 7 games. But when I visited a move tutor with the move it could'nt learn it. So could you make it so that rotom can learn pain split via tutors again?

**Which servers does this apply to?**

All servers

**Additional context**
![2021-11-13_14 18 41](https://user-images.githubusercontent.com/93057830/141645329-11391bf5-29d9-47d6-8d11-a5e31b658a02.png)

![2021-11-13_14 18 52](https://user-images.githubusercontent.com/93057830/141645333-c83e0c0d-0002-49b4-8d2d-b6e5a08dea03.png)

**Comment by HackuJacku** [comment]
This is a bug, not a suggestion. I'll add it to the master ticket though.
