### ISSUE TITLE
Let us sell items on gts

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Suggestions#776]
**Describe the suggestion**
Let people sell items into gts cause we can only put pokemon onto it.

**Which servers does this apply to?**
All

**Additional context**
 'N/A'.

**Comment by AngryRedHead101** [comment]
This would be so helpful and useful. I have lots of exp alls that i could sell off along with choice items and more

**Comment by HackuJacku** [comment]
Please read the latest changelog (22nd Nov), added.
