### ISSUE TITLE
Vote Links on both the Enjin-Website and ingame need an update

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Suggestions#781]
**Suggestion**
Update the links on: https://pokesmash.enjin.com/vote

**Description of Issue**
The Hyperlink for number 5 is: https://minecraft-server-list.com/
It should be https://minecraft-server-list.com/server/464847/vote/ for easier navigation, just like the actual ingame link.
(This only counts for the enjin page)

Change number 3 https://pixelmonservers.com/server/LWblHaxC/smashmc to https://pixelmonservers.com/server/LWblHaxC/vote
It's only an index tab away, but could be more user-friendly.
(This counts for both ingame /vote and enjin page.)

Link number 2 does not appear on the ingame /vote list. 
https://pixelmon-server-list.com/server/157/vote
If outdated remove from Enjin-Page for less confusion or add ingame if missing.

**Comment by Mikirae** [comment]
Fixed things showing the wrong link on Enjin and changed link 3 to the voting link itself, thank you! :)

I'll get someone on removing the Link 2 from the Enjin as that requires website design knowledge that I don't have.

**Comment by DinglePringleUwU** [comment]
Closed. This has been fixed long time ago.
