### ISSUE TITLE
Fire Heart Daily Quest is bugged

### ISSUE THREAD

**Issue by Leamyyy** [SmashMC-Development/Suggestions#782]
**Describe the suggestion**

The daily quest "Fire Heart" appears to have no quest, but has rewards.

**Which servers does this apply to?**

Rayquaza, but I think all servers

**Additional context**
![2021-11-15_23 18 39](https://user-images.githubusercontent.com/93057830/141862870-a4518991-ce91-443e-a002-06426a06ad16.png)

**Comment by Mikirae** [comment]
I'm looking into this, but in the future please be sure to report this to be Bugs and Issues GitHub instead, which is located here: 

https://github.com/SmashMC-Development/Bugs-and-Issues/

**Comment by Mikirae** [comment]
This SHOULD be fixed :D
