### ISSUE TITLE
Warzone Legendary Sapwning and Fix

### ISSUE THREAD

**Issue by AngryRedHead101** [SmashMC-Development/Suggestions#784]
I suggest that when a legendary spawns in warzone, it should be announced to the entire server, not just people in the warzone, It should also have a beacon light for about 3-5 seconds to give players a general direction to head in. This allows for more people to be in warzone at once and allows people to find the legendries that spawn which is a major issue.

**Which servers does this apply to?**
I think this should be implemented onto Kyurem first as a test run. Than if players like it needs to be added onto all servers. 

**Additional context**
Increase the time a legendary spawns in warzone. Legendaries despawn to quickly and therefore no one catches them. I have seen groudons, rayquaza's, melmetals, tons of ultra beasts, and most recently a mew despawn. The time a legend should stay in warzone should be the time a player can stay in warzone, 10 minutes.

**Comment by Killpod989** [comment]
this is agreeable. as many legends that spawn have "spawned" and players would be searching without seeing any part of the legendary. there would be no despawn message either for said mons. and many times have we seen legendary mons spawn and despawns seconds later.

**Comment by ScopesZero** [comment]
I agree. I have missed 8 legendries. and most of them were pretty big. (Palkia, and Dialga are big in size). There are too many mountains to climb over and little cave areas that are inaccessible without wasting a big amount of time. Having a beacon of light helps the player know the general area that the legendary is in, without fully compromising it's location.

**Comment by flubbci** [comment]
i completely agree

**Comment by CrownlessOcto** [comment]
I havent even caught one and I spent like 50k already ;-; for 10m non stop

**Comment by DinglePringleUwU** [comment]
I wholeheartly **disagree** with the idea of making it easier.

This would have a big impact on how many legendaries will circulate and how much they would be worth.
I went to warzone and caught both dialga and palkia in under one minute. It is RNG. You can get lucky.
Even _smoll_ pokemon like Jirachi/Lake trio were easy enough to find if they spawned at the right place at the right time.
It's perfectly Balanced at the moment. Even with the many legendary pokemon that suffocated in the walls i was able to fill one box full of legendaries with little time investment. _(Kyogre)_
Making it easier just for the sake of making it easier devalues everything in the long run.

However,
> "It should also have a beacon light for about 3-5 seconds"

This is indeed an excellent idea that is used in many pvp-games. It would work similar to an Airdrop/Beacon ect. 
If this would work with the given render distance, it would be one hell of an upgrade.

**Comment by ghost** [comment]
Spawning of legendary should definitely not be announced to the entire server. This was done to solve the problem of ppl sniping legs with throw teams and getting legs without having to take the risk of fighting. Only the ppl waiting in wz and spending their money to be there should know about the spawns as it is now. 

However, particle effect around legend or beacon to show general direction is a really good idea, as the legends spawning in wz are definitely hard to find if they are spawning at all in the first place.

**Comment by DragonBallBreakersRandomizer** [comment]
> The beacon part I agree with

**Comment by HackuJacku** [comment]
I'm sorry but we will not be adding this, it was removed because we wanted to stop players only going to Warzone when a legendary spawns. We will not be changing this back. Additionally, we won't be adding a beacon and or compass for the same reason - it was discussed but the majority decided against.
