### ISSUE TITLE
Pokehunt is op

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Suggestions#788]
**Describe the suggestion**
The "Hard" difficulty gives you every item from the Itempool. (all Plates + Rest)
The "Advanced" difficulty gives you every item from the Itempool. (All 8 held items + RC)
The "Easy" difficulty gives you every item from the Itempool. (All Power items + Rest)

**Which servers does this apply to?**
At least kyogre

**Additional context**
It is the "Easy" and "Hard" difficulty as far as i know. The others might be dysfunctional too.

**Comment by Mikirae** [comment]
Hacko fixed this. Thank you for reporting it! :)
