### ISSUE TITLE
/endbattle Taking away way too much time in Warzone

### ISSUE THREAD

**Issue by Sensouu** [SmashMC-Development/Suggestions#789]
**Describe the suggestion**
I ran into a ghost type, which happened to oneshot my lead, it never pulled up the pick a pokemon menu. Waited 3 minutes, and decided to /endbattle. Since what would the mods do? Just end my battle and erase the Pokemon I wanted anyway. After the battle ended it took away 5 minutes. Sure, I can understand why its implemented, but why punish players by hurting them with a glitch they can't control? I just think it's a little silly. You're already stuck in waiting which is taking away time, why take away more for trying to save yourself?

**Which servers does this apply to?**
I only play on Reshiram. 

**Additional context**
You can still remove time, I can't see why not, but with how Buggy Pixelmon is sometimes, there should at least be a little check to see if it's the player's fault or not

**Comment by WalkAway7** [comment]
Simply make a ticket, we can refund your warzone time if you provide logs, and how long you where in warzone.

**Comment by Sensouu** [comment]
Sorry Walk, not sure how to reply to comments, this site.. Is hard to use... 
But isn't that just an inconvenience on the mods? You give us a command to end a battle when it's stuck as it saves mod's time (I'd assume), but now... we still need to come bug you guys to save 2000$ worth of time..? Seems like getting rid of one thing to save another, especially when WZ is on a timer and not every mod is active at any given time. 
You're the boss though, it's just a Member's perspective of the ordeal. I just think 5 minutes is excessive, 1 or 2 minutes would be fine enough, gives you only 5-10 limits of end battle per max 10 minute run

**Comment by HackuJacku** [comment]
Endbattle still takes away time but significantly less.
