### ISSUE TITLE
The new /gts and how to make it better

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Suggestions#791]
**Suggestions for the new /gts**

**Increase the Max Price for Items**
Currently you can sell "single" items like papers for only 20.000 Coins Max. In most cases, this is not enough. Nobody will sell a Leg IV boost or a red chain or any megastone for 20k.
**Add more information for pokemon**
As of now there are no indicators that a pokemon does have its hidden ability. A (HA) next to the ability could help. For mew/lake trio there is no information on if its cloned/gemmed. These are crucial informations for the buyers.

**Applies to all Servers**

**Comment by Mikirae** [comment]
The prices will be fixed soon as it's not working the way we intend it to.

The other two suggestions are being looked into :)

**Comment by ghost** [comment]
I would like to add a suggestion of maintaining an "average price" of pokemon and items. This way new players can find out the approximate cost of items and pokemon.

**Comment by HackuJacku** [comment]
Fixed the pricing system from the next reboot.
