### ISSUE TITLE
Wz bank

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Suggestions#792]
As of now I'm not sure if there is a limit to the warzone bank, but I beat someone who had just caught a legendary and I had to scroll through many pages of mons in the bank before being able to find it and steal it. I suggest either adding a cap to the warzone bank or introducing a clear to peoples banks every --- hours to make sure they don't get clogged, otherwise you might run out of time before you even find the Pokemon you want in their bank

**Comment by HackuJacku** [comment]
Sadly this is not possible to do. We can however increase the duration of the steal bank is open, if that's the case, please create a NEW suggestion stating that.
