### ISSUE TITLE
Shadow Legend of Choice in SmashMC Store

### ISSUE THREAD

**Issue by MarissaSins** [SmashMC-Development/Suggestions#795]
**Describe the suggestion**
Hey! I noticed you can buy a random legendary for $13, and a specific legenday for $25. But looking at the textures section, theres only a choice to buy a random shadow legendary for $17. I would really love to see what a a shadow groudon looks like but I really don't want to get a shadow manphy or something dumb like that in the process. Considering the price change in the reg legend ones you could easily make it $30-35 and I think there would be people buying it, I know atleast I'd be interested. 

**Which servers does this apply to?**
Every server

**Additional context**
Also some shadow pokemons textures are broken, I'm sure you guys are aware of this and its a bit harder to fix that but figured I'd add that here while I'm mentioning shadow pokemon :]!

**Comment by Mikirae** [comment]
Thank you for the suggestion! After deliberating with the other members of the management team, we have decided that this is not something that we wish to offer at this time, unfortunately.
