### ISSUE TITLE
pokestop missing

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Suggestions#801]
**Describe the suggestion**
on Rayquaza the pokestop at the boat is missing

**Which servers does this apply to?**
Rayquaza

**Additional context**
NA

![image](https://user-images.githubusercontent.com/87021826/143896913-1664f246-e23b-40f7-bb3c-06af36e6b4cb.png)

**Comment by Mikirae** [comment]
This was fixed. Thank you for reporting it. Please use the bug reporting GitHub for things like this in the future! :D
