### ISSUE TITLE
Warzoen time

### ISSUE THREAD

**Issue by Dwag0n** [SmashMC-Development/Suggestions#805]
**Describe the suggestion**
you should have more time to steal pokemon from other players after beating them in warzone. or possible the more pokemon they have, the more time someone has to steal from them. People can currently Fill there bank with a lot of useless mons, so that people cant scroll in the 15 seconds fast enough to steal the good pokemon they have caught in warzone.

**Which servers does this apply to?**
all with wz

**Additional context**
N/A if i get screenshots of people with a lot of mons in there bank will add here

**Comment by Mikirae** [comment]
It has been increased to 25 seconds following the next server restart :)
