### ISSUE TITLE
longer stealing time

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Suggestions#813]
**Describe the suggestion**
When you beat someone in warzone i would like it if u had longer to choose one of their mons. Right now its 15 seconds i believe and i feel like that barely gives you time to properly look at someones mons

**Which servers does this apply to?**
All

**Additional context**
NA

**Comment by ghost** [comment]
Agreed.

**Comment by Mikirae** [comment]
This is something that we're doing very soon :)

**Comment by Mikirae** [comment]
The time has increased to 25 seconds starting on the next restart :)
