### ISSUE TITLE
Ivs in GTS are glitched

### ISSUE THREAD

**Issue by SasukeMK2** [SmashMC-Development/Suggestions#815]
**Describe the suggestion**
The ivs in gts are displayed wrong. im selling a bp rayquaza in reshiram and it has 31 atk and spd as its ivs but the gts says its atk ivs are 15 when those are actually its hp ivs. id appreciate it if you guys could look into it and get it fixed because if it isnt, im not going to get a fair price on my mons.

**Which servers does this apply to?**
as far as i know, its on all servers.

**Comment by Mikirae** [comment]
I'm looking in the config, and it all looks fine on our end? Even tested it with some mons in the server and it was fine there as well.

**Comment by Mikirae** [comment]
Heard from others that it's fine as well, so I'll be closing this.
