### ISSUE TITLE
remove these moves in warzone plz

### ISSUE THREAD

**Issue by SenpaiCantAim** [SmashMC-Development/Suggestions#817]
This wasn't enough to be an 'issue' so ima make a suggestion, move combo of mind reader and sheer cold should be removed from warzone. A pokemon with this move combo can get least 1 or 2 free KO in every battle and its just shouldn't be allowed in competitive pokemon battling. Sheer cold is a 1 hit KO move with very low hit rate so this alone isnt a problem as such, however if you use mind reader before using sheer cold it will ALWAYS hit meaning you will 100% lose 1 maybe 2 mons to a 1hit ko move typing not effecting the 1 hit ko.

**Comment by Mikirae** [comment]
Removed for next restart :)
