### ISSUE TITLE
Please balance the Shrines

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Suggestions#819]
**Describe the suggestion**
Currently the Shrines are an unbalanced mess. Both the wild ones and the ones in the spawn as you have to pay a daunting fee for both after the first free use.

>Timespace Altar
You pay 80.000 coins to summon a pokemon (Palkia/Dialga/Giratina) that spawns way to frequently in warzone and is beeing sold for 20-30k on GTS. with items that consists of either all three rubies or all 17 different plates.
Additionally it costs 100.000 coins to produce the Azure Flute on the Chalice shrine. The price of an arceus ranges from 30-50k on GTS.
The plates are not being sold on GTS. There is no demand for them. 

>Bird Shrines
You pay 50.000 coins to summon a pokemon that spawns even more frequently in warzone and that is beeing sold for 7-10k on GTS. This also makes the item "Orb" worthless and undesireable.
 
>Illex Shrines
While beeing rather expensive with 60.000 coins (Twice the amount a celebi is being sold on GTS), this shrine is more or less balanced as the number of spawned Celebis in warzone is lower than Moltres/Zapdos/Articuno/Palkia/Dialga/Giratina/Arceus spawns.

**The implications**
There is another problem that came up with this change. Players are claiming up every single shrine they come across in hopes of selling the free one-time-use one day. I've seen quite a sad scene yesterday in which a newly returning player found an articuno shrine and euphorically wrote about it in main chat, this resulted in another player trying to tp to him. He accepted the tp (He was a returning player that did not know about the change). The player that teleported to him claimed the shrine immediately resulting in the returning player being discouraged. I know this because i /msg'd him and asked about the situation he found himself in afterwards. 

**Which server does this apply to?**
Every Server.

**Possible Solutions**
The current state is not healthy. It does not drain the currency of the server as nobody is using them, its making people fighting over wild shrines, its far too expensive and it renders the summoning items (Orbs/Plates/Rubies) worthless for the Player market. (Tho i can only say that for the Kyogre server)

- Reduce the shrine Fee significantly or remove it completely to make it easier for new people (After all you still need the summoning items)
- Or reduce the wz spawns of the respective shrine pokemon to make the shrines worth the investement
- Or remove the Fee from wild shrines

**Comment by Mikirae** [comment]
Sorry it's taken so long. This one ended up falling through the cracks even though it was on my initial patching list. Hopefully in the next couple days we'll have something better in terms of Shrine prices, as I agree, it's way too expensive right now :(

**Comment by DinglePringleUwU** [comment]
Perfectly balanced now! Good work! Woop Woop! :) :)

**Comment by Mikirae** [comment]
Aye appreciate the kind words :D

**Comment by ghost** [comment]
Prices not fixed after restart on Groudon.
 
Update : Prices are fixed....text above shrines show the old price though.

**Comment by Mikirae** [comment]
Oh, I forgot it said that. I'll change that. Thank you!

**Comment by Superfire96** [comment]
The text above the shrines is now fixed
