### ISSUE TITLE
Add the breeding kit book back to the server,

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#820]
**Describe the suggestion**
While having a free ranch block is cool, the main feature that the breeding kit was  providing is the book with all the information necessary for breeding, which now isn't there anymore, it was such an under estimated feature but with so much value that helps every new player. 

**Which servers does this apply to?**
Everyone

**Comment by DinglePringleUwU** [comment]
That guide was so helpful when i was new!

**Comment by ghost** [comment]
/breeding has the breeding guide I think
