### ISSUE TITLE
Add ranks and colored names in Tab Menu

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Suggestions#821]
**Describe the suggestion**
Add ranks and colored names in Tab Menu. It makes it easier to identify who is online especially for newer players. Staff definitely needs it because it helps identify them.

**Which servers does this apply to?**
All.

**Comment by HackuJacku** [comment]
Implemented from the next reboot

**Comment by ghost** [comment]
Nice! Thank You!
