### ISSUE TITLE
gts bug

### ISSUE THREAD

**Issue by Ahiha2** [SmashMC-Development/Suggestions#835]
the bug is that when I try to list items instead of sending to the gts tab it lets move the items 
![image](https://user-images.githubusercontent.com/93155583/146782994-2e97031b-f1a6-4506-82ae-fd46cca486c5.png)
![image](https://user-images.githubusercontent.com/93155583/146783058-f2b18ab3-7d20-44d3-95af-34eefc396672.png)

**Comment by Mikirae** [comment]
This is a rare glitch that happens with a bunch of GUIs. It's typically fixed by relogging. Is the issue still occurring to you?

**Comment by HackuJacku** [comment]
Fixed
