### ISSUE TITLE
Trapping Abilities!

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Suggestions#842]
**Describe the suggestion**
I don't understand why trapping abilities like arena trap, shadow tag etc are banned in wz when all the ubers are allowed....just doesn't make sense.

**Which servers does this apply to?**
Groudon

**Additional context**
NA

**Comment by Mikirae** [comment]
Not sure that's on purpose. Let me go ask here.

**Comment by Mikirae** [comment]
Fixed this. Thank you for suggesting it :)

**Comment by ghost** [comment]
Saw the changelog....Thanks!
