### ISSUE TITLE
Make /endbattle available for every rank

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Suggestions#844]
**Describe the suggestion**
Currently non-store ranks such as trainer/Expert/Veteran/Ultra can not use /endbattle to free themselves from a stucked wild/trainer/raid encounter. It shows that they dont have permission for that. At least Legend and Smash rank does have access to that command. Tested that. 
I do not understand why this is only for /buy ranks. Maybe it is not intended to be like that, judging by how it was not that way before. It would improve the playing quality for new players greatly if they would not have to ALT+F4 everytime that happens.

**Which servers does this apply to?**
At least Kyogre.

**Additional context**
I am only talking about ending the own battle. Not other players battles. Just to clarify.

**Comment by Mikirae** [comment]
I don't know why Legend and Smash would have access to it but others don't? I see in my personal changelog that I gave it to default rank on every server. 
Regardless, I gave it to everyone on Kyogre now. Thank you for reporting this! :)
![image](https://user-images.githubusercontent.com/24925669/147532465-34a5a913-7329-43f9-8523-9369f37068b7.png)
