### ISSUE TITLE
Bosstower

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Suggestions#847]
Remove gems, fossils and berries from the loot table in the bosstower. Would make bosstower much more usefull, since this is the only drops u get. As of right now I do not think anyone uses the bosstower, which is a shame considering how many hours was used to build it.

**Comment by ghost** [comment]
Agreed!! 💯

**Comment by Chowlien** [comment]
Agreed, along with a high spawnrate

**Comment by Rasgnarok** [comment]
Higher spawnrate and reworked rewards have been added, closing.
