### ISSUE TITLE
Suggestion for WZ

### ISSUE THREAD

**Issue by Lukeymac** [SmashMC-Development/Suggestions#848]
**Describe the suggestion**
Make an announcement type thing for hidden ability mons in wz like legends, This wouldn't be op because in how the message would read it would say something like "A Hidden Ability ((Ability)) pokemon has spawned" so it's not too specific but specific enough

Example for slowpoke: "A Hidden Ability (Regenerator) Pokemon has Spawned" it's not too specific because multiple mons have that ability (slowpoke Evo line, toxapex Evo line, foongus Evo line and more) I think it would be a nice addition to wz.

**Which servers does this apply to?**
All

**Comment by HobnobberJunior** [comment]
I do not think this is a good idea. Then people will just sit and afk until one spawns. I think it ruins the "hunt" for ha mons and makes it a bit too easy since you narrow it down pretty easily.

**Comment by RatedPG21** [comment]
I agree that this shouldn’t be a thing. Hidden ability Pokémon are suppose to be rare and with this, they will become to easy to encounter

**Comment by arjungangwar0** [comment]
mhm guys read carefully. I said "announcement on catching".

**Comment by ghost** [comment]
lol ignore that last comment. This should definitely not be a feature. However, there should be an announcement in chat when someone catches an HA in warzone which is being added I think. That would prevent throw teams and people will actually have to defend the HAs they catch in warzone.

**Comment by Chowlien** [comment]
It would make HA hunting obsolete, big no

**Comment by Mikirae** [comment]
As others have stated, this would be a bit overpowered and ruin a bit of the grind. Thank you for the suggestion, though! :)
