### ISSUE TITLE
Make star pieces sellable

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Suggestions#85]

**Comment by jahangir6969** [comment]
What server?

**Comment by Lun17** [comment]
Pixelmon, all of them also pearls, normally those are items you can sell
for an high price in the original games.

Il lun 10 mag 2021, 18:56 jahangir6969 ***@***.***> ha
scritto:

**Comment by Mikirae** [comment]
This is something that we could implement if we get a weighted boss loot table.

**Comment by HackuJacku** [comment]
Added to the master economy ticket.
