### ISSUE TITLE
Shrines at spawn

### ISSUE THREAD

**Issue by ghost** [SmashMC-Development/Suggestions#850]
**Describe the suggestion**
In my opinion, shrines are currently a little too expensive. Prices should definitely be reduced.

**Which servers does this apply to?**
All.

**Additional context**
NA

**Comment by Mikirae** [comment]
A bit late for me to be closing, but this is done and the holograms will be fixed as soon as we fix a bug with that plugin :) (Although I'm sure you know already because you've commented on it lol)
