### ISSUE TITLE
Breeding cap

### ISSUE THREAD

**Issue by SenpaiCantAim** [SmashMC-Development/Suggestions#852]
I believe having a breeding cap is a good idea however at the same time having only 10 breeding pairs at one time slows down the process too much I think, minimum of 12 pairs I think should be about right allowing you to breed 2 different teams which is reasonable. However I kind of would like to see the breeding cap gone or increased to around 20-30 which seems a lot but for me and a lot of other players I'm sure that's still low. I would just like to suggest a increase of some sort even if it was by 1 pair that would be better then only 10 :)

**Comment by HobnobberJunior** [comment]
I totally agree on the breeding cap being higher than it is now. I do however think 20-30 might be a little too high. I breed a lot of different mons and sometimes it can really take ages if you are trying to breed more than 1 or 2 mons at a time. I do think the limit of 10 pairs is too harsh on the breeding aspect of the game.

**Comment by DinglePringleUwU** [comment]
I strongly disagree on this and you should be too.
Having 12 breeders to work on two different teams does not sound like a bad idea. However...

The reasoning to have enough space for two teams might sound logical, but what if another player asks the same afterwards with something along the lines of: "Add a 13th breeder so we can have an additional ditto-breeder for making female ha's while working on two teams"? Still sounds logical.
And what if another player afterwards asks something along the lines of: "why only allowing 13 breeders? That makes no sense. Allow 18 so we can work on three different teams." Still sounds logical.
And so on.

The cap is perfectly fine. I like breeding and never had any problems with only having 10 pairs yet. Allowing more could lead to a weaker breeding eco. The Breeding eco is surprisingly strong btw. 

**But consider this**
Look at the Breeding eco of Rayquaza. It is weak and cheap enough to discourage any breeder from breeding. One of the possibly logical reasons for that could be the large number of players on them. 
More people breeding/More Breeding space for people = Weaker eco on breeds

And do not forget that more breeding slots would affect /sts (When it's back).

**Comment by Mikirae** [comment]
I have to agree that this would result in a blow to the economy as it would be far easier for people to grind out endless amounts of Pokemon. Thank you for the suggestion, though! :)
