### ISSUE TITLE
Elite 4 Senior

### ISSUE THREAD

**Issue by borkborkdog** [SmashMC-Development/Suggestions#853]
**Describe the suggestion**
Elite 4 seniors should have the capabilities to give/take elite 4 perms and tags

**Which servers does this apply to?**
All servers

**Additional context**
Would take a lot of stress off the managers as they are very busy

**Comment by Rasgnarok** [comment]
I appreciate the concern, but at the end of the day, giving and taking these permissions is an admin-level authorization, like promoting anyone to staff.
