### ISSUE TITLE
Joining Warzone announcement 

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Suggestions#857]
**Describe the suggestion**
I think it would be better if the announcement when someone joins warzone is removed. The whole point of warzone is to fight, giving the server a competitive side, but you can’t really fight if every time you enter warzone it’s announced and everyone either safeplaces or runs away.

**Which servers does this apply to?**
Groudon, maybe all

**Comment by HobnobberJunior** [comment]
I agree. People will just instant /safeplace if they see someone enter. Kinda makes it impossible to fight people.

**Comment by DaniloJonko** [comment]
yes i've had mutible ppl /safeplace on me or just log out in general when they see other ppl join the warzone

**Comment by Mikirae** [comment]
Talking it over with management and will let you guys know :)

**Comment by Mikirae** [comment]
This will be done upon the next Warzone update in the coming days. Thank you for the suggestion :)

**Comment by Rasgnarok** [comment]
Closing, has been added to Warzone.
