### ISSUE TITLE
Add recording battles to wz rules 

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Suggestions#859]
**Describe the suggestion**
In situations where people need to rebattle in wz, there is no way to tell whether players are using the same teams. Perhaps it would be a good idea to add this suggestion of recording wz battles to wz rules so in rebattles players will not argue over who is using the same teams. 
**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.
all servers
**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
A lot of people don't have the ability to record, so I like the other suggestion better and will be closing this one :)
