### ISSUE TITLE
Rank Transfer Suggestion

### ISSUE THREAD

**Issue by DaniloJonko** [SmashMC-Development/Suggestions#863]
Hello,

I've been playing this server since last reset on Deoxys with some friends ( Dxhcky and Snorlax ) 
Now we play on groudon but the playerbase on groudon is going downhill and for me there are 15 people online rn and no competion    since Dxhcky changed to rayquaza because there is an active playerbase on ray. now do i want to change to Rayquaza aswell. but i have smash rank on groudon and no rank on rayquaza. i would like there to be a way for me to get my rank transferred to rayquaza, i it would be awesome if u guys did a rank transfer, now unfortunately u guys don't do that, now do i have a suggestion for the buy store, if u guys add like a rank transfer so we can change our rank from one server to the others for like $20

Let me know if u agree or if u would change something but i think a rank transfer should be available,

**_-Danilojonko_**

**Comment by ghost** [comment]
Something like this would be a nice add.

**Comment by HackuJacku** [comment]
As a Management Team, this is something we've decided not to do sadly. We''re sorry for the inconvenience.
