### ISSUE TITLE
Player Backups

### ISSUE THREAD

**Issue by llnama** [SmashMC-Development/Suggestions#865]
**Describe the suggestion**
My Inventory just got wiped, and there was no way of getting the items back because of a lack of proof. Adding either a backup mod or plug-in would be a lifesaver! It's only server-side and would encrypt everything so it wouldn't consume that much storage!

**Which servers does this apply to?**
All

**Additional context**
N/A

**Comment by HackuJacku** [comment]
We take daily backups of the server as a whole, these need to be restored manually. To the level you're taking about, it's not feasible.
