### ISSUE TITLE
Make /r reply to the person you just messaged

### ISSUE THREAD

**Issue by llnama** [SmashMC-Development/Suggestions#870]
**Describe the suggestion**
Make /r reply to the person you just messaged, not the most recent person who messaged you.

**Which servers does this apply to?**
All

**Additional context**
Every other server does it this way.

**Comment by Mikirae** [comment]
Servers that run on Spigot have different alternatives. Unfortunately here, this is quite literally the only option I have regarding a reply:
# Send a message to the last player that sent you a message.
reply {
    # Sets whether a command is enabled.
    enabled=true
So, this is unfortunately not possible, but thank you for your suggestion :)
