### ISSUE TITLE
Ability capsule

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Suggestions#871]
I breed a lot and I breed quite a few HA mons. However people do not always want the hidden ability. The problem is that I can´t use a ability capsule to change it from HA to non HA, which you could do before reset. It would suck a bit to be forced to make use two different breeding stations just to get a HA and non HA version. Is there a way to change it so we can use an ability capsule to change from HA so non HA of course without the ability to change it back again. It would make things a whole lot easier.

All servers

**Comment by HobnobberJunior** [comment]
Just to add to this. If its a mon with a gender ratio like the starters, this feels even worse, since you will have to start from the beginning.

**Comment by Mikirae** [comment]
The ability to change it from HA to non HA was a Pixelmon bug. Per the rules of Pokemon:
"The Ability Capsule can only be used on a Pokémon that belongs to a species that has two standard Abilities. ... It also cannot be used to change a Pokémon to or from its species' Hidden Ability."
So unfortunately we can't do that. Maybe in the future we could find a different way to change the ability, but we can't tap into the item itself.
Thank you for the suggestion, though :)
