### ISSUE TITLE
builder application might need a bit of updating

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Suggestions#872]
**Describe the suggestion**
The builder application might need a bit of updating. It still says all the old servers instead of the servers post-reset

**Which servers does this apply to?**
the builder app

**Additional context**
![image](https://user-images.githubusercontent.com/87021826/148924015-7e4db965-3718-4bca-a1a9-5a0aa6497021.png)

**Comment by HackuJacku** [comment]
Updated
