### ISSUE TITLE
Max claim blocks

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Suggestions#875]
Might be a wierd request, but here goes. Increase the max claimblocks for one person to more than 80k claimblocks. We are currently building a town on kyogre that has reached the max claim size and we are planning on expanding. We made it as one big claim and have reached the max claimblocks for the person who owns the claim. Would be very nice if this limit could be increased.

**Comment by Mikirae** [comment]
While I appreciate you wanting to build a big town, this a relatively niche scenario so I don't believe that we're going to be increasing everyone's claimblocks for this. 

Thank you for the suggestion, though!
