### ISSUE TITLE
Subclaims

### ISSUE THREAD

**Issue by HobnobberJunior** [SmashMC-Development/Suggestions#876]
Increase the number of subclaims from the /subdivideclaims command, so it is possible to make more than 24. Related to suggestion #875.

**Comment by mDerinho** [comment]
I agree, good for towns, communities etc.

**Comment by Mikirae** [comment]
I can look into this in the coming days :)

**Comment by HobnobberJunior** [comment]
This ticket however will be a little irrelevant, if suggestion 875 is not possible. Will have to come up with another solution for both, if there isn't a way I can increase the claim limit sadly.
