### ISSUE TITLE
An guy who sells competitive items at warp mart

### ISSUE THREAD

**Issue by Firemelon66** [SmashMC-Development/Suggestions#886]
Like an guy who sells z-crystals and items like heavy duty boots or mental herb or light balls so at all items which are useful for competitive in an reasonable price range for the item itself for every server

**Comment by Firemelon66** [comment]
And maybe at the same to patch that you dont lose items like white herb against wild mons

**Comment by WalkAway7** [comment]
White herb is a one time usage thing, like the gems. So I don't think it's possible to make it so that wild encounter don't destroy the herb

**Comment by Mikirae** [comment]
Walk is right about your second suggestion.
As for your first one, we have decided against that to encourage using the other ways of obtaining items to get the respective battle items that you need. 
Thank you for suggesting, though :)
