### ISSUE TITLE
Leveling up pokemon to lvl 100 in /warp training

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Suggestions#888]
Leveling up pokemon is tedious but rewarding, but limiting the levels (1-80) in the /warp training area is hindering or at least slowing down the level up process.
There should be another room where we can level up pokemon from level 80-100.

OR

Another option is revamping how we raise levels of pokemon. by putting an NPC with nothing but chanseys/blisseys with no moves other than healing wish, that would have a higher yield for gaining EXP., vastly increasing the time to train pokemon/s (if the EXP All is activated).
This would decrease the time players would spend training their pokemon to level 100.

OR

Replace all the pokemon in /warp training into Chansey and Blissey with nothing but Heal Pulse and Tail Whip for the move pool

**Comment by Mikirae** [comment]
The first option is something that we are considering and is already on my list of things to discuss with people, but the second two options are far too overpowered and we don't have any wish to put something like that on the server, unfortunately.
I will be closing this suggestion though, as I already have the first one on my list. Thank you for suggesting things! :)
