### ISSUE TITLE
ranks and eggs

### ISSUE THREAD

**Issue by Linkolnisgood** [SmashMC-Development/Suggestions#896]
There should be a way to convert your rank from one server to another as buying i feel buying multiple ranks for the same overall server is quite costly, also there should be a ./eggsteps (slot) command as it is very helpful to the breeders or just for anyone with an egg. It is more convenient.

**Comment by Linkolnisgood** [comment]
you not think paying 50 just for eggsteps is not too much? it just milks money

**Comment by jantjewieger** [comment]
I don't mind knowing how many steps are left on my eggs seeing as i never use the command anyway. Besides seeing as its not a necessity but a perk i think its only fair to have access to it from a paid rank.

**Comment by Linkolnisgood** [comment]
alright then but wb the ranks thing?

**Comment by jantjewieger** [comment]
I mean i only play on reshiram. So once again i don't mind it

**Comment by Linkolnisgood** [comment]
but other people play many servers

**Comment by jantjewieger** [comment]
Which makes it an opinion of a small portion of Smash. Just up to the managers to agree/disagree with it then

**Comment by HobnobberJunior** [comment]
I think /eggsteps should be available for everyone, there isnt a reason to make it a paid rank perk since it doesnt do anything.

**Comment by jantjewieger** [comment]
I mean clearly u guys want access to it so it doesn't do nothing. In my eyes, if i were a manager, it only makes sense to put it in a paid rank seeing as its something to get people to buy a rank. For example i bought my rank bc i wanted access to /breed and /hatch

**Comment by HobnobberJunior** [comment]
Yes but theyre actually usefull commands. I have access to /eggsteps but I do not use it. It is mainly new players wondering how hatching works. I do not see the reason not to do so. There is a vast difference between /eggsteps and /hatch or /breed.

**Comment by Mikirae** [comment]
We have discussed both of these things in the past and unfortunately do not have any plans to implement either of those suggestions at this time.
Thank you for the suggestion, though :)
