### ISSUE TITLE
Zygarde Shrine

### ISSUE THREAD

**Issue by HackuJacku** [SmashMC-Development/Suggestions#9]
Allows players to get a Zygarde without getting the cells.

**Comment by Mikirae** [comment]
I believe Waterdude is going to eventually working on something for this, but what if we get a Zygarde Core as a shrine at spawn that they can summon Zygarde with. We could make custom items to summon it, I think that would be cool and unique.

**Comment by HackuJacku** [comment]
Implemented on the upcoming reset!
