### ISSUE TITLE
A 'common' warzone

### ISSUE THREAD

**Issue by Dxhcky** [SmashMC-Development/Suggestions#900]
**Describe the suggestion**
I saw this idea in #general. What a 'common' warzone would mean is a warzone where every subserver is connected, meaning once you enter, you are up against people across the whole network. I am not sure if this is possible, however, but there might be a way if warzone becomes its own subserver which you get sent to once you join, similar to doing /rayquaza or /groudon, but you can only join if the specific requirements are met. If possible, this would make it so that warzone is the same for all servers and so warzone will thrive on all keeping a higher player base and a few more happy players. This would also make warzone more competitive and it could make it far more entertaining than it already is too. 

**Which servers does this apply to?**
All

**Comment by Mikirae** [comment]
This was suggested before, but it was determined that each server would have its economy affected by doing this, I believe.
Think we realized that it could essentially make a universal economy in the sense that any HA caught on any server would inevitably wind up on all of the others, along with the fact that people could simply move their Pokemon to a different server via Warzone transfer. 
We did consider just making them unbreedable and untradeable, but that didn't seem very poggers champion.
Thanks for the suggestion though <3
