### ISSUE TITLE
perms in warzone

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Suggestions#903]
**Describe the suggestion**
Please give access to /wiki and /pwiki in warzone. The /wiki will come in handy when trying to HA hunt. Ppl might not know the HA of a pokemon but with /wiki torchic ha they can find out what the HA is of torchic while in warzone without having to look it up. /pwiki will give more insight in to when certain pokemon spawn. I was trying to complete my bingo card in warzone but there is no way to check when they (the pokemon i still need) spawn while im still in warzone.

**Which servers does this apply to?**
I mean i play on Reshiram but probably for all

**Additional context**
N/A

**Comment by Mikirae** [comment]
/wiki would be fine, but I believe there are issues with closing people out of GUIs to battle, so /pwiki would be a no go there.
 
That being said, /wiki will be in for next restart.
Thank you for the suggestion :)
