### ISSUE TITLE
Gym waiting time glitch

### ISSUE THREAD

**Issue by SiennaAffliction** [SmashMC-Development/Suggestions#908]
**Describe the suggestion**
Something else needs to be in play when the infinite waiting glitch happens other then end battle and wait for the time to reset. 
Twice in the span of 24 hours has the infinite waiting glitch happened to me, and all anyone can do is cancel the battle.

At least add a little compensation or something when this happens, this games fun, the servers pretty cool but there's nothing more annoying then spending so long training to fight the gym or waiting for the reset just to have the gym fight fail because of a glitch.

**Which servers does this apply to?**
This has happened on the groundon and kyogre server for me, but i'm sure it happens in all of them.

**Additional context**
N/A

**Comment by Rasgnarok** [comment]
https://github.com/SmashMC-Development/Bugs-and-Issues/issues/1120
