### ISSUE TITLE
Evolution Stones

### ISSUE THREAD

**Issue by jantjewieger** [SmashMC-Development/Suggestions#910]
**Describe the suggestion**
Add all the evolution stones to /warp mart please. Im trying to dig something out for a build. But without thunderstone armour it just takes too long. Usually i'd go search for some thunder stone shards, but all the blocks have already been mined (went to 4 different extreme hill biomes). Because of this its pretty much impossible to get some armour/tools nowadays. So please add the evoltion stones to /warp mart so i can buy some

**Which servers does this apply to?**
All

**Additional context**
N/A

**Comment by Superfire96** [comment]
They were added
