### ISSUE TITLE
wz suggestion

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Suggestions#915]
**Describe the suggestion**
Add a way to hide your entry into warzone, either rank perk, increasing entry fee or something.

**Which servers does this apply to?**
all pixelmon servers

**Additional context**
kind of tired warzone favoring people that run away just because another player enters warzone. it is called warzone so it should favor people that look for battle, not players that hide and run.

**Comment by Mikirae** [comment]
Needed a plugin-side change for this to be done, but Warzone announcement is removed for next restart :)
