### ISSUE TITLE
Im on the server groudon my ign is Reesegonecrazy and evryone on the server is banned on wz for over 1000 hours

### ISSUE THREAD

**Issue by Reesegonecrazy** [SmashMC-Development/Suggestions#924]
**Describe the suggestion**

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by Mikirae** [comment]
Fixed. Thank you! :)
