### ISSUE TITLE
Change emojis

### ISSUE THREAD

**Issue by RatedPG21** [SmashMC-Development/Suggestions#929]
**Describe the suggestion**
Would look nice if you could change these emojis

**Which servers does this apply to?**
Discord

**Additional context**
![CEEB8F86-ED0A-4595-9F43-F37F83DB697C](https://user-images.githubusercontent.com/90443761/155837405-27fc2c1a-1f7d-4e15-9bbb-219247763bd2.jpeg) any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by RatedPG21** [comment]
Change these into those
![DBB8EACB-DD24-4330-863B-882DAD09170B](https://user-images.githubusercontent.com/90443761/155837417-5108c082-4ba6-45c6-a5e0-64372c1d07fc.jpeg)

**Comment by Rasgnarok** [comment]
Sadly can't, these emotes need to be compatible with the display - and channel names are not parsed as chat is.
