### ISSUE TITLE
Make WZ great again

### ISSUE THREAD

**Issue by HarshilM67** [SmashMC-Development/Suggestions#934]
**Describe the suggestion**
I believe was shall be free, and that wz should be fully free for all with no limitation on teams.
**Which servers does this apply to?**
All Servers
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.
N/A

**Comment by HarshilM67** [comment]
Wz should be free**

**Comment by DragonBallBreakersRandomizer** [comment]
I belive sleep and minimize should be added back, but no the duplicate mons one due to the new arceus plate coming and you'll regret it lol

**Comment by Firemelon66** [comment]
I dont think they should minimize and evasion again since its way to annoying and broken its just for assy ag users to get even stronger then they are already

**Comment by Rasgnarok** [comment]
Sleep clause is now added to Warzone, closing.
