### ISSUE TITLE
gravel

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Suggestions#950]
**Describe the suggestion**
Add Gravel to block shopkeeper npc

**Which servers does this apply to?**
All pixelmon servers

**Comment by Mikirae** [comment]
Please suggest this over on our Suggestions GitHub. This is for Bug Reports
https://github.com/SmashMC-Development/Suggestions/issues

**Comment by Mikirae** [comment]
I realize now that I'm actually an idiot and didn't realize I switched GitHubs. Ignore me

**Comment by Superfire96** [comment]
Added
