### ISSUE TITLE
Disable the Use of /evofix in tournaments

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Suggestions#952]
Getting random pokemon in tourney makes the event fun and you really have to know how to use your mons in team, but that is thrown out the window once it evolves. Furthermore, in tourney that has 3 players playing, one of them would have to sit out the battle, this means after the first round the winner of the first 2 players would have all lvl 100 pokemon in the team, AND would have ample time in DOING /EVOFIX ALL HIS POKEMON if possible. this make the next match very unfair for the person who didnt battle

plz remove the ability to do /evofix in tournament battles IT IS UNFAIR FOR ALL PLAYERS INVOLVED imo

**Comment by Mikirae** [comment]
This is something that would be great to remove, but unfortunately we need a developer who has access to the source code for tournaments in order to prevent this. We're currently looking for someone, but no promises, unfortunately.

**Comment by Mikirae** [comment]
Done for next restart :D
