### ISSUE TITLE
Custom Textures link is broken

### ISSUE THREAD

**Issue by Cahiller18** [SmashMC-Development/Suggestions#956]
**Describe the suggestion**

**Which servers does this apply to?**
Please provide a list of which servers you'd like this suggestion to be implemented on.

**Additional context**
Add any other context or screenshots about the feature request here. If nothing, please add 'N/A'.

**Comment by RatedPG21** [comment]
Please follow the format provided

**Comment by jantjewieger** [comment]
Cahiller id make a bugs and issues github abut this. U now made a suggestion github and this is thus in the wrong section of our github

**Comment by Mikirae** [comment]
If this is about the one in the #smashmc-info channel on the Discord, I've fixed that :)
If it's something else, please put it in the bugs section!
