### ISSUE TITLE
Change Max Price of "Pictures"

### ISSUE THREAD

**Issue by DinglePringleUwU** [SmashMC-Development/Suggestions#958]
**Describe the suggestion**
Change the Maximum set price of pictures (Those that can be obtained with cameras) on /gts to 500.

**Which servers does this apply to?**
All Servers but Vanilla

**Additional context**
Many players rename their pictures in order to make it look like they sell a legendary or shiny pokemon for a good price.
Especially new players can and already did fall for these scams. By changing the maximum price on /gts, people could not profit from this scamming method anymore and thus would stop doing it. 
There is no reason to sell any pokemon picture for more than 500 Coins.

**Comment by jantjewieger** [comment]
This would be good tbh. Would deal with some of the scam issues regarding these

**Comment by Mikirae** [comment]
I like the idea. I’ll take a look at this tomorrow :)

**Comment by Mikirae** [comment]
Done for next restart. Thank you for suggesting! :)
