### ISSUE TITLE
Bands in Warzone

### ISSUE THREAD

**Issue by llnama** [SmashMC-Development/Suggestions#959]
**Describe the suggestion**
With the change to warzone, what happens is that only the dynamax band gets disabled whenever someone enters wz. I don't know if it's just me, but I always forget to equip the Megaband before or whilst in there and only remember mid-battle. Therefore, it would be quite helpful, upon entering the warzone, if the megaband was automatically equipped (if the player has it) whilst the dmax band is unequipped.

**Which servers does this apply to?**
All Servers

**Additional context**
It could just be my clumsiness forgetting to put it on tho.

**Comment by Mikirae** [comment]
I like this idea and I'll see if we can get something made!

**Comment by Mikirae** [comment]
This is done for the next restart :)
