### ISSUE TITLE
Move Relearner can't relearn egg moves

### ISSUE THREAD

**Issue by IAmF3rdie** [SmashMC-Development/Suggestions#962]
As the title suggests, the move relearner apparently can't make a pokemon relearn its egg move despite the pokemon knowing the egg move.

So I have a scorbunny with the egg moves High Jump Kick, Iron Head, and Sucker Punch, and i accidentally forgot HJK for Pyro Ball, i tried to relearn it in the move relearner, but its not showing at all.

The whole point of the move relearner is to make a pokemon re learn a move IT ALREADY KNOWS. I'm pretty sure that this is a glitch in the NPC tbh. Plz fix this, ty in advance

Oh yea, so far this is happening in Reshiram, im not 100% sure if it happens in other servers too

**Comment by jantjewieger** [comment]
Ferdie im not sure whether or not this is a glitch or intended. Either way u made a suggestion github. If its a bug it should be in bugs and reports not in suggestions :) (although im pretty sure its intended)

**Comment by Mikirae** [comment]
I believe this is just the way it works in Pixelmon. Not sure if it’s a bug on their end, or if it’s how it happens in the games. 
But, since it’s a thing on their end, we can’t do much, unfortunately.
