### ISSUE TITLE
Ultranecrozium Z Drop

### ISSUE THREAD

**Issue by GiffyG** [SmashMC-Development/Suggestions#964]
**Describe the suggestion**
Ultranecrozium-Z should be added a 10% chance drop from defeating a wild Necrozma.

**Which servers does this apply to?**
All

**Additional context**
It was initially active in the prior reset, but inactive in this current reset. Requesting to be re-activated.

**Comment by Mikirae** [comment]
Added this and many more to drops. Will announce when the list is a bit bigger :)
Thank you for the suggestion!
