### ISSUE TITLE
bring back /warp aura

### ISSUE THREAD

**Issue by Itslyr1cal** [SmashMC-Development/Suggestions#974]
it would be like it was last reset so like if you would do /warp aura you could see what all the auras looked like and what the different animations were so you were able to see what you liked the most and what you wanted to put on ur mon.

all server so: rayquaza
groudon
kyogre
kyurem
reshiram
and zekrom

N/A

**Comment by Archie4690** [comment]
Hey Lyr1cals, this has been added to the server! Thank you for your suggestion!
