### ISSUE TITLE
shop stuff

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Suggestions#996]
**Describe the suggestion**

block shop
- add netherbrick block
- add netherwart block
- add red netherbrick block
- add gravel
- add coarse dirt

ore shop
- add silicon
- add redstone

black mart shop
- add legendary items like before reset
- add evo items (as a separate shopkeeper)

breeder shop
- add dispensers

other
this list is to reorganize that damn shopkeeper's item list...like damn its long
- add a dye shopkeeper to block shop 
- add a concrete shopkeeper to block shop 
- add a mason shopkeeper to block shop

**Which servers does this apply to?**
all pixelmon servers

**Additional context**
just stuff I want, if possible.

**Comment by Superfire96** [comment]
Added everything above to the block shop, same for the ore shop. Legendary items will not be added back to the black mart. A shopkeeper with the evolution items was added yesterday, same for the dispensers. Will try to re-organize them when possible
